-- =====================================================
-- 일본어 퀴즈 시드: ADVANCED (고급) - Part 2 [51~100]
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_51', '「禍福は糾える縄の如し」の意味は？', '["幸不幸は予測できない","縄を作ること","福を祈ること","禍を避ける方法"]', 0, '화와 복은 서로 얽힌 새끼줄과 같다 = 행불행은 예측할 수 없다.', 51),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_52', '「漸次」の読み方は？', '["ぜんじ","ざんじ","ぜんし","ざんし"]', 0, '"ぜんじ" = 점차.', 52),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_53', '「逡巡」の読み方・意味は？', '["しゅんじゅん・ためらう","じゅんじゅん・進む","しゅんしゅん・急ぐ","じゅんじゅん・回る"]', 0, '"しゅんじゅん" = 주저하다/망설이다.', 53),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_54', '社長に（　）、会議を始めます。', '["なられましたら","おなりになりましたら","なりましたら","なれましたら"]', 1, '"おなりになりましたら"가 최고 경어.', 54),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_55', '「蛇足」の意味は？', '["蛇の足","余計なこと","短い文章","急いで書く"]', 1, '사족 = 불필요한 것.', 55),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_56', '「馬耳東風」の意味は？', '["馬の耳に風","人の意見を聞かない","風が吹く","馬が走る"]', 1, '마이동풍 = 남의 말을 귀담아 듣지 않음.', 56),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_57', '交渉（　）末、合意に達した。', '["の","した","に","を"]', 0, '"交渉の末" = 교섭 끝에.', 57),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_58', '「呈する」の意味は？', '["差し上げる","受け取る","断る","隠す"]', 0, '"呈する" = 바치다/드리다.', 58),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_59', '「吝嗇」の読み方は？', '["りんしょく","りんしょ","じんしょく","きんしょく"]', 0, '"りんしょく" = 인색/구두쇠.', 59),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_60', '「塞翁が馬」の意味は？', '["馬を失う","幸不幸は予測できない","馬に乗る","老人の知恵"]', 1, '새옹지마 = 행불행은 예측할 수 없다.', 60),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_61', '～に（　）、ご挨拶申し上げます。', '["あたり","際し","おいて","つき"]', 1, '"～に際し" = ～에 즈음하여.', 61),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_62', '「四面楚歌」の意味は？', '["四方が敵","楚の歌","四つの面","国を守る"]', 0, '사면초가 = 사방이 적.', 62),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_63', '「率先垂範」の意味は？', '["先頭に立って手本を示す","率を計算する","範囲を広げる","先に進む"]', 0, '솔선수범.', 63),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_64', '「呈する」の意味は？', '["提出する","表す/差し上げる","呼ぶ","始める"]', 1, '"呈する" = 나타내다/드리다.', 64),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_65', '「虎穴に入らずんば虎子を得ず」', '["虎を捕まえる","危険を冒さなければ成果はない","虎を恐れる","穴を掘る"]', 1, '호혈에 들어가지 않으면 호자를 얻지 못한다.', 65),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_66', '「杜撰」の読み方は？', '["ずさん","ずさ","とさん","もりさん"]', 0, '"ずさん" = 엉성한/허술한.', 66),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_67', '「措置」の読み方は？', '["そち","そうち","しょち","ちょち"]', 0, '"そち" = 조치.', 67),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_68', '事態は深刻（　）一方だ。', '["になる","になっている","をきわめる","の"]', 0, '"～になる一方だ" = 점점 ～해지는 한편이다.', 68),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_69', '「灯台もと暗し」の意味は？', '["灯台が壊れた","身近なことに気づかない","暗い場所","灯台を直す"]', 1, '등잔 밑이 어둡다.', 69),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_70', '「急がば回れ」の意味は？', '["急いで走れ","急ぐときこそ安全な道を","回り道する","急ぐ必要はない"]', 1, '급할수록 돌아가라.', 70),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_71', '「弊社」の使い方として正しいのは？', '["自分の会社を指す","相手の会社を指す","どちらでも使える","第三者の会社を指す"]', 0, '"弊社"는 자사를 겸양하여 말하는 표현.', 71),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_72', '「御社」の使い方として正しいのは？', '["自分の会社","相手の会社(口頭)","第三者の会社","書面での自社"]', 1, '"御社"는 상대 회사를 높이는 구어체.', 72),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_73', '「貴社」と「御社」の違いは？', '["同じ意味","貴社は文面、御社は口頭","貴社は口頭、御社は文面","使い方は逆"]', 1, '"貴社"는 문어체, "御社"는 구어체.', 73),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_74', '「二律背反」の意味は？', '["二つの法則が矛盾する","二つのことを同時にする","二回繰り返す","二つの意見が一致する"]', 0, '이율배반 = 두 명제가 모순됨.', 74),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_75', '「披露」の読み方は？', '["ひろう","ひろ","ぴろう","びろう"]', 0, '"ひろう" = 피로/공개하다.', 75),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_76', '技術の進歩（　）、生活は便利になった。', '["にともなって","ともなって","にしたがって","すべて正しい"]', 3, '모두 "～에 따라" 의미로 사용 가능.', 76),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_77', '「言語道断」の読み方は？', '["ごんごどうだん","げんごどうだん","げんごみちだん","ごんごみちだん"]', 0, '"ごんごどうだん" = 언어도단.', 77),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_78', '「傍若無人」の意味は？', '["人がいない","周りを気にしない態度","無人島","一人で行動する"]', 1, '방약무인 = 주위를 무시하는 태도.', 78),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_79', '「閑古鳥が鳴く」の意味は？', '["鳥が鳴いている","客が来なくて寂しい","静かで平和","古い鳥"]', 1, '한가한 새 = 손님이 없어 쓸쓸하다.', 79),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_80', '「腑に落ちない」の意味は？', '["胃が痛い","納得できない","落ち着かない","腹が立つ"]', 1, '납득이 안 된다.', 80),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_81', '「疎い」の読み方は？', '["うとい","あらい","そい","かたい"]', 0, '"うとい" = 어둡다/소원하다.', 81),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_82', '「概ね」の読み方は？', '["おおむね","がいね","およびね","おもむね"]', 0, '"おおむね" = 대체로.', 82),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_83', '「速やかに」の読み方は？', '["すみやかに","はやかに","そくやかに","すべやかに"]', 0, '"すみやかに" = 신속하게.', 83),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_84', '「著しい」の読み方は？', '["いちじるしい","あらわしい","ちょしい","きわしい"]', 0, '"いちじるしい" = 현저한.', 84),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_85', '「如何」の読み方として正しいのは？', '["いかが","いかん","どちらも正しい","にょか"]', 2, '"いかが"と"いかん" 둘 다 사용 가능.', 85),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_86', '「猪突猛進」の意味は？', '["猪を追いかける","向こう見ずに突き進む","勇敢に戦う","謙虚に進む"]', 1, '저돌맹진 = 무모하게 돌진하다.', 86),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_87', '「花鳥風月」の意味は？', '["花と鳥だけ","自然の美しい風景","花見の季節","鳥を観察する"]', 1, '화조풍월 = 자연의 아름다운 풍경.', 87),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_88', '「不撓不屈」の読み方は？', '["ふとうふくつ","ふじょうふくつ","ふとうふきゅう","ぶとうぶくつ"]', 0, '"ふとうふくつ" = 불요불굴.', 88),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_89', '「泰然自若」の意味は？', '["落ち着いて動じない","自然体でいる","泰山のように大きい","自分を信じる"]', 0, '태연자약 = 침착하여 동요하지 않음.', 89),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_90', '「鶴の一声」の意味は？', '["鶴が鳴く","権力者の一言で決まる","一声で呼ぶ","鶴を飼う"]', 1, '학의 한 마디 = 권력자의 한마디로 결정됨.', 90),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_91', '時代の変化に（　）、制度も変わるべきだ。', '["即して","応じて","準じて","すべて使える"]', 3, '"即して/応じて/準じて" 모두 사용 가능.', 91),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_92', '「白日の下に晒す」の意味は？', '["日光浴する","秘密を明るみに出す","白い日","下に置く"]', 1, '백일하에 드러내다 = 비밀을 공개하다.', 92),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_93', '「慧眼」の読み方は？', '["けいがん","えがん","さいがん","すいがん"]', 0, '"けいがん" = 혜안/통찰력.', 93),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_94', '「忖度と推察」の違いは？', '["同じ意味","忖度は相手の意向を推し量る、推察は事実を推測する","忖度は事実を推測する","推察は相手の気持ちを推し量る"]', 1, '손타쿠는 의향을 헤아림, 추찰은 사실을 추측.', 94),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_95', '「我田引水」の意味は？', '["田に水を引く","自分に都合よく解釈する","水を大切にする","田を耕す"]', 1, '아전인수 = 자기에게 유리하게 해석.', 95),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_96', '「喧喧囂囂」の読み方は？', '["けんけんごうごう","やかましい","そうぞうしい","けんけんがくがく"]', 0, '"けんけんごうごう" = 시끌시끌.', 96),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_97', '「侃侃諤諤」の読み方は？', '["かんかんがくがく","けんけんごうごう","がんがん","かんかくかく"]', 0, '"かんかんがくがく" = 활발하게 토론하다.', 97),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_98', '「呉越同舟」の意味は？', '["一緒に船に乗る","敵同士が協力する","同じ船で戦う","舟を漕ぐ"]', 1, '오월동주 = 적끼리도 위기에는 협력.', 98),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_99', '「朝令暮改」の意味は？', '["朝に命令して夕方に変える","毎日命令する","朝から働く","命令を守る"]', 0, '조령모개 = 아침에 명하고 저녁에 바꿈.', 99),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_100', '「適材適所」の意味は？', '["場所を選ぶ","人を能力に合った場所に配置","材料を選ぶ","適切な場所"]', 1, '적재적소 = 능력에 맞게 배치.', 100)
ON CONFLICT (question_id) DO NOTHING;
