-- =====================================================
-- English Quiz Seed: INTERMEDIATE Part 1 [1~50]
-- Tenses, phrasal verbs, conditionals, comparatives
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_1', 'I ___ already ___ lunch. (have/eat)', '["have / eat","have / ate","have / eaten","has / eaten"]', 2, '현재완료: have + 과거분사(eaten).', 1),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_2', 'She ___ never ___ to Japan. (has/be)', '["has / be","has / been","have / been","has / went"]', 1, '현재완료: has + been.', 2),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_3', 'If I ___ rich, I would travel the world.', '["am","was","were","be"]', 2, '가정법 과거에서는 "were"를 씁니다.', 3),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_4', 'If it rains, I ___ stay home.', '["will","would","could","might"]', 0, '조건절(1형): If + 현재, will + 동사원형.', 4),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_5', '"look up"의 뜻은?', '["위를 보다","찾아보다","둘 다 맞음","정리하다"]', 2, '"look up"은 위를 보다 / (사전에서) 찾아보다.', 5),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_6', '"give up"의 뜻은?', '["주다","포기하다","돌려주다","나눠주다"]', 1, '"give up" = 포기하다.', 6),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_7', '"turn off"의 뜻은?', '["돌리다","켜다","끄다","돌아서다"]', 2, '"turn off" = (전원을) 끄다.', 7),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_8', '"put on"의 뜻은?', '["놓다","입다/쓰다","내려놓다","벗다"]', 1, '"put on" = (옷/모자 등을) 입다/쓰다.', 8),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_9', '"take off"의 뜻은?', '["이륙하다","벗다","둘 다 맞음","가져가다"]', 2, '"take off" = 이륙하다 / (옷을) 벗다.', 9),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_10', 'He is ___ than his brother. (tall)', '["tall","taller","tallest","more tall"]', 1, '비교급: -er (taller).', 10),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_11', 'She is the ___ student in class. (smart)', '["smart","smarter","smartest","most smart"]', 2, '최상급: -est (smartest).', 11),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_12', 'This book is ___ interesting than that one.', '["more","most","much","many"]', 0, '다음절 형용사 비교급: more + 형용사.', 12),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_13', 'The movie was ___ boring ___ I expected.', '["more / than","most / than","as / as","less / as"]', 0, '"more ~ than" = ~보다 더.', 13),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_14', 'I have been ___ here for 2 hours. (wait)', '["wait","waited","waiting","to wait"]', 2, '현재완료진행: have been + ~ing.', 14),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_15', 'The cake was ___ by my mom. (수동태)', '["make","made","making","makes"]', 1, '수동태: was + 과거분사(made).', 15),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_16', '"break down"의 뜻은?', '["고장나다","부수다","분해하다","모두 맞음"]', 3, '"break down"은 고장나다/부수다/분해하다 모두 가능.', 16),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_17', '"run out of"의 뜻은?', '["달려가다","벗어나다","다 떨어지다","도망치다"]', 2, '"run out of" = ~이 다 떨어지다.', 17),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_18', '"come up with"의 뜻은?', '["올라오다","생각해내다","따라잡다","만나다"]', 1, '"come up with" = (아이디어를) 생각해내다.', 18),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_19', '"look forward to"의 뜻은?', '["앞을 보다","기대하다","찾아보다","돌아보다"]', 1, '"look forward to" = ~을 기대하다.', 19),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_20', 'I wish I ___ speak French.', '["can","could","will","would"]', 1, '소망의 가정법: wish + 과거 (could).', 20),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_21', 'You ___ better study hard. (충고)', '["had","have","should","would"]', 0, '"had better" = ~하는 게 좋겠다.', 21),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_22', 'He ___ to be a doctor when he grows up.', '["want","wants","wanting","wanted"]', 1, '3인칭 단수 현재: wants.', 22),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_23', 'I ___ lived in Seoul since 2010.', '["have","has","had","am"]', 0, '현재완료 + since: have lived.', 23),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_24', 'She told me ___ she was tired.', '["what","which","that","who"]', 2, '명사절 접속사 "that".', 24),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_25', 'The man ___ is standing there is my father.', '["who","which","what","whose"]', 0, '사람 관계대명사: who.', 25),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_26', 'The book ___ I read was interesting.', '["who","which","what","whose"]', 1, '사물 관계대명사: which (또는 that).', 26),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_27', '"used to"의 의미는?', '["~에 익숙하다","~하곤 했다","사용하다","둘 다 맞음"]', 1, '"used to" = (과거에) ~하곤 했다.', 27),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_28', '"be used to"의 의미는?', '["~에 익숙하다","~하곤 했다","사용되다","사용하다"]', 0, '"be used to" = ~에 익숙하다.', 28),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_29', 'I will call you ___ I arrive.', '["since","until","when","during"]', 2, '"when" = ~할 때.', 29),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_30', '___ it was raining, we went outside.', '["Because","Although","If","Unless"]', 1, '"Although" = ~에도 불구하고.', 30),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_31', '"get along with"의 뜻은?', '["따라가다","사이좋게 지내다","극복하다","시작하다"]', 1, '"get along with" = ~와 사이좋게 지내다.', 31),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_32', '"figure out"의 뜻은?', '["알아내다","적어두다","빠져나가다","체형을 가꾸다"]', 0, '"figure out" = 알아내다/이해하다.', 32),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_33', 'Neither Tom ___ Jerry likes math.', '["or","and","nor","but"]', 2, '"Neither A nor B" 구문.', 33),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_34', 'Not only is she smart, ___ she is kind.', '["and","or","but also","so"]', 2, '"Not only ~ but also ~" 구문.', 34),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_35', '"경험"을 영어로?', '["Experience","Experiment","Expert","Expect"]', 0, '"Experience"는 경험입니다.', 35),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_36', '"실험"을 영어로?', '["Experience","Experiment","Expert","Expect"]', 1, '"Experiment"는 실험입니다.', 36),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_37', '"기대하다"를 영어로?', '["Experience","Experiment","Expert","Expect"]', 3, '"Expect"는 기대하다입니다.', 37),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_38', '"환경"을 영어로?', '["Environment","Equipment","Entertainment","Encouragement"]', 0, '"Environment"는 환경입니다.', 38),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_39', 'I am interested ___ music.', '["on","in","at","for"]', 1, '"interested in" = ~에 관심있다.', 39),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_40', 'She is afraid ___ spiders.', '["on","in","at","of"]', 3, '"afraid of" = ~을 무서워하다.', 40),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_41', '"뜻밖의"를 영어로?', '["Unexpected","Expected","Usual","Normal"]', 0, '"Unexpected"는 뜻밖의입니다.', 41),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_42', '"광고"를 영어로?', '["Advertisement","Advice","Adventure","Advantage"]', 0, '"Advertisement"는 광고입니다.', 42),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_43', '"조언/충고"를 영어로?', '["Advertisement","Advice","Adventure","Advantage"]', 1, '"Advice"는 조언입니다.', 43),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_44', '"이점"을 영어로?', '["Advertisement","Advice","Adventure","Advantage"]', 3, '"Advantage"는 이점/장점입니다.', 44),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_45', 'The meeting has been ___ to next week. (연기하다)', '["postponed","proposed","promoted","provided"]', 0, '"postpone" = 연기하다.', 45),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_46', 'I need to ___ a decision soon. (결정하다)', '["do","make","take","get"]', 1, '"make a decision" = 결정하다.', 46),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_47', '"비록 ~일지라도"를 영어로?', '["Although","Because","Unless","While"]', 0, '"Although" = 비록 ~일지라도.', 47),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_48', '"~하지 않는 한"을 영어로?', '["Although","Because","Unless","While"]', 2, '"Unless" = ~하지 않는 한.', 48),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_49', '"동의하다"를 영어로?', '["Agree","Argue","Accept","Allow"]', 0, '"Agree"는 동의하다입니다.', 49),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_50', '"허락하다"를 영어로?', '["Agree","Argue","Accept","Allow"]', 3, '"Allow"는 허락하다입니다.', 50)
ON CONFLICT (question_id) DO NOTHING;


INSERT INTO quiz_questions (correct_option_index, created_at, explanation, options, question, question_id, sort_order, set_id) VALUES
-- 1~20: 현재완료 및 과거완료 (완료시제)
(1, CURRENT_TIMESTAMP, '경험을 나타내는 현재완료형(have/has p.p)이 적절합니다.', '["go", "have been", "went", "had gone"]', 'I ___ to Paris three times.', 'en_im_fb_1', 1, 11),
(0, CURRENT_TIMESTAMP, 'since(이후로 쭉)와 어울리는 현재완료 진행형이 적절합니다.', '["have been studying", "studied", "study", "am studying"]', 'They ___ English since 2020.', 'en_im_fb_2', 2, 11),
(2, CURRENT_TIMESTAMP, 'just가 있으므로 현재완료 완료용법이 적절합니다.', '["finish", "finished", "have just finished", "had finished"]', 'I ___ my homework.', 'en_im_fb_3', 3, 11),
(3, CURRENT_TIMESTAMP, 'yet과 어울리는 현재완료 부정문이 적절합니다.', '["did not arrive", "arrives", "is arriving", "has not arrived"]', 'The train ___ yet.', 'en_im_fb_4', 4, 11),
(1, CURRENT_TIMESTAMP, '과거의 특정 시점(arrived)보다 먼저 일어난 일이므로 과거완료(had p.p)를 씁니다.', '["leaves", "had left", "has left", "left"]', 'When I arrived, the train ___.', 'en_im_fb_5', 5, 11),
(0, CURRENT_TIMESTAMP, '과거 이전에 잃어버린 것이므로 과거완료를 씁니다.', '["had lost", "lost", "have lost", "lose"]', 'I couldn''t find the watch I ___.', 'en_im_fb_6', 6, 11),
(2, CURRENT_TIMESTAMP, '현재까지 결과가 이어지므로 현재완료(has gone: 가버렸다)가 적절합니다.', '["goes", "went", "has gone", "had gone"]', 'She ___ to London, so she isn''t here.', 'en_im_fb_7', 7, 11),
(1, CURRENT_TIMESTAMP, 'for five years와 어울리는 현재완료형이 적절합니다.', '["know", "have known", "knew", "had known"]', 'We ___ each other for five years.', 'en_im_fb_8', 8, 11),
(3, CURRENT_TIMESTAMP, '과거의 두 동작 중 먼저 일어난 동작(had finished)입니다.', '["finish", "finished", "have finished", "had finished"]', 'I went to bed after I ___ the work.', 'en_im_fb_9', 9, 11),
(0, CURRENT_TIMESTAMP, 'ever가 들어간 경험을 묻는 현재완료 의문문입니다.', '["Have", "Did", "Do", "Are"]', '___ you ever eaten Mexican food?', 'en_im_fb_10', 10, 11),
(2, CURRENT_TIMESTAMP, '과거의 과거(대과거)를 나타내는 had seen이 적절합니다.', '["see", "saw", "had seen", "have seen"]', 'He said he ___ the movie before.', 'en_im_fb_11', 11, 11),
(1, CURRENT_TIMESTAMP, 'lately(최근에)와 어울리는 현재완료형이 적절합니다.', '["was", "has been", "is", "had been"]', 'She ___ very busy lately.', 'en_im_fb_12', 12, 11),
(0, CURRENT_TIMESTAMP, 'before(~하기 전에) 과거 시점보다 앞선 일이므로 과거완료를 씁니다.', '["had met", "met", "have met", "meet"]', 'I realized that I ___ him before.', 'en_im_fb_13', 13, 11),
(3, CURRENT_TIMESTAMP, 'how long(얼마나 오래)과 어울리는 현재완료형입니다.', '["did you live", "do you live", "are you living", "have you lived"]', 'How long ___ here?', 'en_im_fb_14', 14, 11),
(1, CURRENT_TIMESTAMP, 'when절이 과거이므로 주절은 과거완료 진행형이 적절합니다.', '["has been waiting", "had been waiting", "is waiting", "was waiting"]', 'She ___ for an hour when he arrived.', 'en_im_fb_15', 15, 11),
(2, CURRENT_TIMESTAMP, '현재완료 계속용법입니다.', '["am", "was", "have been", "had been"]', 'I ___ sick since yesterday.', 'en_im_fb_16', 16, 11),
(0, CURRENT_TIMESTAMP, '이미 완료되었으므로 already를 쓰는 현재완료가 적절합니다.', '["has already started", "already started", "started already", "had already started"]', 'The meeting ___.', 'en_im_fb_17', 17, 11),
(1, CURRENT_TIMESTAMP, '과거(did not know) 시점까지의 경험이므로 과거완료를 씁니다.', '["have never seen", "had never seen", "never saw", "never see"]', 'I didn''t know who he was; I ___ him.', 'en_im_fb_18', 18, 11),
(3, CURRENT_TIMESTAMP, '최상급 수식을 받는 경험의 현재완료 구문입니다.', '["read", "am reading", "had read", "have ever read"]', 'This is the best book I ___.', 'en_im_fb_19', 19, 11),
(2, CURRENT_TIMESTAMP, '현재 시점의 완료(마침내 해냈다)를 나타냅니다.', '["finally did", "am finally doing", "have finally done", "had finally done"]', 'I ___ it!', 'en_im_fb_20', 20, 11),

-- 21~40: 수동태 (Passive Voice)
(1, CURRENT_TIMESTAMP, '과거형 수동태(be p.p + by)가 적절합니다.', '["wrote", "was written", "writes", "has written"]', 'This book ___ by Shakespeare.', 'en_im_fb_21', 21, 11),
(0, CURRENT_TIMESTAMP, '현재형 수동태(are + p.p)가 적절합니다.', '["are spoken", "speak", "is spoken", "spoke"]', 'Many languages ___ in India.', 'en_im_fb_22', 22, 11),
(2, CURRENT_TIMESTAMP, '조동사가 있는 수동태(will be p.p)가 적절합니다.', '["will build", "build", "will be built", "is building"]', 'A new bridge ___ next year.', 'en_im_fb_23', 23, 11),
(3, CURRENT_TIMESTAMP, '현재진행형 수동태(be being p.p)가 적절합니다.', '["is repairing", "repairs", "repaired", "is being repaired"]', 'My car ___ right now.', 'en_im_fb_24', 24, 11),
(1, CURRENT_TIMESTAMP, '현재완료 수동태(have been p.p)가 적절합니다.', '["have painted", "have been painted", "are painting", "painted"]', 'The walls ___.', 'en_im_fb_25', 25, 11),
(0, CURRENT_TIMESTAMP, '조동사 수동태(can be p.p)가 적절합니다.', '["can be seen", "can see", "sees", "is seen"]', 'The stars ___ at night.', 'en_im_fb_26', 26, 11),
(2, CURRENT_TIMESTAMP, '수동태의 부정문(was not p.p)이 적절합니다.', '["didn''t invite", "was not inviting", "was not invited", "not invited"]', 'I ___ to the party.', 'en_im_fb_27', 27, 11),
(1, CURRENT_TIMESTAMP, 'be covered with(~로 덮여 있다) 전치사 구문입니다.', '["by", "with", "in", "of"]', 'The mountain is covered ___ snow.', 'en_im_fb_28', 28, 11),
(3, CURRENT_TIMESTAMP, 'be surprised at(~에 놀라다) 전치사 구문입니다.', '["by", "with", "in", "at"]', 'She was surprised ___ the news.', 'en_im_fb_29', 29, 11),
(0, CURRENT_TIMESTAMP, 'be interested in(~에 관심이 있다) 전치사 구문입니다.', '["in", "on", "about", "with"]', 'He is interested ___ history.', 'en_im_fb_30', 30, 11),
(2, CURRENT_TIMESTAMP, '과거 수동태 의문문(Was + S + p.p)이 적절합니다.', '["Did", "Does", "Was", "Were"]', '___ the window broken by him?', 'en_im_fb_31', 31, 11),
(1, CURRENT_TIMESTAMP, 'be known for(~로 유명하다) 전치사 구문입니다.', '["as", "for", "to", "by"]', 'Korea is known ___ Kimchi.', 'en_im_fb_32', 32, 11),
(3, CURRENT_TIMESTAMP, 'be known to(~에게 알려져 있다) 전치사 구문입니다.', '["as", "for", "by", "to"]', 'The secret is known ___ everyone.', 'en_im_fb_33', 33, 11),
(0, CURRENT_TIMESTAMP, 'be made of(물리적 변화) 전치사 구문입니다.', '["of", "from", "with", "by"]', 'This desk is made ___ wood.', 'en_im_fb_34', 34, 11),
(1, CURRENT_TIMESTAMP, 'be made from(화학적 변화) 전치사 구문입니다.', '["of", "from", "with", "into"]', 'Wine is made ___ grapes.', 'en_im_fb_35', 35, 11),
(2, CURRENT_TIMESTAMP, 'be filled with(~로 가득 차 있다) 전치사 구문입니다.', '["of", "by", "with", "in"]', 'The room was filled ___ smoke.', 'en_im_fb_36', 36, 11),
(0, CURRENT_TIMESTAMP, '수여동사의 수동태입니다. (주어에게 주어지다)', '["was given", "gave", "has given", "was giving"]', 'I ___ a present by him.', 'en_im_fb_37', 37, 11),
(1, CURRENT_TIMESTAMP, '5형식 동사 call의 수동태 구문(S + is called + 명사)입니다.', '["calls", "is called", "calling", "has called"]', 'This animal ___ a kangaroo.', 'en_im_fb_38', 38, 11),
(3, CURRENT_TIMESTAMP, '과거진행형 수동태(was being p.p)가 적절합니다.', '["is watched", "watched", "was watching", "was being watched"]', 'I felt that I ___.', 'en_im_fb_39', 39, 11),
(2, CURRENT_TIMESTAMP, '조동사 must의 수동태 구문입니다.', '["must do", "must have done", "must be done", "is done"]', 'The work ___ by tomorrow.', 'en_im_fb_40', 40, 11),

-- 41~60: 관계대명사 (Relative Pronouns)
(0, CURRENT_TIMESTAMP, '선행사가 사람이고 주격이므로 who가 적절합니다.', '["who", "which", "whom", "what"]', 'The boy ___ is playing the piano is my brother.', 'en_im_fb_41', 41, 11),
(1, CURRENT_TIMESTAMP, '선행사가 사물이고 주격이므로 which(또는 that)가 적절합니다.', '["who", "which", "whom", "where"]', 'I bought a car ___ is very fast.', 'en_im_fb_42', 42, 11),
(2, CURRENT_TIMESTAMP, '선행사가 사람이고 목적격이므로 whom(또는 who/that)이 적절합니다.', '["which", "whose", "whom", "what"]', 'The man ___ I met yesterday is a doctor.', 'en_im_fb_43', 43, 11),
(3, CURRENT_TIMESTAMP, '소유의 의미(~의)를 나타내므로 소유격 whose가 적절합니다.', '["who", "whom", "which", "whose"]', 'I know a girl ___ father is a teacher.', 'en_im_fb_44', 44, 11),
(0, CURRENT_TIMESTAMP, '선행사를 포함하는 관계대명사 what(~하는 것)이 적절합니다.', '["what", "that", "which", "who"]', 'This is exactly ___ I wanted.', 'en_im_fb_45', 45, 11),
(1, CURRENT_TIMESTAMP, '선행사가 최상급(the only)의 수식을 받으므로 that이 주로 쓰입니다.', '["which", "that", "what", "who"]', 'He is the only person ___ can help me.', 'en_im_fb_46', 46, 11),
(2, CURRENT_TIMESTAMP, '장소를 나타내는 관계부사 where가 적절합니다.', '["when", "which", "where", "how"]', 'This is the house ___ I was born.', 'en_im_fb_47', 47, 11),
(0, CURRENT_TIMESTAMP, '시간을 나타내는 관계부사 when이 적절합니다.', '["when", "where", "why", "how"]', 'I remember the day ___ we first met.', 'en_im_fb_48', 48, 11),
(3, CURRENT_TIMESTAMP, '이유를 나타내는 관계부사 why가 적절합니다.', '["where", "when", "how", "why"]', 'Tell me the reason ___ you were late.', 'en_im_fb_49', 49, 11),
(1, CURRENT_TIMESTAMP, 'the way와 how는 함께 쓸 수 없으므로 how만 씁니다.', '["why", "how", "where", "which"]', 'This is ___ he solved the problem.', 'en_im_fb_50', 50, 11),
(2, CURRENT_TIMESTAMP, '계속적 용법(콤마 뒤)이므로 which가 적절합니다. (that은 불가)', '["that", "what", "which", "where"]', 'He gave me a book, ___ was very interesting.', 'en_im_fb_51', 51, 11),
(0, CURRENT_TIMESTAMP, '전치사 in 뒤에 사물이 올 때는 which를 씁니다.', '["which", "that", "where", "what"]', 'The city in ___ I live is very large.', 'en_im_fb_52', 52, 11),
(1, CURRENT_TIMESTAMP, '전치사 with 뒤에 사람이 올 때는 whom을 씁니다.', '["who", "whom", "that", "whose"]', 'The woman with ___ I was talking is my boss.', 'en_im_fb_53', 53, 11),
(3, CURRENT_TIMESTAMP, '주어가 빠져있는 불완전한 문장이므로 주격 관계대명사가 필요합니다.', '["what", "where", "whose", "that"]', 'I need a phone ___ has a good camera.', 'en_im_fb_54', 54, 11),
(2, CURRENT_TIMESTAMP, '목적어가 빠져있고 선행사가 없으므로 what이 적절합니다.', '["that", "which", "what", "where"]', 'Do you understand ___ I am saying?', 'en_im_fb_55', 55, 11),
(0, CURRENT_TIMESTAMP, 'anyone who ~ (~하는 사람은 누구나) 구문입니다.', '["who", "whom", "which", "what"]', 'Anyone ___ wants to join can sign up.', 'en_im_fb_56', 56, 11),
(1, CURRENT_TIMESTAMP, '선행사가 사람+사물일 경우 that을 주로 씁니다.', '["which", "that", "who", "what"]', 'Look at the boy and his dog ___ are running there.', 'en_im_fb_57', 57, 11),
(2, CURRENT_TIMESTAMP, '계속적 용법의 사람 주격이므로 who가 적절합니다.', '["that", "which", "who", "whom"]', 'My father, ___ is 60 years old, still runs every day.', 'en_im_fb_58', 58, 11),
(3, CURRENT_TIMESTAMP, '~하는 것은 무엇이든(복합관계대명사) whatever가 적절합니다.', '["whoever", "whichever", "whenever", "whatever"]', 'You can do ___ you want.', 'en_im_fb_59', 59, 11),
(0, CURRENT_TIMESTAMP, '~하는 사람은 누구든(복합관계대명사) whoever가 적절합니다.', '["Whoever", "Whatever", "Whomever", "Whichever"]', '___ comes first will get the prize.', 'en_im_fb_60', 60, 11),

-- 61~80: To부정사와 동명사
(1, CURRENT_TIMESTAMP, 'want는 to부정사를 목적어로 취합니다.', '["going", "to go", "go", "gone"]', 'I want ___ home early today.', 'en_im_fb_61', 61, 11),
(0, CURRENT_TIMESTAMP, 'enjoy는 동명사를 목적어로 취합니다.', '["reading", "to read", "read", "reads"]', 'She enjoys ___ comic books.', 'en_im_fb_62', 62, 11),
(2, CURRENT_TIMESTAMP, 'hope는 to부정사를 목적어로 취합니다.', '["seeing", "see", "to see", "saw"]', 'I hope ___ you again soon.', 'en_im_fb_63', 63, 11),
(1, CURRENT_TIMESTAMP, 'finish는 동명사를 목적어로 취합니다.', '["to eat", "eating", "eat", "eaten"]', 'Have you finished ___ your lunch?', 'en_im_fb_64', 64, 11),
(3, CURRENT_TIMESTAMP, 'mind(~를 꺼리다)는 동명사를 목적어로 취합니다.', '["to open", "open", "opened", "opening"]', 'Do you mind ___ the window?', 'en_im_fb_65', 65, 11),
(0, CURRENT_TIMESTAMP, 'decide는 to부정사를 목적어로 취합니다.', '["to stay", "staying", "stay", "stayed"]', 'We decided ___ at a hotel.', 'en_im_fb_66', 66, 11),
(2, CURRENT_TIMESTAMP, 'give up(포기하다)는 동명사를 목적어로 취합니다.', '["to smoke", "smoke", "smoking", "smoked"]', 'He gave up ___ last year.', 'en_im_fb_67', 67, 11),
(1, CURRENT_TIMESTAMP, 'plan은 to부정사를 목적어로 취합니다.', '["traveling", "to travel", "travel", "traveled"]', 'They plan ___ to Europe.', 'en_im_fb_68', 68, 11),
(0, CURRENT_TIMESTAMP, 'stop ~ing는 ~하는 것을 멈추다라는 뜻입니다.', '["talking", "to talk", "talk", "talked"]', 'Stop ___ and listen to me.', 'en_im_fb_69', 69, 11),
(1, CURRENT_TIMESTAMP, 'stop to V는 ~하기 위해 멈추다라는 뜻입니다.', '["resting", "to rest", "rest", "rested"]', 'We stopped ___ on the way.', 'en_im_fb_70', 70, 11),
(2, CURRENT_TIMESTAMP, 'remember ~ing는 (과거에) ~한 것을 기억하다라는 뜻입니다.', '["to lock", "lock", "locking", "locked"]', 'I remember ___ the door yesterday.', 'en_im_fb_71', 71, 11),
(0, CURRENT_TIMESTAMP, 'remember to V는 (미래에) ~할 것을 기억하다라는 뜻입니다.', '["to bring", "bringing", "bring", "brought"]', 'Remember ___ your umbrella tomorrow.', 'en_im_fb_72', 72, 11),
(1, CURRENT_TIMESTAMP, 'forget ~ing는 (과거에) ~한 것을 잊다라는 뜻입니다.', '["to meet", "meeting", "meet", "met"]', 'I will never forget ___ you.', 'en_im_fb_73', 73, 11),
(3, CURRENT_TIMESTAMP, 'forget to V는 (미래에) ~할 것을 깜빡하다라는 뜻입니다.', '["calling", "call", "called", "to call"]', 'Don''t forget ___ me tonight.', 'en_im_fb_74', 74, 11),
(0, CURRENT_TIMESTAMP, 'look forward to 뒤에는 동명사(~ing)가 옵니다.', '["seeing", "see", "to see", "saw"]', 'I am looking forward to ___ you.', 'en_im_fb_75', 75, 11),
(2, CURRENT_TIMESTAMP, 'be used to ~ing는 ~하는 데 익숙하다라는 뜻입니다.', '["live", "to live", "living", "lived"]', 'I am used to ___ alone.', 'en_im_fb_76', 76, 11),
(1, CURRENT_TIMESTAMP, 'used to V는 (과거에) ~하곤 했다라는 뜻입니다.', '["playing", "play", "to play", "played"]', 'He used to ___ tennis when he was young.', 'en_im_fb_77', 77, 11),
(3, CURRENT_TIMESTAMP, '전치사(without) 뒤에는 동명사가 옵니다.', '["say", "to say", "said", "saying"]', 'He left without ___ goodbye.', 'en_im_fb_78', 78, 11),
(0, CURRENT_TIMESTAMP, '가주어 It ~ 진주어 to부정사 구문입니다.', '["to learn", "learning", "learn", "learned"]', 'It is important ___ English.', 'en_im_fb_79', 79, 11),
(1, CURRENT_TIMESTAMP, 'to부정사의 의미상 주어는 for + 목적격으로 나타냅니다.', '["of", "for", "to", "by"]', 'It is hard ___ me to understand it.', 'en_im_fb_80', 80, 11),

-- 81~100: 분사 및 분사구문 (Participles)
(2, CURRENT_TIMESTAMP, '능동적으로 울고 있는 아기이므로 현재분사(crying)가 적절합니다.', '["cry", "cried", "crying", "to cry"]', 'Look at the ___ baby.', 'en_im_fb_81', 81, 11),
(1, CURRENT_TIMESTAMP, '수동적으로 깨진 창문이므로 과거분사(broken)가 적절합니다.', '["break", "broken", "breaking", "broke"]', 'Be careful with the ___ window.', 'en_im_fb_82', 82, 11),
(0, CURRENT_TIMESTAMP, '놀라움을 주는(능동) 소식이므로 surprising이 적절합니다.', '["surprising", "surprised", "surprise", "to surprise"]', 'The news was very ___.', 'en_im_fb_83', 83, 11),
(3, CURRENT_TIMESTAMP, '놀라움을 느낀(수동) 주체이므로 surprised가 적절합니다.', '["surprising", "surprise", "to surprise", "surprised"]', 'I was ___ to hear the news.', 'en_im_fb_84', 84, 11),
(1, CURRENT_TIMESTAMP, '지루함을 주는 영화이므로 boring이 적절합니다.', '["bored", "boring", "bore", "to bore"]', 'The movie was so ___ that I fell asleep.', 'en_im_fb_85', 85, 11),
(0, CURRENT_TIMESTAMP, '지루함을 느끼는 주체이므로 bored가 적절합니다.', '["bored", "boring", "bore", "to bore"]', 'The students look ___ today.', 'en_im_fb_86', 86, 11),
(2, CURRENT_TIMESTAMP, '피곤함을 주는 일이므로 tiring이 적절합니다.', '["tired", "tire", "tiring", "to tire"]', 'It was a ___ day.', 'en_im_fb_87', 87, 11),
(1, CURRENT_TIMESTAMP, '피곤함을 느끼는 주체이므로 tired가 적절합니다.', '["tiring", "tired", "tire", "to tire"]', 'I am so ___ right now.', 'en_im_fb_88', 88, 11),
(0, CURRENT_TIMESTAMP, '흥미를 주는 책이므로 interesting이 적절합니다.', '["interesting", "interested", "interest", "to interest"]', 'This book is very ___.', 'en_im_fb_89', 89, 11),
(3, CURRENT_TIMESTAMP, '흥미를 느끼는 주체이므로 interested가 적절합니다.', '["interesting", "interest", "to interest", "interested"]', 'I am ___ in history.', 'en_im_fb_90', 90, 11),
(1, CURRENT_TIMESTAMP, '능동적으로 거리를 걷고 있는 상태이므로 현재분사 구문입니다.', '["Walked", "Walking", "Walk", "To walk"]', '___ along the street, I met a friend.', 'en_im_fb_91', 91, 11),
(0, CURRENT_TIMESTAMP, '수동적으로 (영어로) 쓰여진 상태이므로 과거분사 구문입니다.', '["Written", "Writing", "Write", "Wrote"]', '___ in English, the book is hard to read.', 'en_im_fb_92', 92, 11),
(2, CURRENT_TIMESTAMP, '돈이 없었기 때문에(이유)를 뜻하는 분사구문입니다.', '["Have not", "Not have", "Not having", "Having not"]', '___ any money, I couldn''t buy it.', 'en_im_fb_93', 93, 11),
(1, CURRENT_TIMESTAMP, '다리를 꼰 채로(부대상황)를 나타내는 with + 명사 + 과거분사 구문입니다.', '["crossing", "crossed", "cross", "to cross"]', 'He sat with his legs ___.', 'en_im_fb_94', 94, 11),
(3, CURRENT_TIMESTAMP, '눈을 감은 채로를 나타내는 with + 명사 + 과거분사 구문입니다.', '["closing", "close", "to close", "closed"]', 'She listened to the music with her eyes ___.', 'en_im_fb_95', 95, 11),
(0, CURRENT_TIMESTAMP, '개(dog)가 능동적으로 따라오는 것이므로 현재분사를 씁니다.', '["following", "followed", "follow", "follows"]', 'He walked with his dog ___ him.', 'en_im_fb_96', 96, 11),
(2, CURRENT_TIMESTAMP, '주절보다 한 시제 앞선 완료 분사구문(Having p.p)입니다.', '["Finished", "Finishing", "Having finished", "To finish"]', '___ the work, I went to bed.', 'en_im_fb_97', 97, 11),
(1, CURRENT_TIMESTAMP, '지각동사(saw) + 목적어 + 현재분사(진행의 의미 강조) 구문입니다.', '["ran", "running", "to run", "runs"]', 'I saw him ___ away.', 'en_im_fb_98', 98, 11),
(0, CURRENT_TIMESTAMP, '사역동사(have) + 사물 목적어 + 과거분사(수동의 의미) 구문입니다.', '["cut", "cutting", "to cut", "cuts"]', 'I had my hair ___ yesterday.', 'en_im_fb_99', 99, 11),
(2, CURRENT_TIMESTAMP, '사역동사(get) + 사물 목적어 + 과거분사 구문입니다.', '["fix", "fixing", "fixed", "to fix"]', 'I must get my watch ___.', 'en_im_fb_100', 100, 11),

-- 101~120: 가정법 (Subjunctive Mood)
(0, CURRENT_TIMESTAMP, '가정법 과거의 be동사는 인칭에 상관없이 were를 주로 씁니다.', '["were", "was", "am", "is"]', 'If I ___ a bird, I could fly to you.', 'en_im_fb_101', 101, 101),
(1, CURRENT_TIMESTAMP, '가정법 과거(If S 과거동사, S would/could V) 구문입니다.', '["have", "had", "have had", "having"]', 'If I ___ enough money, I would buy it.', 'en_im_fb_102', 102, 11),
(2, CURRENT_TIMESTAMP, '가정법 과거 주절에는 조동사 과거형+동사원형이 옵니다.', '["will help", "help", "would help", "would have helped"]', 'If I knew his number, I ___ him.', 'en_im_fb_103', 103, 11),
(3, CURRENT_TIMESTAMP, '가정법 과거완료(If S had p.p) 구문입니다.', '["study", "studied", "have studied", "had studied"]', 'If I ___ harder, I would have passed the exam.', 'en_im_fb_104', 104, 11),
(0, CURRENT_TIMESTAMP, '가정법 과거완료 주절에는 would have p.p가 옵니다.', '["would have gone", "would go", "will go", "went"]', 'If it had been sunny, we ___ to the beach.', 'en_im_fb_105', 105, 11),
(1, CURRENT_TIMESTAMP, '현재 사실의 반대를 소망하는 I wish 가정법 과거입니다.', '["am", "were", "was", "will be"]', 'I wish I ___ taller.', 'en_im_fb_106', 106, 11),
(2, CURRENT_TIMESTAMP, '과거 사실에 대한 아쉬움을 나타내는 I wish 가정법 과거완료입니다.', '["did", "have done", "had done", "do"]', 'I wish I ___ it yesterday.', 'en_im_fb_107', 107, 11),
(0, CURRENT_TIMESTAMP, '마치 ~인 것처럼(as if) 가정법 과거 구문입니다.', '["knew", "knows", "know", "had known"]', 'He talks as if he ___ everything.', 'en_im_fb_108', 108, 11),
(3, CURRENT_TIMESTAMP, '과거에 마치 ~였던 것처럼(as if + 과거완료) 구문입니다.', '["saw", "has seen", "see", "had seen"]', 'She acted as if she ___ a ghost.', 'en_im_fb_109', 109, 11),
(1, CURRENT_TIMESTAMP, '~가 없다면(If it were not for) 구문입니다.', '["was", "were", "had been", "is"]', 'If it ___ not for water, we could not live.', 'en_im_fb_110', 110, 11),
(2, CURRENT_TIMESTAMP, '과거에 ~가 없었다면(If it had not been for) 구문입니다.', '["has", "was", "had", "were"]', 'If it ___ not been for your help, I would have failed.', 'en_im_fb_111', 111, 11),
(0, CURRENT_TIMESTAMP, 'Without(~가 없다면)으로 시작하는 가정법 과거 주절입니다.', '["would be", "will be", "is", "was"]', 'Without air, nothing ___ alive.', 'en_im_fb_112', 112, 11),
(1, CURRENT_TIMESTAMP, 'But for(~가 없다면/없었다면) 구문으로 과거완료 주절과 어울립니다.', '["will miss", "would have missed", "missed", "would miss"]', 'But for the map, we ___ our way.', 'en_im_fb_113', 113, 11),
(3, CURRENT_TIMESTAMP, '시간/조건의 부사절에서는 현재가 미래를 대신하므로 rains가 적절합니다.', '["will rain", "rained", "rain", "rains"]', 'If it ___ tomorrow, we will cancel the picnic.', 'en_im_fb_114', 114, 11),
(2, CURRENT_TIMESTAMP, '시간의 부사절(when)에서도 현재 시제가 미래를 대신합니다.', '["will finish", "finished", "finish", "finishes"]', 'I will go out when I ___ my homework.', 'en_im_fb_115', 115, 11),
(0, CURRENT_TIMESTAMP, '~할 때이다(It is time S 과거동사) 구문입니다.', '["went", "go", "will go", "going"]', 'It is time we ___ to bed.', 'en_im_fb_116', 116, 11),
(1, CURRENT_TIMESTAMP, 'If가 생략되면 주어와 조동사가 도치(Were I)됩니다.', '["If I was", "Were I", "Am I", "Was I"]', '___ rich, I would buy a yacht.', 'en_im_fb_117', 117, 11),
(2, CURRENT_TIMESTAMP, 'If가 생략된 가정법 과거완료 도치(Had I known) 구문입니다.', '["If I knew", "Did I know", "Had I known", "Have I known"]', '___ the truth, I would have told you.', 'en_im_fb_118', 118, 11),
(0, CURRENT_TIMESTAMP, '주장/제안/요구의 동사(insist) 뒤 that절의 동사는 (should)+동사원형이 옵니다.', '["go", "went", "goes", "has gone"]', 'He insisted that she ___ there.', 'en_im_fb_119', 119, 11),
(1, CURRENT_TIMESTAMP, '제안 동사(suggest) 뒤 that절에 동사원형이 옵니다.', '["saw", "see", "sees", "seen"]', 'I suggest that he ___ a doctor.', 'en_im_fb_120', 120, 11),

-- 121~140: 비교 구문 (Comparisons)
(2, CURRENT_TIMESTAMP, '비교급 앞에서는 much, even, still, far, a lot이 강조의 의미를 가집니다.', '["very", "many", "much", "so"]', 'This car is ___ faster than that one.', 'en_im_fb_121', 121, 11),
(0, CURRENT_TIMESTAMP, 'as ~ as 동등비교 구문입니다.', '["as", "than", "so", "to"]', 'She is ___ tall as her brother.', 'en_im_fb_122', 122, 11),
(1, CURRENT_TIMESTAMP, 'not as[so] ~ as (~만큼 ~하지 않다) 구문입니다.', '["as", "so", "than", "more"]', 'It is not ___ hot today as it was yesterday.', 'en_im_fb_123', 123, 11),
(3, CURRENT_TIMESTAMP, '배수사(twice) + as ~ as 구문입니다.', '["than", "more", "much", "as"]', 'My room is twice ___ large as yours.', 'en_im_fb_124', 124, 11),
(2, CURRENT_TIMESTAMP, '가능한 한 빨리(as ~ as possible) 구문입니다.', '["can", "you", "possible", "fast"]', 'Please reply as soon as ___.', 'en_im_fb_125', 125, 11),
(0, CURRENT_TIMESTAMP, 'the + 비교급, the + 비교급 (~하면 할수록 점점 더 ~하다) 구문입니다.', '["more", "most", "much", "many"]', 'The ___ you read, the smarter you become.', 'en_im_fb_126', 126, 11),
(1, CURRENT_TIMESTAMP, '비교급 and 비교급 (점점 더 ~한) 구문입니다.', '["cold", "colder", "coldest", "more cold"]', 'It is getting colder and ___.', 'en_im_fb_127', 127, 11),
(3, CURRENT_TIMESTAMP, '라틴어 어원 비교급인 superior는 than 대신 to를 씁니다.', '["than", "as", "for", "to"]', 'This model is superior ___ the older one.', 'en_im_fb_128', 128, 11),
(2, CURRENT_TIMESTAMP, 'prefer A to B (B보다 A를 선호하다) 구문입니다.', '["than", "as", "to", "for"]', 'I prefer tea ___ coffee.', 'en_im_fb_129', 129, 11),
(0, CURRENT_TIMESTAMP, '최상급의 의미를 나타내는 비교급 + than any other 단수명사 구문입니다.', '["boy", "boys", "boy''s", "a boy"]', 'He is taller than any other ___ in his class.', 'en_im_fb_130', 130, 11),
(1, CURRENT_TIMESTAMP, '최상급을 강조하는 by far(단연코)가 적절합니다.', '["much", "by far", "very", "even"]', 'This is ___ the best movie of the year.', 'en_im_fb_131', 131, 11),
(2, CURRENT_TIMESTAMP, '가장 ~한 것들 중 하나(one of the 최상급 복수명사) 구문입니다.', '["city", "a city", "cities", "citys"]', 'New York is one of the biggest ___ in the world.', 'en_im_fb_132', 132, 11),
(0, CURRENT_TIMESTAMP, 'A no less than B (B만큼이나 A하다 / A 못지않게 B하다) 구문입니다.', '["less", "more", "as", "than"]', 'A whale is no ___ a mammal than a horse is.', 'en_im_fb_133', 133, 11),
(3, CURRENT_TIMESTAMP, 'no longer (더 이상 ~않다) 구문입니다.', '["more", "any", "much", "longer"]', 'He is no ___ a child.', 'en_im_fb_134', 134, 11),
(1, CURRENT_TIMESTAMP, 'no more than (단지, 오직 = only) 구문입니다.', '["much", "more", "less", "as"]', 'I have no ___ than 5 dollars.', 'en_im_fb_135', 135, 11),
(2, CURRENT_TIMESTAMP, 'not more than (기껏해야 = at most) 구문입니다.', '["much", "less", "more", "as"]', 'There were not ___ than 10 people.', 'en_im_fb_136', 136, 11),
(0, CURRENT_TIMESTAMP, 'no less than (자그마치, ~만큼이나 많이) 구문입니다.', '["less", "more", "as", "much"]', 'He won no ___ than 1,000 dollars.', 'en_im_fb_137', 137, 11),
(1, CURRENT_TIMESTAMP, '둘 중 하나를 비교할 때는 the 비교급 of the two를 씁니다.', '["tallest", "taller", "tall", "more tall"]', 'He is the ___ of the two boys.', 'en_im_fb_138', 138, 11),
(3, CURRENT_TIMESTAMP, '비교 대상이 명확하도록 소유대명사 yours(너의 차)를 씁니다.', '["you", "your", "yourself", "yours"]', 'My car is faster than ___.', 'en_im_fb_139', 139, 11),
(2, CURRENT_TIMESTAMP, '단수 명사(population)를 대신하는 지시대명사 that을 씁니다.', '["those", "it", "that", "this"]', 'The population of Tokyo is larger than ___ of Seoul.', 'en_im_fb_140', 140, 11),

-- 141~160: 5형식 동사 및 특수 구문
(0, CURRENT_TIMESTAMP, '사역동사 make는 목적격 보어로 동사원형을 취합니다.', '["clean", "to clean", "cleaning", "cleaned"]', 'He made me ___ my room.', 'en_im_fb_141', 141, 11),
(1, CURRENT_TIMESTAMP, '사역동사 let은 목적격 보어로 동사원형을 취합니다.', '["to go", "go", "going", "gone"]', 'My father let me ___ to the concert.', 'en_im_fb_142', 142, 11),
(2, CURRENT_TIMESTAMP, '사역동사 have는 능동일 때 동사원형을 취합니다.', '["to carry", "carrying", "carry", "carried"]', 'I had him ___ my bags.', 'en_im_fb_143', 143, 11),
(3, CURRENT_TIMESTAMP, '준사역동사 help는 동사원형이나 to부정사 둘 다 가능합니다.', '["done", "doing", "does", "do"]', 'She helped me ___ the dishes.', 'en_im_fb_144', 144, 11),
(0, CURRENT_TIMESTAMP, '지각동사 see는 동사원형이나 현재분사를 취합니다.', '["cross", "to cross", "crossed", "crosses"]', 'I saw him ___ the street.', 'en_im_fb_145', 145, 11),
(1, CURRENT_TIMESTAMP, '지각동사 hear는 능동 진행일 때 현재분사를 취할 수 있습니다.', '["sang", "singing", "to sing", "sung"]', 'I heard her ___ a song.', 'en_im_fb_146', 146, 11),
(2, CURRENT_TIMESTAMP, '목적어(my name)와 능동/수동 관계를 따져 과거분사(called)를 씁니다.', '["call", "calling", "called", "to call"]', 'I heard my name ___ from behind.', 'en_im_fb_147', 147, 11),
(0, CURRENT_TIMESTAMP, 'ask는 5형식에서 목적격 보어로 to부정사를 취합니다.', '["to help", "help", "helping", "helped"]', 'I asked him ___ me.', 'en_im_fb_148', 148, 11),
(1, CURRENT_TIMESTAMP, 'tell은 5형식에서 목적격 보어로 to부정사를 취합니다.', '["to not do", "not to do", "doing not", "do not"]', 'I told her ___ it again.', 'en_im_fb_149', 149, 11),
(2, CURRENT_TIMESTAMP, 'allow는 5형식에서 목적격 보어로 to부정사를 취합니다.', '["use", "using", "to use", "used"]', 'They didn''t allow me ___ my phone.', 'en_im_fb_150', 150, 11),
(3, CURRENT_TIMESTAMP, 'expect는 5형식에서 목적격 보어로 to부정사를 취합니다.', '["arrive", "arriving", "arrived", "to arrive"]', 'We expect him ___ soon.', 'en_im_fb_151', 151, 11),
(0, CURRENT_TIMESTAMP, 'want는 5형식에서 목적격 보어로 to부정사를 취합니다.', '["to be", "be", "being", "been"]', 'I want you ___ happy.', 'en_im_fb_152', 152, 11),
(1, CURRENT_TIMESTAMP, 'keep은 5형식에서 목적격 보어로 현재분사(~ing)를 자주 취합니다.', '["wait", "waiting", "to wait", "waited"]', 'I am sorry to keep you ___.', 'en_im_fb_153', 153, 11),
(2, CURRENT_TIMESTAMP, 'find는 5형식에서 목적격 보어로 형용사나 현재분사를 취합니다.', '["easy", "easily", "easier", "easiest"]', 'I found the book very ___.', 'en_im_fb_154', 154, 11),
(0, CURRENT_TIMESTAMP, 'make는 5형식에서 가목적어 it을 자주 사용합니다.', '["it", "that", "this", "them"]', 'I make ___ a rule to get up early.', 'en_im_fb_155', 155, 11),
(1, CURRENT_TIMESTAMP, '가목적어 it을 받는 진목적어 to부정사 구문입니다.', '["understand", "to understand", "understanding", "understood"]', 'I found it difficult ___ the theory.', 'en_im_fb_156', 156, 11),
(2, CURRENT_TIMESTAMP, 'so + 형용사/부사 + that (너무 ~해서 ~하다) 구문입니다.', '["too", "very", "so", "such"]', 'He was ___ tired that he couldn''t walk.', 'en_im_fb_157', 157, 11),
(3, CURRENT_TIMESTAMP, 'such + (a/an) + 형용사 + 명사 + that 구문입니다.', '["so", "too", "very", "such"]', 'It was ___ a beautiful day that we went out.', 'en_im_fb_158', 158, 11),
(0, CURRENT_TIMESTAMP, 'too ~ to 구문은 so ~ that ~ can''t로 바꿀 수 있습니다.', '["can''t", "can", "will", "would"]', 'He is so young that he ___ go to school.', 'en_im_fb_159', 159, 11),
(1, CURRENT_TIMESTAMP, '~할 만큼 충분히 ~한 (형용사/부사 + enough to) 구문입니다.', '["too", "enough", "so", "very"]', 'He is rich ___ to buy the car.', 'en_im_fb_160', 160, 11),

-- 161~180: 접속부사 및 전치사구 (Transitions & Prepositions)
(2, CURRENT_TIMESTAMP, '결과를 나타내는 Therefore(그러므로)가 적절합니다.', '["However", "For example", "Therefore", "Besides"]', 'He studied hard. ___, he passed the test.', 'en_im_fb_161', 161, 11),
(0, CURRENT_TIMESTAMP, '역접을 나타내는 However(그러나)가 적절합니다.', '["However", "Therefore", "So", "Thus"]', 'I love pizza. ___, I am on a diet now.', 'en_im_fb_162', 162, 11),
(1, CURRENT_TIMESTAMP, '예시를 나타내는 For example(예를 들어)이 적절합니다.', '["In addition", "For example", "Therefore", "However"]', 'I like fruits. ___, I eat apples every day.', 'en_im_fb_163', 163, 11),
(3, CURRENT_TIMESTAMP, '첨가/게다가를 나타내는 Besides(게다가)가 적절합니다.', '["However", "Therefore", "For instance", "Besides"]', 'It''s too late to go out. ___, it''s raining.', 'en_im_fb_164', 164, 11),
(0, CURRENT_TIMESTAMP, '요약을 나타내는 In short(요약하자면)가 적절합니다.', '["In short", "However", "Therefore", "Besides"]', 'He is smart, kind, and rich. ___, he is perfect.', 'en_im_fb_165', 165, 11),
(2, CURRENT_TIMESTAMP, '대조를 나타내는 On the other hand(반면에)가 적절합니다.', '["Therefore", "For example", "On the other hand", "In addition"]', 'City life is exciting. ___, it is very stressful.', 'en_im_fb_166', 166, 11),
(1, CURRENT_TIMESTAMP, '대신에를 나타내는 Instead가 적절합니다.', '["However", "Instead", "Therefore", "So"]', 'I didn''t go to the movie. ___, I stayed home.', 'en_im_fb_167', 167, 11),
(3, CURRENT_TIMESTAMP, '결과적으로를 나타내는 As a result가 적절합니다.', '["However", "For example", "In addition", "As a result"]', 'He didn''t study at all. ___, he failed.', 'en_im_fb_168', 168, 11),
(0, CURRENT_TIMESTAMP, '불행하게도를 나타내는 Unfortunately가 적절합니다.', '["Unfortunately", "Therefore", "Besides", "So"]', 'We wanted to go. ___, the tickets were sold out.', 'en_im_fb_169', 169, 11),
(1, CURRENT_TIMESTAMP, '게다가를 나타내는 In addition이 적절합니다.', '["However", "In addition", "Therefore", "Instead"]', 'The hotel was cheap. ___, it was very clean.', 'en_im_fb_170', 170, 11),
(2, CURRENT_TIMESTAMP, '명사구 앞이므로 접속사 Because가 아니라 Because of(~때문에)가 옵니다.', '["Because", "As", "Because of", "Since"]', 'We canceled the game ___ the heavy rain.', 'en_im_fb_171', 171, 11),
(0, CURRENT_TIMESTAMP, '명사구 앞이므로 ~에도 불구하고 뜻인 Despite가 옵니다.', '["Despite", "Although", "Though", "Even though"]', '___ the bad weather, they went hiking.', 'en_im_fb_172', 172, 11),
(1, CURRENT_TIMESTAMP, 'In spite of는 Despite와 같은 뜻의 전치사구입니다.', '["of", "in", "with", "for"]', 'In spite ___ his wealth, he is not happy.', 'en_im_fb_173', 173, 11),
(3, CURRENT_TIMESTAMP, 'During(~동안에)은 특정 기간 명사(the vacation) 앞에 옵니다.', '["While", "For", "In", "During"]', 'I met many friends ___ the vacation.', 'en_im_fb_174', 174, 11),
(0, CURRENT_TIMESTAMP, 'According to(~에 따르면) 전치사 구문입니다.', '["According", "Because", "Due", "Thanks"]', '___ to the weather forecast, it will snow tomorrow.', 'en_im_fb_175', 175, 11),
(2, CURRENT_TIMESTAMP, 'Due to(~때문에) 전치사 구문입니다.', '["Because", "According", "Due", "Despite"]', 'His success is ___ to his hard work.', 'en_im_fb_176', 176, 11),
(1, CURRENT_TIMESTAMP, 'Instead of(~대신에) 전치사 구문입니다.', '["Because", "Instead", "In spite", "Due"]', 'I will have tea ___ of coffee.', 'en_im_fb_177', 177, 11),
(3, CURRENT_TIMESTAMP, 'Thanks to(~덕분에) 전치사 구문입니다.', '["Due", "According", "Because", "Thanks"]', '___ to your help, I finished it on time.', 'en_im_fb_178', 178, 11),
(0, CURRENT_TIMESTAMP, '명사구 앞이므로 ~에 더하여(In addition to)가 옵니다.', '["In addition to", "In addition", "Besides", "Also"]', '___ to English, she speaks French.', 'en_im_fb_179', 179, 11),
(2, CURRENT_TIMESTAMP, 'By means of(~에 의하여, ~를 수단으로) 전치사 구문입니다.', '["way", "method", "means", "tool"]', 'Thoughts are expressed by ___ of language.', 'en_im_fb_180', 180, 11),

-- 181~200: 중요 동사구 및 관용 표현 (Idioms & Phrasal Verbs)
(1, CURRENT_TIMESTAMP, 'look forward to (~를 고대하다) 구문입니다.', '["at", "to", "for", "after"]', 'I am looking forward ___ seeing you.', 'en_im_fb_181', 181, 11),
(0, CURRENT_TIMESTAMP, 'take care of (~를 돌보다 = look after) 구문입니다.', '["take", "make", "have", "get"]', 'She has to ___ care of her baby sister.', 'en_im_fb_182', 182, 11),
(2, CURRENT_TIMESTAMP, 'put off (~를 미루다 = postpone) 구문입니다.', '["on", "out", "off", "up"]', 'Don''t put ___ until tomorrow what you can do today.', 'en_im_fb_183', 183, 11),
(3, CURRENT_TIMESTAMP, 'give up (~를 포기하다) 구문입니다.', '["in", "out", "away", "up"]', 'You should not give ___ your dreams.', 'en_im_fb_184', 184, 11),
(1, CURRENT_TIMESTAMP, 'turn on (전원 등을 켜다) 구문입니다.', '["in", "on", "out", "up"]', 'Please turn ___ the light. It''s dark here.', 'en_im_fb_185', 185, 11),
(0, CURRENT_TIMESTAMP, 'run out of (~가 다 떨어지다, 고갈되다) 구문입니다.', '["out", "away", "into", "over"]', 'We have run ___ of gas.', 'en_im_fb_186', 186, 11),
(2, CURRENT_TIMESTAMP, 'figure out (알아내다, 이해하다) 구문입니다.', '["in", "on", "out", "up"]', 'I can''t figure ___ how to solve this problem.', 'en_im_fb_187', 187, 11),
(1, CURRENT_TIMESTAMP, 'look for (~를 찾다) 구문입니다.', '["at", "for", "after", "into"]', 'What are you looking ___?', 'en_im_fb_188', 188, 11),
(3, CURRENT_TIMESTAMP, 'look up (사전 등에서 찾아보다) 구문입니다.', '["in", "at", "for", "up"]', 'If you don''t know the word, look it ___ in the dictionary.', 'en_im_fb_189', 189, 11),
(0, CURRENT_TIMESTAMP, 'make up one''s mind (결심하다) 구문입니다.', '["up", "out", "in", "off"]', 'Have you made ___ your mind yet?', 'en_im_fb_190', 190, 11),
(2, CURRENT_TIMESTAMP, 'depend on (~에 의존하다, ~에 달려있다) 구문입니다.', '["in", "at", "on", "for"]', 'It depends ___ the weather.', 'en_im_fb_191', 191, 11),
(1, CURRENT_TIMESTAMP, 'rely on (~에 의지하다) 구문입니다.', '["in", "on", "at", "for"]', 'You can rely ___ me.', 'en_im_fb_192', 192, 11),
(3, CURRENT_TIMESTAMP, 'consist of (~로 구성되다) 구문입니다.', '["in", "with", "from", "of"]', 'The team consists ___ 11 players.', 'en_im_fb_193', 193, 11),
(0, CURRENT_TIMESTAMP, 'suffer from (~로 고통받다) 구문입니다.', '["from", "with", "in", "of"]', 'She is suffering ___ a bad cold.', 'en_im_fb_194', 194, 11),
(2, CURRENT_TIMESTAMP, 'prevent A from B (A가 B하는 것을 막다) 구문입니다.', '["to", "of", "from", "in"]', 'The rain prevented us ___ going out.', 'en_im_fb_195', 195, 11),
(1, CURRENT_TIMESTAMP, 'be good at (~를 잘하다) 구문입니다.', '["in", "at", "on", "for"]', 'He is very good ___ playing tennis.', 'en_im_fb_196', 196, 11),
(0, CURRENT_TIMESTAMP, 'be proud of (~를 자랑스러워하다) 구문입니다.', '["of", "in", "for", "with"]', 'They are proud ___ their son.', 'en_im_fb_197', 197, 11),
(3, CURRENT_TIMESTAMP, 'take part in (~에 참여하다 = participate in) 구문입니다.', '["on", "at", "for", "in"]', 'Are you going to take part ___ the contest?', 'en_im_fb_198', 198, 11),
(2, CURRENT_TIMESTAMP, 'catch up with (~를 따라잡다) 구문입니다.', '["to", "for", "with", "on"]', 'Go ahead. I will catch up ___ you later.', 'en_im_fb_199', 199, 11),
(1, CURRENT_TIMESTAMP, 'put up with (~를 참다, 견디다) 구문입니다.', '["in", "with", "for", "on"]', 'I can''t put up ___ this noise anymore.', 'en_im_fb_200', 200, 11);