-- =====================================================
-- English Quiz Seed: STARTER - 100 Questions
-- Basic greetings, numbers, colors, food, family, daily objects
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
-- === Greetings (1~10) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_1', '"안녕하세요" (아침)를 영어로?', '["Good night","Good morning","Good evening","Goodbye"]', 1, '"Good morning"은 아침 인사입니다.', 1),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_2', '"감사합니다"를 영어로?', '["Sorry","Please","Thank you","Excuse me"]', 2, '"Thank you"는 감사합니다입니다.', 2),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_3', '"미안합니다"를 영어로?', '["Thank you","Sorry","Please","Hello"]', 1, '"Sorry"는 미안합니다입니다.', 3),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_4', '"안녕히 가세요"를 영어로?', '["Hello","Good morning","Goodbye","See you"]', 2, '"Goodbye"는 안녕히 가세요입니다.', 4),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_5', '"실례합니다"를 영어로?', '["Sorry","Excuse me","Thank you","Please"]', 1, '"Excuse me"는 실례합니다입니다.', 5),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_6', '"처음 뵙겠습니다"를 영어로?', '["How are you?","Nice to meet you","See you later","Thank you"]', 1, '"Nice to meet you"입니다.', 6),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_7', '"잘 지내세요?"를 영어로?', '["What is this?","How are you?","Where are you?","Who are you?"]', 1, '"How are you?"입니다.', 7),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_8', '"네/예"를 영어로?', '["No","Yes","Maybe","Please"]', 1, '"Yes"는 네/예입니다.', 8),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_9', '"아니요"를 영어로?', '["No","Yes","Not","None"]', 0, '"No"는 아니요입니다.', 9),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_10', '"부탁합니다"를 영어로?', '["Sorry","Thank you","Please","Excuse me"]', 2, '"Please"는 부탁합니다/제발입니다.', 10),

-- === Numbers (11~20) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_11', '숫자 "1"을 영어로?', '["One","Two","Three","Four"]', 0, '"One"은 1입니다.', 11),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_12', '숫자 "5"를 영어로?', '["Three","Four","Five","Six"]', 2, '"Five"는 5입니다.', 12),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_13', '숫자 "10"을 영어로?', '["Eight","Nine","Ten","Eleven"]', 2, '"Ten"은 10입니다.', 13),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_14', '숫자 "100"을 영어로?', '["Ten","Hundred","Thousand","Million"]', 1, '"Hundred"는 100입니다.', 14),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_15', '숫자 "7"을 영어로?', '["Six","Seven","Eight","Nine"]', 1, '"Seven"은 7입니다.', 15),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_16', '숫자 "12"를 영어로?', '["Eleven","Twelve","Thirteen","Fourteen"]', 1, '"Twelve"는 12입니다.', 16),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_17', '숫자 "20"을 영어로?', '["Twelve","Fifteen","Twenty","Thirty"]', 2, '"Twenty"는 20입니다.', 17),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_18', '숫자 "0"을 영어로?', '["One","Zero","None","Null"]', 1, '"Zero"는 0입니다.', 18),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_19', '숫자 "1000"을 영어로?', '["Hundred","Thousand","Million","Billion"]', 1, '"Thousand"는 1000입니다.', 19),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_20', '"첫 번째"를 영어로?', '["One","Once","First","Firstly"]', 2, '"First"는 첫 번째입니다.', 20),

-- === Colors (21~30) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_21', '"빨간색"을 영어로?', '["Blue","Red","Green","Yellow"]', 1, '"Red"는 빨간색입니다.', 21),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_22', '"파란색"을 영어로?', '["Blue","Red","Green","Yellow"]', 0, '"Blue"는 파란색입니다.', 22),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_23', '"초록색"을 영어로?', '["Blue","Red","Green","Yellow"]', 2, '"Green"은 초록색입니다.', 23),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_24', '"노란색"을 영어로?', '["Blue","Red","Green","Yellow"]', 3, '"Yellow"는 노란색입니다.', 24),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_25', '"흰색"을 영어로?', '["Black","White","Gray","Brown"]', 1, '"White"는 흰색입니다.', 25),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_26', '"검은색"을 영어로?', '["Black","White","Gray","Brown"]', 0, '"Black"은 검은색입니다.', 26),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_27', '"주황색"을 영어로?', '["Purple","Orange","Pink","Gray"]', 1, '"Orange"는 주황색입니다.', 27),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_28', '"보라색"을 영어로?', '["Purple","Orange","Pink","Gray"]', 0, '"Purple"은 보라색입니다.', 28),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_29', '"분홍색"을 영어로?', '["Purple","Orange","Pink","Gray"]', 2, '"Pink"는 분홍색입니다.', 29),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_30', '"갈색"을 영어로?', '["Black","White","Gray","Brown"]', 3, '"Brown"은 갈색입니다.', 30),

-- === Animals (31~40) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_31', '"고양이"를 영어로?', '["Dog","Cat","Bird","Fish"]', 1, '"Cat"은 고양이입니다.', 31),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_32', '"강아지"를 영어로?', '["Dog","Cat","Bird","Fish"]', 0, '"Dog"은 개/강아지입니다.', 32),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_33', '"새"를 영어로?', '["Dog","Cat","Bird","Fish"]', 2, '"Bird"는 새입니다.', 33),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_34', '"물고기"를 영어로?', '["Dog","Cat","Bird","Fish"]', 3, '"Fish"는 물고기입니다.', 34),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_35', '"말"을 영어로?', '["Cow","Horse","Pig","Sheep"]', 1, '"Horse"는 말입니다.', 35),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_36', '"소"를 영어로?', '["Cow","Horse","Pig","Sheep"]', 0, '"Cow"는 소입니다.', 36),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_37', '"돼지"를 영어로?', '["Cow","Horse","Pig","Sheep"]', 2, '"Pig"는 돼지입니다.', 37),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_38', '"토끼"를 영어로?', '["Mouse","Rabbit","Monkey","Bear"]', 1, '"Rabbit"은 토끼입니다.', 38),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_39', '"원숭이"를 영어로?', '["Mouse","Rabbit","Monkey","Bear"]', 2, '"Monkey"는 원숭이입니다.', 39),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_40', '"곰"을 영어로?', '["Mouse","Rabbit","Monkey","Bear"]', 3, '"Bear"는 곰입니다.', 40),

-- === Food & Drink (41~55) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_41', '"물"을 영어로?', '["Water","Milk","Juice","Coffee"]', 0, '"Water"는 물입니다.', 41),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_42', '"우유"를 영어로?', '["Water","Milk","Juice","Coffee"]', 1, '"Milk"는 우유입니다.', 42),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_43', '"커피"를 영어로?', '["Water","Milk","Juice","Coffee"]', 3, '"Coffee"는 커피입니다.', 43),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_44', '"빵"을 영어로?', '["Rice","Bread","Meat","Egg"]', 1, '"Bread"는 빵입니다.', 44),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_45', '"밥/쌀"을 영어로?', '["Rice","Bread","Meat","Egg"]', 0, '"Rice"는 밥/쌀입니다.', 45),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_46', '"고기"를 영어로?', '["Rice","Bread","Meat","Egg"]', 2, '"Meat"는 고기입니다.', 46),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_47', '"달걀"을 영어로?', '["Rice","Bread","Meat","Egg"]', 3, '"Egg"는 달걀입니다.', 47),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_48', '"사과"를 영어로?', '["Apple","Banana","Orange","Grape"]', 0, '"Apple"은 사과입니다.', 48),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_49', '"바나나"를 영어로?', '["Apple","Banana","Orange","Grape"]', 1, '"Banana"는 바나나입니다.', 49),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_50', '"딸기"를 영어로?', '["Cherry","Peach","Strawberry","Watermelon"]', 2, '"Strawberry"는 딸기입니다.', 50),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_51', '"치킨/닭고기"를 영어로?', '["Beef","Pork","Chicken","Lamb"]', 2, '"Chicken"은 닭고기입니다.', 51),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_52', '"소고기"를 영어로?', '["Beef","Pork","Chicken","Lamb"]', 0, '"Beef"는 소고기입니다.', 52),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_53', '"돼지고기"를 영어로?', '["Beef","Pork","Chicken","Lamb"]', 1, '"Pork"는 돼지고기입니다.', 53),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_54', '"야채"를 영어로?', '["Fruit","Vegetable","Meat","Snack"]', 1, '"Vegetable"은 야채입니다.', 54),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_55', '"과일"을 영어로?', '["Fruit","Vegetable","Meat","Snack"]', 0, '"Fruit"는 과일입니다.', 55),

-- === Family (56~65) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_56', '"어머니"를 영어로?', '["Father","Mother","Brother","Sister"]', 1, '"Mother"는 어머니입니다.', 56),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_57', '"아버지"를 영어로?', '["Father","Mother","Brother","Sister"]', 0, '"Father"는 아버지입니다.', 57),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_58', '"형제"를 영어로?', '["Father","Mother","Brother","Sister"]', 2, '"Brother"는 형제입니다.', 58),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_59', '"자매"를 영어로?', '["Father","Mother","Brother","Sister"]', 3, '"Sister"는 자매입니다.', 59),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_60', '"가족"을 영어로?', '["Family","Friend","Teacher","Student"]', 0, '"Family"는 가족입니다.', 60),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_61', '"친구"를 영어로?', '["Family","Friend","Teacher","Student"]', 1, '"Friend"는 친구입니다.', 61),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_62', '"선생님"을 영어로?', '["Family","Friend","Teacher","Student"]', 2, '"Teacher"는 선생님입니다.', 62),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_63', '"학생"을 영어로?', '["Family","Friend","Teacher","Student"]', 3, '"Student"는 학생입니다.', 63),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_64', '"아들"을 영어로?', '["Son","Daughter","Uncle","Aunt"]', 0, '"Son"은 아들입니다.', 64),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_65', '"딸"을 영어로?', '["Son","Daughter","Uncle","Aunt"]', 1, '"Daughter"는 딸입니다.', 65),

-- === Places (66~75) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_66', '"학교"를 영어로?', '["School","Hospital","Bank","Park"]', 0, '"School"은 학교입니다.', 66),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_67', '"병원"을 영어로?', '["School","Hospital","Bank","Park"]', 1, '"Hospital"은 병원입니다.', 67),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_68', '"은행"을 영어로?', '["School","Hospital","Bank","Park"]', 2, '"Bank"는 은행입니다.', 68),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_69', '"공원"을 영어로?', '["School","Hospital","Bank","Park"]', 3, '"Park"는 공원입니다.', 69),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_70', '"공항"을 영어로?', '["Station","Airport","Hotel","Store"]', 1, '"Airport"는 공항입니다.', 70),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_71', '"역"을 영어로?', '["Station","Airport","Hotel","Store"]', 0, '"Station"은 역입니다.', 71),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_72', '"가게"를 영어로?', '["Station","Airport","Hotel","Store"]', 3, '"Store"는 가게입니다.', 72),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_73', '"식당"을 영어로?', '["Library","Restaurant","Museum","Church"]', 1, '"Restaurant"는 식당입니다.', 73),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_74', '"도서관"을 영어로?', '["Library","Restaurant","Museum","Church"]', 0, '"Library"는 도서관입니다.', 74),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_75', '"우체국"을 영어로?', '["Police station","Fire station","Post office","City hall"]', 2, '"Post office"는 우체국입니다.', 75),

-- === Objects & Nature (76~90) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_76', '"책"을 영어로?', '["Book","Pen","Desk","Chair"]', 0, '"Book"은 책입니다.', 76),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_77', '"펜"을 영어로?', '["Book","Pen","Desk","Chair"]', 1, '"Pen"은 펜입니다.', 77),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_78', '"책상"을 영어로?', '["Book","Pen","Desk","Chair"]', 2, '"Desk"는 책상입니다.', 78),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_79', '"의자"를 영어로?', '["Book","Pen","Desk","Chair"]', 3, '"Chair"는 의자입니다.', 79),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_80', '"시계"를 영어로?', '["Clock","Watch","둘 다 맞음","Phone"]', 2, '"Clock"(벽시계)과 "Watch"(손목시계) 둘 다 시계입니다.', 80),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_81', '"가방"을 영어로?', '["Bag","Box","Cup","Hat"]', 0, '"Bag"은 가방입니다.', 81),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_82', '"우산"을 영어로?', '["Umbrella","Hat","Coat","Shoes"]', 0, '"Umbrella"는 우산입니다.', 82),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_83', '"신발"을 영어로?', '["Umbrella","Hat","Coat","Shoes"]', 3, '"Shoes"는 신발입니다.', 83),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_84', '"하늘"을 영어로?', '["Sky","Sea","Mountain","River"]', 0, '"Sky"는 하늘입니다.', 84),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_85', '"바다"를 영어로?', '["Sky","Sea","Mountain","River"]', 1, '"Sea"는 바다입니다.', 85),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_86', '"산"을 영어로?', '["Sky","Sea","Mountain","River"]', 2, '"Mountain"은 산입니다.', 86),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_87', '"강"을 영어로?', '["Sky","Sea","Mountain","River"]', 3, '"River"는 강입니다.', 87),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_88', '"꽃"을 영어로?', '["Flower","Tree","Grass","Leaf"]', 0, '"Flower"는 꽃입니다.', 88),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_89', '"나무"를 영어로?', '["Flower","Tree","Grass","Leaf"]', 1, '"Tree"는 나무입니다.', 89),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_90', '"비"를 영어로?', '["Rain","Snow","Wind","Sun"]', 0, '"Rain"은 비입니다.', 90),

-- === Adjectives & Time (91~100) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_91', '"크다"를 영어로?', '["Big","Small","Long","Short"]', 0, '"Big"은 크다입니다.', 91),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_92', '"작다"를 영어로?', '["Big","Small","Long","Short"]', 1, '"Small"은 작다입니다.', 92),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_93', '"뜨겁다/더운"을 영어로?', '["Hot","Cold","Warm","Cool"]', 0, '"Hot"은 뜨겁다/더운입니다.', 93),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_94', '"차가운/추운"을 영어로?', '["Hot","Cold","Warm","Cool"]', 1, '"Cold"는 차가운/추운입니다.', 94),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_95', '"오늘"을 영어로?', '["Yesterday","Today","Tomorrow","Now"]', 1, '"Today"는 오늘입니다.', 95),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_96', '"내일"을 영어로?', '["Yesterday","Today","Tomorrow","Now"]', 2, '"Tomorrow"는 내일입니다.', 96),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_97', '"어제"를 영어로?', '["Yesterday","Today","Tomorrow","Now"]', 0, '"Yesterday"는 어제입니다.', 97),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_98', '"좋은"을 영어로?', '["Good","Bad","New","Old"]', 0, '"Good"은 좋은입니다.', 98),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_99', '"나쁜"을 영어로?', '["Good","Bad","New","Old"]', 1, '"Bad"는 나쁜입니다.', 99),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='english'), 'en_w_100', '"행복한"을 영어로?', '["Happy","Sad","Angry","Tired"]', 0, '"Happy"는 행복한입니다.', 100)
ON CONFLICT (question_id) DO NOTHING;


INSERT INTO quiz_questions (correct_option_index, created_at, explanation, options, question, question_id, sort_order, set_id) VALUES
-- 1~10: 과일 및 채소
(0, CURRENT_TIMESTAMP, '"Apple"은 사과입니다.', '["Apple", "Banana", "Orange", "Grape"]', '"사과"를 영어로?', 'en_st_1', 1, 9),
(1, CURRENT_TIMESTAMP, '"Banana"는 바나나입니다.', '["Apple", "Banana", "Orange", "Grape"]', '"바나나"를 영어로?', 'en_st_2', 2, 9),
(2, CURRENT_TIMESTAMP, '"Orange"는 오렌지입니다.', '["Apple", "Banana", "Orange", "Grape"]', '"오렌지"를 영어로?', 'en_st_3', 3, 9),
(3, CURRENT_TIMESTAMP, '"Grape"는 포도입니다.', '["Apple", "Banana", "Orange", "Grape"]', '"포도"를 영어로?', 'en_st_4', 4, 9),
(0, CURRENT_TIMESTAMP, '"Watermelon"은 수박입니다.', '["Watermelon", "Strawberry", "Lemon", "Peach"]', '"수박"을 영어로?', 'en_st_5', 5, 9),
(1, CURRENT_TIMESTAMP, '"Strawberry"는 딸기입니다.', '["Watermelon", "Strawberry", "Lemon", "Peach"]', '"딸기"를 영어로?', 'en_st_6', 6, 9),
(2, CURRENT_TIMESTAMP, '"Lemon"은 레몬입니다.', '["Watermelon", "Strawberry", "Lemon", "Peach"]', '"레몬"을 영어로?', 'en_st_7', 7, 9),
(3, CURRENT_TIMESTAMP, '"Peach"는 복숭아입니다.', '["Watermelon", "Strawberry", "Lemon", "Peach"]', '"복숭아"를 영어로?', 'en_st_8', 8, 9),
(0, CURRENT_TIMESTAMP, '"Pear"는 배입니다.', '["Pear", "Pineapple", "Tomato", "Potato"]', '"배"를 영어로?', 'en_st_9', 9, 9),
(1, CURRENT_TIMESTAMP, '"Pineapple"은 파인애플입니다.', '["Pear", "Pineapple", "Tomato", "Potato"]', '"파인애플"을 영어로?', 'en_st_10', 10, 9),

-- 11~30: 동물
(2, CURRENT_TIMESTAMP, '"Dog"는 개입니다.', '["Cat", "Bird", "Dog", "Fish"]', '"개"를 영어로?', 'en_st_11', 11, 9),
(3, CURRENT_TIMESTAMP, '"Cat"은 고양이입니다.', '["Cat", "Bird", "Dog", "Cat"]', '"고양이"를 영어로?', 'en_st_12', 12, 9),
(0, CURRENT_TIMESTAMP, '"Bird"는 새입니다.', '["Bird", "Fish", "Pig", "Cow"]', '"새"를 영어로?', 'en_st_13', 13, 9),
(1, CURRENT_TIMESTAMP, '"Fish"는 물고기입니다.', '["Bird", "Fish", "Pig", "Cow"]', '"물고기"를 영어로?', 'en_st_14', 14, 9),
(2, CURRENT_TIMESTAMP, '"Pig"는 돼지입니다.', '["Bird", "Fish", "Pig", "Cow"]', '"돼지"를 영어로?', 'en_st_15', 15, 9),
(3, CURRENT_TIMESTAMP, '"Cow"는 소입니다.', '["Bird", "Fish", "Pig", "Cow"]', '"소"를 영어로?', 'en_st_16', 16, 9),
(0, CURRENT_TIMESTAMP, '"Horse"는 말입니다.', '["Horse", "Sheep", "Chicken", "Duck"]', '"말"을 영어로?', 'en_st_17', 17, 9),
(1, CURRENT_TIMESTAMP, '"Sheep"은 양입니다.', '["Horse", "Sheep", "Chicken", "Duck"]', '"양"을 영어로?', 'en_st_18', 18, 9),
(2, CURRENT_TIMESTAMP, '"Chicken"은 닭입니다.', '["Horse", "Sheep", "Chicken", "Duck"]', '"닭"을 영어로?', 'en_st_19', 19, 9),
(3, CURRENT_TIMESTAMP, '"Duck"은 오리입니다.', '["Horse", "Sheep", "Chicken", "Duck"]', '"오리"를 영어로?', 'en_st_20', 20, 9),
(0, CURRENT_TIMESTAMP, '"Lion"은 사자입니다.', '["Lion", "Tiger", "Bear", "Monkey"]', '"사자"를 영어로?', 'en_st_21', 21, 9),
(1, CURRENT_TIMESTAMP, '"Tiger"는 호랑이입니다.', '["Lion", "Tiger", "Bear", "Monkey"]', '"호랑이"를 영어로?', 'en_st_22', 22, 9),
(2, CURRENT_TIMESTAMP, '"Bear"는 곰입니다.', '["Lion", "Tiger", "Bear", "Monkey"]', '"곰"을 영어로?', 'en_st_23', 23, 9),
(3, CURRENT_TIMESTAMP, '"Monkey"는 원숭이입니다.', '["Lion", "Tiger", "Bear", "Monkey"]', '"원숭이"를 영어로?', 'en_st_24', 24, 9),
(0, CURRENT_TIMESTAMP, '"Elephant"는 코끼리입니다.', '["Elephant", "Mouse", "Snake", "Frog"]', '"코끼리"를 영어로?', 'en_st_25', 25, 9),
(1, CURRENT_TIMESTAMP, '"Mouse"는 쥐입니다.', '["Elephant", "Mouse", "Snake", "Frog"]', '"쥐"를 영어로?', 'en_st_26', 26, 9),
(2, CURRENT_TIMESTAMP, '"Snake"는 뱀입니다.', '["Elephant", "Mouse", "Snake", "Frog"]', '"뱀"을 영어로?', 'en_st_27', 27, 9),
(3, CURRENT_TIMESTAMP, '"Frog"는 개구리입니다.', '["Elephant", "Mouse", "Snake", "Frog"]', '"개구리"를 영어로?', 'en_st_28', 28, 9),
(0, CURRENT_TIMESTAMP, '"Rabbit"은 토끼입니다.', '["Rabbit", "Fox", "Wolf", "Deer"]', '"토끼"를 영어로?', 'en_st_29', 29, 9),
(1, CURRENT_TIMESTAMP, '"Fox"는 여우입니다.', '["Rabbit", "Fox", "Wolf", "Deer"]', '"여우"를 영어로?', 'en_st_30', 30, 9),

-- 31~40: 색깔
(2, CURRENT_TIMESTAMP, '"Red"는 빨간색입니다.', '["Blue", "Green", "Red", "Yellow"]', '"빨간색"을 영어로?', 'en_st_31', 31, 9),
(3, CURRENT_TIMESTAMP, '"Blue"는 파란색입니다.', '["Blue", "Green", "Red", "Blue"]', '"파란색"을 영어로?', 'en_st_32', 32, 9),
(0, CURRENT_TIMESTAMP, '"Green"은 초록색입니다.', '["Green", "Yellow", "Black", "White"]', '"초록색"을 영어로?', 'en_st_33', 33, 9),
(1, CURRENT_TIMESTAMP, '"Yellow"는 노란색입니다.', '["Green", "Yellow", "Black", "White"]', '"노란색"을 영어로?', 'en_st_34', 34, 9),
(2, CURRENT_TIMESTAMP, '"Black"은 검은색입니다.', '["Green", "Yellow", "Black", "White"]', '"검은색"을 영어로?', 'en_st_35', 35, 9),
(3, CURRENT_TIMESTAMP, '"White"는 하얀색입니다.', '["Green", "Yellow", "Black", "White"]', '"하얀색"을 영어로?', 'en_st_36', 36, 9),
(0, CURRENT_TIMESTAMP, '"Pink"는 분홍색입니다.', '["Pink", "Purple", "Brown", "Gray"]', '"분홍색"을 영어로?', 'en_st_37', 37, 9),
(1, CURRENT_TIMESTAMP, '"Purple"은 보라색입니다.', '["Pink", "Purple", "Brown", "Gray"]', '"보라색"을 영어로?', 'en_st_38', 38, 9),
(2, CURRENT_TIMESTAMP, '"Brown"은 갈색입니다.', '["Pink", "Purple", "Brown", "Gray"]', '"갈색"을 영어로?', 'en_st_39', 39, 9),
(3, CURRENT_TIMESTAMP, '"Gray"는 회색입니다.', '["Pink", "Purple", "Brown", "Gray"]', '"회색"을 영어로?', 'en_st_40', 40, 9),

-- 41~50: 숫자
(0, CURRENT_TIMESTAMP, '"One"은 숫자 1입니다.', '["One", "Two", "Three", "Four"]', '"하나(1)"를 영어로?', 'en_st_41', 41, 9),
(1, CURRENT_TIMESTAMP, '"Two"는 숫자 2입니다.', '["One", "Two", "Three", "Four"]', '"둘(2)"을 영어로?', 'en_st_42', 42, 9),
(2, CURRENT_TIMESTAMP, '"Three"는 숫자 3입니다.', '["One", "Two", "Three", "Four"]', '"셋(3)"을 영어로?', 'en_st_43', 43, 9),
(3, CURRENT_TIMESTAMP, '"Four"는 숫자 4입니다.', '["One", "Two", "Three", "Four"]', '"넷(4)"을 영어로?', 'en_st_44', 44, 9),
(0, CURRENT_TIMESTAMP, '"Five"는 숫자 5입니다.', '["Five", "Six", "Seven", "Eight"]', '"다섯(5)"을 영어로?', 'en_st_45', 45, 9),
(1, CURRENT_TIMESTAMP, '"Six"는 숫자 6입니다.', '["Five", "Six", "Seven", "Eight"]', '"여섯(6)"을 영어로?', 'en_st_46', 46, 9),
(2, CURRENT_TIMESTAMP, '"Seven"은 숫자 7입니다.', '["Five", "Six", "Seven", "Eight"]', '"일곱(7)"을 영어로?', 'en_st_47', 47, 9),
(3, CURRENT_TIMESTAMP, '"Eight"은 숫자 8입니다.', '["Five", "Six", "Seven", "Eight"]', '"여덟(8)"을 영어로?', 'en_st_48', 48, 9),
(0, CURRENT_TIMESTAMP, '"Nine"은 숫자 9입니다.', '["Nine", "Ten", "Eleven", "Twelve"]', '"아홉(9)"을 영어로?', 'en_st_49', 49, 9),
(1, CURRENT_TIMESTAMP, '"Ten"은 숫자 10입니다.', '["Nine", "Ten", "Eleven", "Twelve"]', '"열(10)"을 영어로?', 'en_st_50', 50, 9),

-- 51~70: 신체
(2, CURRENT_TIMESTAMP, '"Head"는 머리입니다.', '["Eye", "Nose", "Head", "Mouth"]', '"머리"를 영어로?', 'en_st_51', 51, 9),
(3, CURRENT_TIMESTAMP, '"Eye"는 눈입니다.', '["Ear", "Arm", "Leg", "Eye"]', '"눈"을 영어로?', 'en_st_52', 52, 9),
(0, CURRENT_TIMESTAMP, '"Nose"는 코입니다.', '["Nose", "Mouth", "Ear", "Arm"]', '"코"를 영어로?', 'en_st_53', 53, 9),
(1, CURRENT_TIMESTAMP, '"Mouth"는 입입니다.', '["Nose", "Mouth", "Ear", "Arm"]', '"입"을 영어로?', 'en_st_54', 54, 9),
(2, CURRENT_TIMESTAMP, '"Ear"는 귀입니다.', '["Nose", "Mouth", "Ear", "Arm"]', '"귀"를 영어로?', 'en_st_55', 55, 9),
(3, CURRENT_TIMESTAMP, '"Arm"은 팔입니다.', '["Nose", "Mouth", "Ear", "Arm"]', '"팔"을 영어로?', 'en_st_56', 56, 9),
(0, CURRENT_TIMESTAMP, '"Leg"는 다리입니다.', '["Leg", "Hand", "Foot", "Hair"]', '"다리"를 영어로?', 'en_st_57', 57, 9),
(1, CURRENT_TIMESTAMP, '"Hand"는 손입니다.', '["Leg", "Hand", "Foot", "Hair"]', '"손"을 영어로?', 'en_st_58', 58, 9),
(2, CURRENT_TIMESTAMP, '"Foot"은 발입니다.', '["Leg", "Hand", "Foot", "Hair"]', '"발"을 영어로?', 'en_st_59', 59, 9),
(3, CURRENT_TIMESTAMP, '"Hair"는 머리카락입니다.', '["Leg", "Hand", "Foot", "Hair"]', '"머리카락"을 영어로?', 'en_st_60', 60, 9),
(0, CURRENT_TIMESTAMP, '"Face"는 얼굴입니다.', '["Face", "Neck", "Shoulder", "Back"]', '"얼굴"을 영어로?', 'en_st_61', 61, 9),
(1, CURRENT_TIMESTAMP, '"Neck"은 목입니다.', '["Face", "Neck", "Shoulder", "Back"]', '"목"을 영어로?', 'en_st_62', 62, 9),
(2, CURRENT_TIMESTAMP, '"Shoulder"는 어깨입니다.', '["Face", "Neck", "Shoulder", "Back"]', '"어깨"를 영어로?', 'en_st_63', 63, 9),
(3, CURRENT_TIMESTAMP, '"Back"은 등입니다.', '["Face", "Neck", "Shoulder", "Back"]', '"등"을 영어로?', 'en_st_64', 64, 9),
(0, CURRENT_TIMESTAMP, '"Stomach"는 배, 위입니다.', '["Stomach", "Heart", "Finger", "Toe"]', '"배(신체)"를 영어로?', 'en_st_65', 65, 9),
(1, CURRENT_TIMESTAMP, '"Finger"는 손가락입니다.', '["Stomach", "Finger", "Toe", "Knee"]', '"손가락"을 영어로?', 'en_st_66', 66, 9),
(2, CURRENT_TIMESTAMP, '"Toe"는 발가락입니다.', '["Stomach", "Finger", "Toe", "Knee"]', '"발가락"을 영어로?', 'en_st_67', 67, 9),
(3, CURRENT_TIMESTAMP, '"Knee"는 무릎입니다.', '["Stomach", "Finger", "Toe", "Knee"]', '"무릎"을 영어로?', 'en_st_68', 68, 9),
(0, CURRENT_TIMESTAMP, '"Heart"는 심장, 마음입니다.', '["Heart", "Brain", "Bone", "Skin"]', '"심장"을 영어로?', 'en_st_69', 69, 9),
(1, CURRENT_TIMESTAMP, '"Skin"은 피부입니다.', '["Heart", "Skin", "Brain", "Bone"]', '"피부"를 영어로?', 'en_st_70', 70, 9),

-- 71~90: 가족 및 사람
(2, CURRENT_TIMESTAMP, '"Mother"는 엄마입니다.', '["Father", "Brother", "Mother", "Sister"]', '"엄마"를 영어로?', 'en_st_71', 71, 9),
(3, CURRENT_TIMESTAMP, '"Father"는 아빠입니다.', '["Brother", "Sister", "Baby", "Father"]', '"아빠"를 영어로?', 'en_st_72', 72, 9),
(0, CURRENT_TIMESTAMP, '"Brother"는 남자 형제입니다.', '["Brother", "Sister", "Baby", "Family"]', '"남자 형제"를 영어로?', 'en_st_73', 73, 9),
(1, CURRENT_TIMESTAMP, '"Sister"는 여자 형제입니다.', '["Brother", "Sister", "Baby", "Family"]', '"여자 형제"를 영어로?', 'en_st_74', 74, 9),
(2, CURRENT_TIMESTAMP, '"Baby"는 아기입니다.', '["Brother", "Sister", "Baby", "Family"]', '"아기"를 영어로?', 'en_st_75', 75, 9),
(3, CURRENT_TIMESTAMP, '"Family"는 가족입니다.', '["Brother", "Sister", "Baby", "Family"]', '"가족"을 영어로?', 'en_st_76', 76, 9),
(0, CURRENT_TIMESTAMP, '"Grandmother"는 할머니입니다.', '["Grandmother", "Grandfather", "Uncle", "Aunt"]', '"할머니"를 영어로?', 'en_st_77', 77, 9),
(1, CURRENT_TIMESTAMP, '"Grandfather"는 할아버지입니다.', '["Grandmother", "Grandfather", "Uncle", "Aunt"]', '"할아버지"를 영어로?', 'en_st_78', 78, 9),
(2, CURRENT_TIMESTAMP, '"Uncle"은 삼촌입니다.', '["Grandmother", "Grandfather", "Uncle", "Aunt"]', '"삼촌(아저씨)"을 영어로?', 'en_st_79', 79, 9),
(3, CURRENT_TIMESTAMP, '"Aunt"는 이모, 고모입니다.', '["Grandmother", "Grandfather", "Uncle", "Aunt"]', '"이모(아줌마)"를 영어로?', 'en_st_80', 80, 9),
(0, CURRENT_TIMESTAMP, '"Friend"는 친구입니다.', '["Friend", "Teacher", "Student", "Boy"]', '"친구"를 영어로?', 'en_st_81', 81, 9),
(1, CURRENT_TIMESTAMP, '"Teacher"는 선생님입니다.', '["Friend", "Teacher", "Student", "Boy"]', '"선생님"을 영어로?', 'en_st_82', 82, 9),
(2, CURRENT_TIMESTAMP, '"Student"는 학생입니다.', '["Friend", "Teacher", "Student", "Boy"]', '"학생"을 영어로?', 'en_st_83', 83, 9),
(3, CURRENT_TIMESTAMP, '"Boy"는 소년입니다.', '["Friend", "Teacher", "Student", "Boy"]', '"소년"을 영어로?', 'en_st_84', 84, 9),
(0, CURRENT_TIMESTAMP, '"Girl"은 소녀입니다.', '["Girl", "Man", "Woman", "Person"]', '"소녀"를 영어로?', 'en_st_85', 85, 9),
(1, CURRENT_TIMESTAMP, '"Man"은 남자(어른)입니다.', '["Girl", "Man", "Woman", "Person"]', '"남자(성인)"를 영어로?', 'en_st_86', 86, 9),
(2, CURRENT_TIMESTAMP, '"Woman"은 여자(어른)입니다.', '["Girl", "Man", "Woman", "Person"]', '"여자(성인)"를 영어로?', 'en_st_87', 87, 9),
(3, CURRENT_TIMESTAMP, '"Person"은 사람입니다.', '["Girl", "Man", "Woman", "Person"]', '"사람"을 영어로?', 'en_st_88', 88, 9),
(0, CURRENT_TIMESTAMP, '"Doctor"는 의사입니다.', '["Doctor", "Police", "Singer", "Actor"]', '"의사"를 영어로?', 'en_st_89', 89, 9),
(1, CURRENT_TIMESTAMP, '"Police"는 경찰입니다.', '["Doctor", "Police", "Singer", "Actor"]', '"경찰"을 영어로?', 'en_st_90', 90, 9),

-- 91~110: 사물 및 장소
(2, CURRENT_TIMESTAMP, '"House"는 집입니다.', '["School", "Room", "House", "Door"]', '"집"을 영어로?', 'en_st_91', 91, 9),
(3, CURRENT_TIMESTAMP, '"School"은 학교입니다.', '["Room", "Door", "Window", "School"]', '"학교"를 영어로?', 'en_st_92', 92, 9),
(0, CURRENT_TIMESTAMP, '"Room"은 방입니다.', '["Room", "Door", "Window", "Bed"]', '"방"을 영어로?', 'en_st_93', 93, 9),
(1, CURRENT_TIMESTAMP, '"Door"는 문입니다.', '["Room", "Door", "Window", "Bed"]', '"문"을 영어로?', 'en_st_94', 94, 9),
(2, CURRENT_TIMESTAMP, '"Window"는 창문입니다.', '["Room", "Door", "Window", "Bed"]', '"창문"을 영어로?', 'en_st_95', 95, 9),
(3, CURRENT_TIMESTAMP, '"Bed"는 침대입니다.', '["Room", "Door", "Window", "Bed"]', '"침대"를 영어로?', 'en_st_96', 96, 9),
(0, CURRENT_TIMESTAMP, '"Chair"는 의자입니다.', '["Chair", "Desk", "Book", "Bag"]', '"의자"를 영어로?', 'en_st_97', 97, 9),
(1, CURRENT_TIMESTAMP, '"Desk"는 책상입니다.', '["Chair", "Desk", "Book", "Bag"]', '"책상"을 영어로?', 'en_st_98', 98, 9),
(2, CURRENT_TIMESTAMP, '"Book"은 책입니다.', '["Chair", "Desk", "Book", "Bag"]', '"책"을 영어로?', 'en_st_99', 99, 9),
(3, CURRENT_TIMESTAMP, '"Bag"은 가방입니다.', '["Chair", "Desk", "Book", "Bag"]', '"가방"을 영어로?', 'en_st_100', 100, 9),
(0, CURRENT_TIMESTAMP, '"Pencil"은 연필입니다.', '["Pencil", "Eraser", "Clock", "Computer"]', '"연필"을 영어로?', 'en_st_101', 101, 9),
(1, CURRENT_TIMESTAMP, '"Eraser"는 지우개입니다.', '["Pencil", "Eraser", "Clock", "Computer"]', '"지우개"를 영어로?', 'en_st_102', 102, 9),
(2, CURRENT_TIMESTAMP, '"Clock"은 시계입니다.', '["Pencil", "Eraser", "Clock", "Computer"]', '"벽시계"를 영어로?', 'en_st_103', 103, 9),
(3, CURRENT_TIMESTAMP, '"Computer"는 컴퓨터입니다.', '["Pencil", "Eraser", "Clock", "Computer"]', '"컴퓨터"를 영어로?', 'en_st_104', 104, 9),
(0, CURRENT_TIMESTAMP, '"Phone"은 전화기입니다.', '["Phone", "Car", "Bus", "Train"]', '"전화기"를 영어로?', 'en_st_105', 105, 9),
(1, CURRENT_TIMESTAMP, '"Car"는 자동차입니다.', '["Phone", "Car", "Bus", "Train"]', '"자동차"를 영어로?', 'en_st_106', 106, 9),
(2, CURRENT_TIMESTAMP, '"Bus"는 버스입니다.', '["Phone", "Car", "Bus", "Train"]', '"버스"를 영어로?', 'en_st_107', 107, 9),
(3, CURRENT_TIMESTAMP, '"Train"은 기차입니다.', '["Phone", "Car", "Bus", "Train"]', '"기차"를 영어로?', 'en_st_108', 108, 9),
(0, CURRENT_TIMESTAMP, '"Bike"는 자전거입니다.', '["Bike", "Plane", "Boat", "Taxi"]', '"자전거"를 영어로?', 'en_st_109', 109, 9),
(1, CURRENT_TIMESTAMP, '"Plane"은 비행기입니다.', '["Bike", "Plane", "Boat", "Taxi"]', '"비행기"를 영어로?', 'en_st_110', 110, 9),

-- 111~130: 기초 형용사
(2, CURRENT_TIMESTAMP, '"Happy"는 행복한, 기쁜입니다.', '["Sad", "Angry", "Happy", "Tired"]', '"기쁜, 행복한"을 영어로?', 'en_st_111', 111, 9),
(3, CURRENT_TIMESTAMP, '"Sad"는 슬픈입니다.', '["Angry", "Tired", "Hungry", "Sad"]', '"슬픈"을 영어로?', 'en_st_112', 112, 9),
(0, CURRENT_TIMESTAMP, '"Angry"는 화난입니다.', '["Angry", "Tired", "Hungry", "Thirsty"]', '"화난"을 영어로?', 'en_st_113', 113, 9),
(1, CURRENT_TIMESTAMP, '"Tired"는 피곤한입니다.', '["Angry", "Tired", "Hungry", "Thirsty"]', '"피곤한"을 영어로?', 'en_st_114', 114, 9),
(2, CURRENT_TIMESTAMP, '"Hungry"는 배고픈입니다.', '["Angry", "Tired", "Hungry", "Thirsty"]', '"배고픈"을 영어로?', 'en_st_115', 115, 9),
(3, CURRENT_TIMESTAMP, '"Thirsty"는 목마른입니다.', '["Angry", "Tired", "Hungry", "Thirsty"]', '"목마른"을 영어로?', 'en_st_116', 116, 9),
(0, CURRENT_TIMESTAMP, '"Hot"은 뜨거운, 더운입니다.', '["Hot", "Cold", "Big", "Small"]', '"더운, 뜨거운"을 영어로?', 'en_st_117', 117, 9),
(1, CURRENT_TIMESTAMP, '"Cold"는 추운, 차가운입니다.', '["Hot", "Cold", "Big", "Small"]', '"추운, 차가운"을 영어로?', 'en_st_118', 118, 9),
(2, CURRENT_TIMESTAMP, '"Big"은 큰입니다.', '["Hot", "Cold", "Big", "Small"]', '"큰"을 영어로?', 'en_st_119', 119, 9),
(3, CURRENT_TIMESTAMP, '"Small"은 작은입니다.', '["Hot", "Cold", "Big", "Small"]', '"작은"을 영어로?', 'en_st_120', 120, 9),
(0, CURRENT_TIMESTAMP, '"Good"은 좋은입니다.', '["Good", "Bad", "Fast", "Slow"]', '"좋은"을 영어로?', 'en_st_121', 121, 9),
(1, CURRENT_TIMESTAMP, '"Bad"는 나쁜입니다.', '["Good", "Bad", "Fast", "Slow"]', '"나쁜"을 영어로?', 'en_st_122', 122, 9),
(2, CURRENT_TIMESTAMP, '"Fast"는 빠른입니다.', '["Good", "Bad", "Fast", "Slow"]', '"빠른"을 영어로?', 'en_st_123', 123, 9),
(3, CURRENT_TIMESTAMP, '"Slow"는 느린입니다.', '["Good", "Bad", "Fast", "Slow"]', '"느린"을 영어로?', 'en_st_124', 124, 9),
(0, CURRENT_TIMESTAMP, '"Long"은 긴입니다.', '["Long", "Short", "High", "Low"]', '"긴"을 영어로?', 'en_st_125', 125, 9),
(1, CURRENT_TIMESTAMP, '"Short"는 짧은입니다.', '["Long", "Short", "High", "Low"]', '"짧은"을 영어로?', 'en_st_126', 126, 9),
(2, CURRENT_TIMESTAMP, '"High"는 높은입니다.', '["Long", "Short", "High", "Low"]', '"높은"을 영어로?', 'en_st_127', 127, 9),
(3, CURRENT_TIMESTAMP, '"Low"는 낮은입니다.', '["Long", "Short", "High", "Low"]', '"낮은"을 영어로?', 'en_st_128', 128, 9),
(0, CURRENT_TIMESTAMP, '"New"는 새로운입니다.', '["New", "Old", "Young", "Clean"]', '"새로운"을 영어로?', 'en_st_129', 129, 9),
(1, CURRENT_TIMESTAMP, '"Old"는 낡은, 늙은입니다.', '["New", "Old", "Young", "Clean"]', '"오래된, 늙은"을 영어로?', 'en_st_130', 130, 9),

-- 131~165: 기초 동사
(2, CURRENT_TIMESTAMP, '"Run"은 달리다입니다.', '["Walk", "Jump", "Run", "Swim"]', '"달리다"를 영어로?', 'en_st_131', 131, 9),
(3, CURRENT_TIMESTAMP, '"Walk"는 걷다입니다.', '["Jump", "Swim", "Fly", "Walk"]', '"걷다"를 영어로?', 'en_st_132', 132, 9),
(0, CURRENT_TIMESTAMP, '"Jump"는 뛰다입니다.', '["Jump", "Swim", "Fly", "Eat"]', '"뛰다, 점프하다"를 영어로?', 'en_st_133', 133, 9),
(1, CURRENT_TIMESTAMP, '"Swim"은 수영하다입니다.', '["Jump", "Swim", "Fly", "Eat"]', '"수영하다"를 영어로?', 'en_st_134', 134, 9),
(2, CURRENT_TIMESTAMP, '"Fly"는 날다입니다.', '["Jump", "Swim", "Fly", "Eat"]', '"날다"를 영어로?', 'en_st_135', 135, 9),
(3, CURRENT_TIMESTAMP, '"Eat"은 먹다입니다.', '["Jump", "Swim", "Fly", "Eat"]', '"먹다"를 영어로?', 'en_st_136', 136, 9),
(0, CURRENT_TIMESTAMP, '"Drink"는 마시다입니다.', '["Drink", "Sleep", "Wake", "Wash"]', '"마시다"를 영어로?', 'en_st_137', 137, 9),
(1, CURRENT_TIMESTAMP, '"Sleep"은 자다입니다.', '["Drink", "Sleep", "Wake", "Wash"]', '"자다"를 영어로?', 'en_st_138', 138, 9),
(2, CURRENT_TIMESTAMP, '"Wake"는 깨다, 일어나다입니다.', '["Drink", "Sleep", "Wake", "Wash"]', '"잠에서 깨다"를 영어로?', 'en_st_139', 139, 9),
(3, CURRENT_TIMESTAMP, '"Wash"는 씻다입니다.', '["Drink", "Sleep", "Wake", "Wash"]', '"씻다"를 영어로?', 'en_st_140', 140, 9),
(0, CURRENT_TIMESTAMP, '"Read"는 읽다입니다.', '["Read", "Write", "Listen", "Speak"]', '"읽다"를 영어로?', 'en_st_141', 141, 9),
(1, CURRENT_TIMESTAMP, '"Write"는 쓰다입니다.', '["Read", "Write", "Listen", "Speak"]', '"글을 쓰다"를 영어로?', 'en_st_142', 142, 9),
(2, CURRENT_TIMESTAMP, '"Listen"은 듣다입니다.', '["Read", "Write", "Listen", "Speak"]', '"듣다"를 영어로?', 'en_st_143', 143, 9),
(3, CURRENT_TIMESTAMP, '"Speak"는 말하다입니다.', '["Read", "Write", "Listen", "Speak"]', '"말하다"를 영어로?', 'en_st_144', 144, 9),
(0, CURRENT_TIMESTAMP, '"See"는 보다입니다.', '["See", "Play", "Study", "Work"]', '"보다"를 영어로?', 'en_st_145', 145, 9),
(1, CURRENT_TIMESTAMP, '"Play"는 놀다입니다.', '["See", "Play", "Study", "Work"]', '"놀다, 경기하다"를 영어로?', 'en_st_146', 146, 9),
(2, CURRENT_TIMESTAMP, '"Study"는 공부하다입니다.', '["See", "Play", "Study", "Work"]', '"공부하다"를 영어로?', 'en_st_147', 147, 9),
(3, CURRENT_TIMESTAMP, '"Work"는 일하다입니다.', '["See", "Play", "Study", "Work"]', '"일하다"를 영어로?', 'en_st_148', 148, 9),
(0, CURRENT_TIMESTAMP, '"Rest"는 쉬다입니다.', '["Rest", "Stop", "Go", "Come"]', '"쉬다, 휴식하다"를 영어로?', 'en_st_149', 149, 9),
(1, CURRENT_TIMESTAMP, '"Stop"은 멈추다입니다.', '["Rest", "Stop", "Go", "Come"]', '"멈추다"를 영어로?', 'en_st_150', 150, 9),
(2, CURRENT_TIMESTAMP, '"Go"는 가다입니다.', '["Rest", "Stop", "Go", "Come"]', '"가다"를 영어로?', 'en_st_151', 151, 9),
(3, CURRENT_TIMESTAMP, '"Come"은 오다입니다.', '["Rest", "Stop", "Go", "Come"]', '"오다"를 영어로?', 'en_st_152', 152, 9),
(0, CURRENT_TIMESTAMP, '"Bring"은 가져오다입니다.', '["Bring", "Take", "Make", "Give"]', '"가져오다"를 영어로?', 'en_st_153', 153, 9),
(1, CURRENT_TIMESTAMP, '"Take"는 가져가다, 취하다입니다.', '["Bring", "Take", "Make", "Give"]', '"가져가다"를 영어로?', 'en_st_154', 154, 9),
(2, CURRENT_TIMESTAMP, '"Make"는 만들다입니다.', '["Bring", "Take", "Make", "Give"]', '"만들다"를 영어로?', 'en_st_155', 155, 9),
(3, CURRENT_TIMESTAMP, '"Give"는 주다입니다.', '["Bring", "Take", "Make", "Give"]', '"주다"를 영어로?', 'en_st_156', 156, 9),
(0, CURRENT_TIMESTAMP, '"Get"은 얻다, 받다입니다.', '["Get", "Buy", "Sell", "Open"]', '"얻다, 구하다"를 영어로?', 'en_st_157', 157, 9),
(1, CURRENT_TIMESTAMP, '"Buy"는 사다입니다.', '["Get", "Buy", "Sell", "Open"]', '"물건을 사다"를 영어로?', 'en_st_158', 158, 9),
(2, CURRENT_TIMESTAMP, '"Sell"은 팔다입니다.', '["Get", "Buy", "Sell", "Open"]', '"팔다"를 영어로?', 'en_st_159', 159, 9),
(3, CURRENT_TIMESTAMP, '"Open"은 열다입니다.', '["Get", "Buy", "Sell", "Open"]', '"열다"를 영어로?', 'en_st_160', 160, 9),
(0, CURRENT_TIMESTAMP, '"Close"는 닫다입니다.', '["Close", "Push", "Pull", "Love"]', '"닫다"를 영어로?', 'en_st_161', 161, 9),
(1, CURRENT_TIMESTAMP, '"Push"는 밀다입니다.', '["Close", "Push", "Pull", "Love"]', '"밀다"를 영어로?', 'en_st_162', 162, 9),
(2, CURRENT_TIMESTAMP, '"Pull"은 당기다입니다.', '["Close", "Push", "Pull", "Love"]', '"당기다"를 영어로?', 'en_st_163', 163, 9),
(3, CURRENT_TIMESTAMP, '"Love"는 사랑하다입니다.', '["Close", "Push", "Pull", "Love"]', '"사랑하다"를 영어로?', 'en_st_164', 164, 9),
(0, CURRENT_TIMESTAMP, '"Like"는 좋아하다입니다.', '["Like", "Hate", "Want", "Need"]', '"좋아하다"를 영어로?', 'en_st_165', 165, 9),

-- 166~180: 요일 및 시간, 계절
(1, CURRENT_TIMESTAMP, '"Monday"는 월요일입니다.', '["Sunday", "Monday", "Tuesday", "Friday"]', '"월요일"을 영어로?', 'en_st_166', 166, 9),
(2, CURRENT_TIMESTAMP, '"Tuesday"는 화요일입니다.', '["Monday", "Wednesday", "Tuesday", "Thursday"]', '"화요일"을 영어로?', 'en_st_167', 167, 9),
(3, CURRENT_TIMESTAMP, '"Wednesday"는 수요일입니다.', '["Tuesday", "Thursday", "Friday", "Wednesday"]', '"수요일"을 영어로?', 'en_st_168', 168, 9),
(0, CURRENT_TIMESTAMP, '"Thursday"는 목요일입니다.', '["Thursday", "Friday", "Saturday", "Sunday"]', '"목요일"을 영어로?', 'en_st_169', 169, 9),
(1, CURRENT_TIMESTAMP, '"Friday"는 금요일입니다.', '["Thursday", "Friday", "Saturday", "Sunday"]', '"금요일"을 영어로?', 'en_st_170', 170, 9),
(2, CURRENT_TIMESTAMP, '"Saturday"는 토요일입니다.', '["Thursday", "Friday", "Saturday", "Sunday"]', '"토요일"을 영어로?', 'en_st_171', 171, 9),
(3, CURRENT_TIMESTAMP, '"Sunday"는 일요일입니다.', '["Thursday", "Friday", "Saturday", "Sunday"]', '"일요일"을 영어로?', 'en_st_172', 172, 9),
(0, CURRENT_TIMESTAMP, '"Today"는 오늘입니다.', '["Today", "Tomorrow", "Yesterday", "Week"]', '"오늘"을 영어로?', 'en_st_173', 173, 9),
(1, CURRENT_TIMESTAMP, '"Tomorrow"는 내일입니다.', '["Today", "Tomorrow", "Yesterday", "Week"]', '"내일"을 영어로?', 'en_st_174', 174, 9),
(2, CURRENT_TIMESTAMP, '"Yesterday"는 어제입니다.', '["Today", "Tomorrow", "Yesterday", "Week"]', '"어제"를 영어로?', 'en_st_175', 175, 9),
(3, CURRENT_TIMESTAMP, '"Spring"은 봄입니다.', '["Summer", "Autumn", "Winter", "Spring"]', '"봄"을 영어로?', 'en_st_176', 176, 9),
(0, CURRENT_TIMESTAMP, '"Summer"는 여름입니다.', '["Summer", "Autumn", "Winter", "Season"]', '"여름"을 영어로?', 'en_st_177', 177, 9),
(1, CURRENT_TIMESTAMP, '"Autumn(Fall)"은 가을입니다.', '["Summer", "Autumn", "Winter", "Season"]', '"가을"을 영어로?', 'en_st_178', 178, 9),
(2, CURRENT_TIMESTAMP, '"Winter"는 겨울입니다.', '["Summer", "Autumn", "Winter", "Season"]', '"겨울"을 영어로?', 'en_st_179', 179, 9),
(3, CURRENT_TIMESTAMP, '"Weather"는 날씨입니다.', '["Summer", "Autumn", "Winter", "Weather"]', '"날씨"를 영어로?', 'en_st_180', 180, 9),

-- 181~200: 자연 및 기타 사물
(0, CURRENT_TIMESTAMP, '"Rain"은 비입니다.', '["Rain", "Snow", "Wind", "Cloud"]', '"비"를 영어로?', 'en_st_181', 181, 9),
(1, CURRENT_TIMESTAMP, '"Snow"는 눈입니다.', '["Rain", "Snow", "Wind", "Cloud"]', '"눈(날씨)"을 영어로?', 'en_st_182', 182, 9),
(2, CURRENT_TIMESTAMP, '"Wind"는 바람입니다.', '["Rain", "Snow", "Wind", "Cloud"]', '"바람"을 영어로?', 'en_st_183', 183, 9),
(3, CURRENT_TIMESTAMP, '"Cloud"는 구름입니다.', '["Rain", "Snow", "Wind", "Cloud"]', '"구름"을 영어로?', 'en_st_184', 184, 9),
(0, CURRENT_TIMESTAMP, '"Sun"은 태양입니다.', '["Sun", "Moon", "Star", "Sky"]', '"해(태양)"를 영어로?', 'en_st_185', 185, 9),
(1, CURRENT_TIMESTAMP, '"Moon"은 달입니다.', '["Sun", "Moon", "Star", "Sky"]', '"달"을 영어로?', 'en_st_186', 186, 9),
(2, CURRENT_TIMESTAMP, '"Star"는 별입니다.', '["Sun", "Moon", "Star", "Sky"]', '"별"을 영어로?', 'en_st_187', 187, 9),
(3, CURRENT_TIMESTAMP, '"Sky"는 하늘입니다.', '["Sun", "Moon", "Star", "Sky"]', '"하늘"을 영어로?', 'en_st_188', 188, 9),
(0, CURRENT_TIMESTAMP, '"Sea"는 바다입니다.', '["Sea", "River", "Mountain", "Tree"]', '"바다"를 영어로?', 'en_st_189', 189, 9),
(1, CURRENT_TIMESTAMP, '"River"는 강입니다.', '["Sea", "River", "Mountain", "Tree"]', '"강"을 영어로?', 'en_st_190', 190, 9),
(2, CURRENT_TIMESTAMP, '"Meat"는 고기입니다.', '["Bread", "Rice", "Meat", "Egg"]', '"고기"를 영어로?', 'en_st_191', 191, 9),
(3, CURRENT_TIMESTAMP, '"Egg"는 계란입니다.', '["Bread", "Rice", "Meat", "Egg"]', '"계란"을 영어로?', 'en_st_192', 192, 9),
(0, CURRENT_TIMESTAMP, '"Cheese"는 치즈입니다.', '["Cheese", "Water", "Milk", "Juice"]', '"치즈"를 영어로?', 'en_st_193', 193, 9),
(1, CURRENT_TIMESTAMP, '"Water"는 물입니다.', '["Cheese", "Water", "Milk", "Juice"]', '"물"을 영어로?', 'en_st_194', 194, 9),
(2, CURRENT_TIMESTAMP, '"Milk"는 우유입니다.', '["Cheese", "Water", "Milk", "Juice"]', '"우유"를 영어로?', 'en_st_195', 195, 9),
(3, CURRENT_TIMESTAMP, '"Juice"는 주스입니다.', '["Cheese", "Water", "Milk", "Juice"]', '"주스"를 영어로?', 'en_st_196', 196, 9),
(0, CURRENT_TIMESTAMP, '"Tea"는 차(음료)입니다.', '["Tea", "Coffee", "Cake", "Cookie"]', '"차(마시는 차)"를 영어로?', 'en_st_197', 197, 9),
(1, CURRENT_TIMESTAMP, '"Coffee"는 커피입니다.', '["Tea", "Coffee", "Cake", "Cookie"]', '"커피"를 영어로?', 'en_st_198', 198, 9),
(2, CURRENT_TIMESTAMP, '"Cake"는 케이크입니다.', '["Tea", "Coffee", "Cake", "Cookie"]', '"케이크"를 영어로?', 'en_st_199', 199, 9),
(3, CURRENT_TIMESTAMP, '"Cookie"는 쿠키입니다.', '["Tea", "Coffee", "Cake", "Cookie"]', '"쿠키"를 영어로?', 'en_st_200', 200, 9);