-- =====================================================
-- 과학 상식 퀴즈: STARTER (왕초보) - 100문항
-- 일상 속 과학, 기초 자연현상, 인체, 동물, 우주
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
-- === 일상 속 과학 (1~20) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_1', '물이 끓는 온도(1기압 기준)는?', '["90°C","95°C","100°C","110°C"]', 2, '1기압에서 물의 끓는점은 100°C입니다.', 1),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_2', '물이 어는 온도는?', '["0°C","-10°C","10°C","5°C"]', 0, '물의 어는점은 0°C입니다.', 2),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_3', '무지개는 몇 가지 색으로 이루어져 있나요?', '["5가지","6가지","7가지","8가지"]', 2, '무지개는 빨주노초파남보 7가지 색입니다.', 3),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_4', '하루는 몇 시간인가요?', '["12시간","20시간","24시간","30시간"]', 2, '지구가 한 바퀴 자전하는 데 약 24시간이 걸립니다.', 4),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_5', '얼음이 물에 뜨는 이유는?', '["얼음이 더 무거워서","얼음이 더 가벼워서","물이 더 차가워서","얼음이 투명해서"]', 1, '얼음은 물보다 밀도가 낮아서(가벼워서) 뜹니다.', 5),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_6', '소리가 전달되는 데 필요한 것은?', '["빛","매질(공기 등)","전기","자석"]', 1, '소리는 공기, 물 같은 매질을 통해 전달됩니다.', 6),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_7', '비누로 손을 씻으면 세균이 줄어드는 이유는?', '["비누가 뜨거워서","비누가 세균을 녹여서","비누가 기름과 세균을 함께 씻어내서","비누 냄새 때문에"]', 2, '비누의 계면활성제가 기름과 세균을 물에 녹여 씻어냅니다.', 7),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_8', '식물이 초록색인 이유는?', '["초록색 물감 때문","엽록소가 초록색 빛을 반사해서","흙이 초록색이라서","물이 초록색이라서"]', 1, '엽록소는 초록색 빛을 반사하고 나머지를 흡수합니다.', 8),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_9', '밤에 하늘이 어두운 이유는?', '["태양이 없어져서","지구가 태양 반대편을 향해서","달이 빛을 가려서","구름 때문에"]', 1, '지구의 자전으로 밤에는 태양 반대편을 향합니다.', 9),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_10', '냉장고가 음식을 오래 보관할 수 있는 이유는?', '["어두워서","차가워서 세균 번식이 느려져서","건조해서","소리를 내서"]', 1, '낮은 온도에서 세균 번식 속도가 느려집니다.', 10),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_11', '하늘이 파란 이유는?', '["물의 반사","공기 중 산소가 파란색이라서","태양 빛이 공기에 산란되어서","구름이 파란색이라서"]', 2, '태양의 백색광 중 파란색 빛이 공기 분자에 더 많이 산란됩니다(레일리 산란).', 11),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_12', '사계절이 생기는 이유는?', '["지구와 태양의 거리 변화","지구 자전축이 기울어져 있어서","달의 인력 때문에","태양의 크기가 변해서"]', 1, '지구 자전축이 약 23.5도 기울어져 있어 계절이 바뀝니다.', 12),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_13', '쇠못이 녹스는 현상은 무엇 때문인가요?', '["햇빛","산소와 수분","소리","바람"]', 1, '철이 산소 및 수분과 반응해 산화철(녹)이 생깁니다.', 13),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_14', '풍선을 불면 커지는 이유는?', '["풍선이 녹아서","공기 압력이 풍선을 밀어서","풍선 색이 변해서","풍선이 무거워져서"]', 1, '불어넣은 공기가 풍선 안쪽을 밀어 크기가 커집니다.', 14),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_15', '뜨거운 물에서 김이 나는 현상을 무엇이라 하나요?', '["증발","응결","어는 현상","융해"]', 0, '액체 물이 기체(수증기)로 변하는 현상을 증발이라 합니다.', 15),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_16', '나침반의 바늘은 어느 방향을 가리키나요?', '["동쪽","서쪽","남쪽","북쪽"]', 3, '나침반 바늘의 N극은 지구의 북쪽을 가리킵니다.', 16),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_17', '전기가 통하는 물질을 무엇이라 하나요?', '["부도체","도체","반도체","절연체"]', 1, '전기가 잘 통하는 물질을 도체라 합니다(예: 구리, 철).', 17),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_18', '소금물은 순수한 물보다 어는점이?', '["높다","같다","낮다","관계없다"]', 2, '소금물은 순수한 물보다 어는점이 낮습니다.', 18),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_19', '자전거 타이어에 공기를 넣으면 딱딱해지는 이유는?', '["고무가 굳어서","공기 압력이 높아져서","열 때문에","빛 때문에"]', 1, '공기를 넣으면 타이어 안의 기압이 높아져 딱딱해집니다.', 19),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_20', '소리는 무엇에서 가장 빠르게 전달되나요?', '["공기","물","진공","고체(철)"]', 3, '소리는 고체(철 등)에서 가장 빠르게 전달됩니다.', 20),

-- === 인체 (21~40) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_21', '사람의 뼈는 약 몇 개인가요?', '["100개","150개","206개","300개"]', 2, '성인의 뼈는 약 206개입니다.', 21),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_22', '혈액이 온몸을 돌게 하는 기관은?', '["폐","간","심장","위"]', 2, '심장이 혈액을 펌프질하여 온몸에 보냅니다.', 22),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_23', '호흡할 때 들이마시는 기체는?', '["이산화탄소","산소","질소","수소"]', 1, '호흡 시 산소를 들이마시고 이산화탄소를 내쉽니다.', 23),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_24', '음식물을 소화시키는 주요 기관은?', '["폐","심장","위","신장"]', 2, '위는 위산과 효소로 음식물을 소화시킵니다.', 24),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_25', '피부 색소를 결정하는 물질은?', '["헤모글로빈","멜라닌","케라틴","콜라겐"]', 1, '멜라닌 색소가 피부색을 결정합니다.', 25),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_26', '인체에서 가장 큰 장기는?', '["심장","폐","간","뇌"]', 2, '간은 인체에서 가장 큰 내부 장기입니다.', 26),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_27', '인체의 약 몇 %가 물로 이루어져 있나요?', '["30%","50%","70%","90%"]', 2, '인체의 약 60~70%가 물로 구성되어 있습니다.', 27),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_28', '눈의 색깔 부분을 무엇이라 하나요?', '["동공","홍채","각막","수정체"]', 1, '홍채가 눈의 색깔을 결정합니다.', 28),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_29', '침(타액)의 역할은?', '["뼈를 강화","음식물의 초기 소화","혈액 생성","호흡 보조"]', 1, '침 속의 아밀라아제 효소가 탄수화물을 분해합니다.', 29),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_30', '체온을 조절하는 역할을 하는 것은?', '["심장","뇌의 시상하부","위","간"]', 1, '뇌의 시상하부가 체온 조절 중추입니다.', 30),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_31', '적혈구의 주요 역할은?', '["면역","산소 운반","소화","호르몬 분비"]', 1, '적혈구의 헤모글로빈이 산소를 운반합니다.', 31),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_32', '뇌가 하는 일이 아닌 것은?', '["생각하기","움직임 조절","소화액 분비","기억 저장"]', 2, '소화액 분비는 위, 췌장 등이 담당합니다.', 32),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_33', '손톱은 무엇으로 만들어져 있나요?', '["뼈","케라틴","칼슘","콜라겐"]', 1, '손톱은 케라틴이라는 단백질로 이루어져 있습니다.', 33),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_34', '혀에서 맛을 느끼는 기관은?', '["미뢰(맛봉오리)","치아","잇몸","편도선"]', 0, '미뢰(맛봉오리)가 맛을 감지합니다.', 34),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_35', '근육이 수축할 때 사용되는 에너지원은?', '["비타민","ATP","칼슘","철분"]', 1, 'ATP(아데노신 삼인산)가 근육 수축의 에너지원입니다.', 35),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_36', '감기에 걸리는 원인은?', '["추운 날씨","바이러스","세균 없음","운동 부족"]', 1, '감기는 주로 바이러스(리노바이러스 등)에 의해 발생합니다.', 36),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_37', '이가 빠져도 다시 나는 이를 무엇이라 하나요?', '["사랑니","유치","영구치","가짜 이"]', 1, '유치(젖니)가 빠지면 영구치가 올라옵니다.', 37),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_38', '귀의 가장 안쪽에서 균형을 담당하는 곳은?', '["고막","이소골","달팽이관","반고리관"]', 3, '반고리관이 몸의 균형 감각을 담당합니다.', 38),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_39', '혈액형의 종류가 아닌 것은?', '["A형","B형","C형","O형"]', 2, 'ABO 혈액형은 A, B, AB, O형입니다.', 39),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_40', '땀을 흘리는 이유는?', '["체온을 낮추기 위해","배고파서","졸려서","기분이 좋아서"]', 0, '땀이 증발하면서 체온을 낮춥니다.', 40),

-- === 동물/식물 (41~60) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_41', '식물이 광합성을 할 때 만드는 것은?', '["이산화탄소","산소와 포도당","질소","수소"]', 1, '광합성으로 이산화탄소와 물을 이용해 산소와 포도당을 만듭니다.', 41),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_42', '곤충의 다리는 몇 개인가요?', '["4개","6개","8개","10개"]', 1, '곤충은 다리가 6개입니다.', 42),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_43', '거미는 곤충인가요?', '["네","아니요","때에 따라","같은 종류"]', 1, '거미는 곤충이 아니라 거미류(8개 다리)입니다.', 43),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_44', '고래는 어떤 동물인가요?', '["어류","양서류","파충류","포유류"]', 3, '고래는 폐로 호흡하고 새끼에게 젖을 먹이는 포유류입니다.', 44),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_45', '박쥐는 어떤 동물인가요?', '["조류","포유류","파충류","곤충"]', 1, '박쥐는 날 수 있는 유일한 포유류입니다.', 45),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_46', '나무의 나이테는 무엇을 알려주나요?', '["높이","나이","무게","색깔"]', 1, '나이테 수를 세면 나무의 나이를 알 수 있습니다.', 46),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_47', '꿀벌이 꿀을 만드는 재료는?', '["물","꽃의 꿀(화밀)","나뭇잎","흙"]', 1, '꿀벌은 꽃에서 화밀을 수집해 꿀을 만듭니다.', 47),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_48', '공룡이 멸종한 시기는 약?', '["100만 년 전","6,600만 년 전","1억 년 전","10억 년 전"]', 1, '약 6,600만 년 전 대멸종으로 공룡이 사라졌습니다.', 48),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_49', '식물의 뿌리가 하는 일은?', '["광합성","물과 양분 흡수","꽃 피우기","씨앗 만들기"]', 1, '뿌리는 토양에서 물과 무기 양분을 흡수합니다.', 49),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_50', '변온동물이 아닌 것은?', '["뱀","개구리","도마뱀","강아지"]', 3, '강아지(포유류)는 정온동물이고, 나머지는 변온동물입니다.', 50),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_51', '펭귄은 날 수 있나요?', '["네","아니요"]', 1, '펭귄은 날개가 있지만 날지 못하고 수영에 특화되어 있습니다.', 51),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_52', '올챙이가 자라면 무엇이 되나요?', '["물고기","개구리","뱀","거북이"]', 1, '올챙이(유생)는 변태를 거쳐 개구리가 됩니다.', 52),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_53', '나비의 일생 순서로 맞는 것은?', '["알→애벌레→번데기→나비","알→번데기→애벌레→나비","나비→알→번데기→애벌레","애벌레→알→나비→번데기"]', 0, '완전변태: 알→애벌레→번데기→성충(나비)입니다.', 53),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_54', '사막에서 물 없이 오래 버틸 수 있는 동물은?', '["코끼리","낙타","사자","기린"]', 1, '낙타는 혹에 지방을 저장하여 오래 버틸 수 있습니다.', 54),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_55', '잎이 초록색인 색소는?', '["카로틴","엽록소(클로로필)","안토시아닌","멜라닌"]', 1, '엽록소(클로로필)가 초록색입니다.', 55),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_56', '지렁이는 어떤 역할을 하나요?', '["해충","토양을 비옥하게 함","나무를 심음","물을 정화"]', 1, '지렁이는 토양을 뒤집고 유기물을 분해하여 비옥하게 합니다.', 56),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_57', '씨앗이 자라는 데 필요한 3가지는?', '["빛, 공기, 음악","물, 공기, 적절한 온도","흙, 소금, 비료","돌, 물, 종이"]', 1, '씨앗 발아에는 물, 공기(산소), 적절한 온도가 필요합니다.', 57),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_58', '상어는 뼈가 있나요?', '["단단한 뼈가 있다","연골로 되어 있다","뼈가 전혀 없다","나무로 되어 있다"]', 1, '상어는 연골어류로, 뼈 대신 연골로 이루어져 있습니다.', 58),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_59', '가장 빠른 육상 동물은?', '["사자","치타","말","표범"]', 1, '치타는 최대 시속 약 120km로 달릴 수 있습니다.', 59),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_60', '식물의 꽃가루를 옮겨주는 곤충은?', '["모기","꿀벌","바퀴벌레","개미"]', 1, '꿀벌은 대표적인 꽃가루 매개 곤충입니다.', 60),

-- === 지구/우주 (61~80) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_61', '지구에서 가장 가까운 별은?', '["달","화성","태양","북극성"]', 2, '태양은 지구에서 가장 가까운 항성(별)입니다.', 61),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_62', '태양계 행성 중 가장 큰 행성은?', '["토성","목성","천왕성","해왕성"]', 1, '목성은 태양계에서 가장 큰 행성입니다.', 62),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_63', '달에는 공기가 있나요?', '["많다","조금 있다","거의 없다","지구와 같다"]', 2, '달에는 대기가 거의 없습니다.', 63),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_64', '지구가 태양 주위를 한 바퀴 도는 데 걸리는 시간은?', '["1일","1개월","1년","10년"]', 2, '지구의 공전 주기는 약 365.25일(1년)입니다.', 64),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_65', '태양계에서 지구는 몇 번째 행성인가요?', '["1번째","2번째","3번째","4번째"]', 2, '태양에서 셋째 행성이 지구입니다.', 65),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_66', '화산이 폭발할 때 나오는 뜨거운 액체는?', '["물","용암","기름","수은"]', 1, '지하의 마그마가 지표로 분출되면 용암이라 합니다.', 66),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_67', '지진이 자주 일어나는 지역을 무엇이라 하나요?', '["사막 지대","극지방","불의 고리(환태평양 조산대)","열대 우림"]', 2, '태평양 주변의 환태평양 조산대를 불의 고리라고 합니다.', 67),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_68', '바다가 짠 이유는?', '["소금을 넣어서","암석에서 녹아든 광물(나트륨 등) 때문","물고기 때문에","태양 때문에"]', 1, '강물이 암석의 광물을 녹여 바다로 운반하고 축적됩니다.', 68),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_69', '구름은 무엇으로 이루어져 있나요?', '["솜","연기","작은 물방울과 얼음 결정","먼지"]', 2, '구름은 미세한 물방울이나 얼음 결정의 모음입니다.', 69),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_70', '별이 반짝이는 이유는?', '["별이 깜빡여서","대기 때문에 빛이 흔들려서","달이 가려서","구름 때문에"]', 1, '별빛이 대기를 통과하며 굴절되어 반짝여 보입니다.', 70),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_71', '태양은 주로 무엇으로 이루어져 있나요?', '["철","산소","수소","질소"]', 2, '태양의 약 74%는 수소, 약 24%는 헬륨입니다.', 71),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_72', '달이 스스로 빛을 내나요?', '["네","아니요, 태양 빛을 반사"]', 1, '달은 스스로 빛을 내지 않고 태양 빛을 반사합니다.', 72),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_73', '공기의 대부분을 차지하는 기체는?', '["산소","이산화탄소","질소","수소"]', 2, '공기의 약 78%는 질소, 약 21%는 산소입니다.', 73),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_74', '지구의 표면 중 바다가 차지하는 비율은 약?', '["30%","50%","70%","90%"]', 2, '지구 표면의 약 71%가 바다입니다.', 74),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_75', '조석(밀물/썰물)이 생기는 주된 원인은?', '["바람","달의 인력","태양열","지구 자전"]', 1, '달의 인력(중력)이 조석의 주된 원인입니다.', 75),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_76', '은하수는 무엇인가요?', '["강 이름","우리 은하의 모습","구름","오로라"]', 1, '은하수는 우리 은하를 옆에서 본 모습입니다.', 76),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_77', '화성의 별명은?', '["파란 행성","붉은 행성","고리 행성","거대 행성"]', 1, '화성은 표면의 산화철 때문에 붉은 행성이라 불립니다.', 77),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_78', '토성의 특징은?', '["가장 뜨겁다","고리가 있다","가장 작다","물이 있다"]', 1, '토성은 아름다운 고리로 유명합니다.', 78),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_79', '혜성의 꼬리는 무엇으로 이루어져 있나요?', '["불","가스와 먼지","물","돌"]', 1, '태양열에 의해 혜성의 가스와 먼지가 꼬리를 만듭니다.', 79),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_80', '지구의 위성은?', '["화성","목성","태양","달"]', 3, '달은 지구의 유일한 자연 위성입니다.', 80),

-- === 기초 물리/화학 (81~100) ===
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_81', '물질의 세 가지 상태가 아닌 것은?', '["고체","액체","기체","전기"]', 3, '물질의 3상태는 고체, 액체, 기체입니다.', 81),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_82', '빛보다 빠른 것은?', '["소리","전파","아무것도 없다","비행기"]', 2, '진공에서 빛의 속도가 가장 빠르며 이를 넘을 수 없습니다.', 82),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_83', '중력이 우리에게 하는 일은?', '["위로 떠오르게 함","지구 중심으로 잡아당김","옆으로 밀어냄","아무 일도 안 함"]', 1, '중력은 모든 물체를 지구 중심으로 잡아당깁니다.', 83),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_84', '돋보기로 햇빛을 모으면 종이에 불이 붙는 이유는?', '["돋보기가 뜨거워서","빛이 한 점에 모여 열이 집중되어서","바람 때문에","마법 때문에"]', 1, '볼록렌즈가 빛을 한 점(초점)에 모아 열이 집중됩니다.', 84),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_85', '자석의 같은 극끼리는?', '["서로 당긴다","서로 밀어낸다","아무 반응 없다","합쳐진다"]', 1, '같은 극(N-N, S-S)은 서로 밀어냅니다(척력).', 85),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_86', '금속은 열을 잘 전달하나요?', '["네","아니요","나무보다 못함","관계없음"]', 0, '금속은 자유전자 덕분에 열전도율이 높습니다.', 86),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_87', 'H₂O는 무엇의 화학식인가요?', '["산소","수소","물","소금"]', 2, 'H₂O는 물의 화학식입니다.', 87),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_88', 'CO₂는 무엇의 화학식인가요?', '["산소","이산화탄소","일산화탄소","질소"]', 1, 'CO₂는 이산화탄소입니다.', 88),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_89', '빛의 3원색은?', '["빨강, 노랑, 파랑","빨강, 초록, 파랑","빨강, 초록, 노랑","노랑, 초록, 파랑"]', 1, '빛의 3원색은 빨강(R), 초록(G), 파랑(B)입니다.', 89),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_90', '번개가 치고 천둥이 나중에 들리는 이유는?', '["번개가 더 강해서","빛이 소리보다 빨라서","소리가 먼저 나서","둘은 관계없어서"]', 1, '빛의 속도(30만 km/s)가 소리(340m/s)보다 훨씬 빠릅니다.', 90),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_91', '물에 소금을 넣으면 어떻게 되나요?', '["소금이 녹는다","소금이 커진다","물이 얼어버린다","아무 변화 없다"]', 0, '소금(NaCl)은 물에 잘 녹는 물질입니다.', 91),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_92', '레몬즙이 신 이유는?', '["설탕 때문","산성(구연산) 때문","소금 때문","쓴맛 때문"]', 1, '레몬에는 구연산(시트르산)이 포함되어 있어 신맛이 납니다.', 92),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_93', '거울에 내 모습이 보이는 원리는?', '["거울이 빛을 만들어서","빛의 반사","빛의 굴절","빛의 흡수"]', 1, '거울은 빛을 반사하여 우리 모습을 보여줍니다.', 93),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_94', '정전기가 생기는 이유는?', '["물 때문에","마찰로 전자가 이동해서","자석 때문에","빛 때문에"]', 1, '마찰 시 한쪽에서 다른 쪽으로 전자가 이동하여 정전기가 생깁니다.', 94),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_95', '배터리(건전지)는 무엇을 저장하나요?', '["물","빛","화학 에너지","소리"]', 2, '건전지는 화학 에너지를 저장했다가 전기 에너지로 변환합니다.', 95),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_96', '그림자가 생기는 이유는?', '["빛이 물체를 통과하지 못해서","바람 때문에","열 때문에","소리 때문에"]', 0, '불투명한 물체가 빛을 가려 그림자가 생깁니다.', 96),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_97', '물속에서 빨대가 꺾여 보이는 현상은?', '["반사","굴절","산란","흡수"]', 1, '빛이 물과 공기의 경계에서 꺾이는 굴절 현상입니다.', 97),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_98', '온도계의 단위로 가장 흔히 쓰이는 것은?', '["섭씨(°C)","화씨(°F)","켈빈(K)","뉴턴(N)"]', 0, '한국에서는 섭씨(°C)를 가장 많이 사용합니다.', 98),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_99', '전구를 발명한 사람은?', '["아인슈타인","뉴턴","에디슨","갈릴레오"]', 2, '토마스 에디슨이 실용적인 전구를 발명했습니다.', 99),
((SELECT id FROM quiz_sets WHERE difficulty='STARTER' AND category='science'), 'sc_w_100', '지구의 중심부는 매우 뜨겁나요?', '["차갑다","미지근하다","매우 뜨겁다(약 6,000°C)","보통이다"]', 2, '지구 핵의 온도는 약 5,000~6,000°C입니다.', 100)
ON CONFLICT (question_id) DO NOTHING;
