-- =====================================================
-- 과학 상식 퀴즈: INTERMEDIATE (중급) - Part 2 [51~100]
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_51', '페니실린을 발견한 과학자는?', '["파스퇴르","플레밍","제너","코흐"]', 1, '알렉산더 플레밍이 1928년 페니실린을 발견했습니다.', 51),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_52', '백신의 원리는?', '["직접 병원체를 죽이기","면역 체계가 항체를 미리 만들게 유도","약물로 증상 억제","수술"]', 1, '약화/비활성된 병원체로 면역 체계가 항체를 미리 만들게 합니다.', 52),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_53', '유전자 편집 기술 CRISPR-Cas9의 기능은?', '["RNA 증폭","특정 DNA 서열을 정밀하게 편집","세포 배양","약물 전달"]', 1, 'CRISPR-Cas9은 DNA의 특정 부위를 잘라 편집하는 기술입니다.', 53),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_54', '플라스마(Plasma)란?', '["액체 상태","이온화된 기체(제4의 물질 상태)","초저온 상태","고체와 액체의 중간"]', 1, '플라스마는 이온과 전자로 분리된 기체 상태입니다.', 54),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_55', '쿼크(Quark)란?', '["원자핵","양성자와 중성자를 구성하는 기본 입자","전자의 일종","광자의 일종"]', 1, '쿼크는 양성자, 중성자를 구성하는 더 작은 기본 입자입니다.', 55),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_56', '암흑 물질(Dark matter)이란?', '["검은 암석","관측 불가하나 중력 효과로 존재가 추정되는 물질","빛을 흡수하는 물질","탄소 덩어리"]', 1, '암흑 물질은 빛과 상호작용하지 않지만 중력 효과가 관측됩니다.', 56),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_57', '광합성의 명반응이 일어나는 곳은?', '["미토콘드리아","엽록체의 틸라코이드","핵","세포질"]', 1, '명반응은 엽록체의 틸라코이드 막에서 일어납니다.', 57),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_58', '광합성의 암반응(캘빈 회로)이 일어나는 곳은?', '["틸라코이드","스트로마","핵","세포질"]', 1, '암반응은 엽록체의 스트로마에서 일어납니다.', 58),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_59', '만유인력 법칙에서 인력의 크기는 거리의?', '["1제곱에 비례","1제곱에 반비례","2제곱에 비례","2제곱에 반비례"]', 3, 'F = GMm/r² (거리의 제곱에 반비례).', 59),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_60', '전자볼트(eV)는 무엇의 단위인가요?', '["전압","에너지","전류","저항"]', 1, '전자볼트(eV)는 에너지의 단위입니다.', 60),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_61', '물질파(드브로이 파)란?', '["바다의 파도","물질 입자도 파동성을 갖는다","전자기파","음파"]', 1, '드브로이는 모든 물질이 파동성을 가진다고 제안했습니다(1924).', 61),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_62', '하이젠베르크의 불확정성 원리란?', '["모든 것은 확정적","위치와 운동량을 동시에 정확히 측정 불가","에너지 보존","질량 보존"]', 1, '입자의 위치와 운동량을 동시에 정확히 측정하는 것은 불가능합니다.', 62),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_63', 'pH 1과 pH 13 중 더 강한 산은?', '["pH 1","pH 13","같다","비교 불가"]', 0, 'pH가 낮을수록 강한 산, 높을수록 강한 염기입니다.', 63),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_64', '르샤틀리에의 원리란?', '["질량 보존","평형 상태가 교란되면 교란을 줄이는 방향으로 이동","에너지 보존","운동 법칙"]', 1, '화학 평형에서 외부 변화가 가해지면 그것을 상쇄하는 방향으로 이동.', 64),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_65', '질량 결손이란?', '["원자핵의 질량이 구성 입자들의 질량 합보다 작은 현상","질량이 증가하는 현상","질량 보존","에너지 보존"]', 0, '결합 에너지로 인해 핵의 질량이 구성 입자 합보다 작습니다.', 65),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_66', '변이(Mutation)란?', '["DNA 서열의 영구적 변화","단백질 합성","세포 분열","유전자 발현"]', 0, '변이는 DNA 서열에 일어나는 영구적인 변화입니다.', 66),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_67', '자연선택의 주요 조건이 아닌 것은?', '["변이 존재","과잉 생산","인위적 교배","생존 경쟁"]', 2, '자연선택의 조건: 변이, 과잉 생산, 생존 경쟁, 환경 적응.', 67),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_68', '지질 시대의 순서(오래된→최근)는?', '["고생대→중생대→신생대","신생대→중생대→고생대","중생대→고생대→신생대","고생대→신생대→중생대"]', 0, '선캄브리아→고생대→중생대→신생대 순서입니다.', 68),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_69', '공룡이 번성했던 시대는?', '["고생대","중생대","신생대","선캄브리아"]', 1, '공룡은 중생대(약 2.5억~6,600만 년 전)에 번성했습니다.', 69),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_70', '빅뱅 이론이란?', '["우주가 영원히 변하지 않음","우주가 한 점에서 대폭발로 시작","우주가 수축 중","우주는 무한히 많음"]', 1, '우주가 약 138억 년 전 한 점에서 대폭발로 시작되었다는 이론.', 70),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_71', '우주 배경 복사(CMB)란?', '["별빛","빅뱅 직후 남은 잔류 복사","은하의 빛","태양풍"]', 1, '빅뱅의 증거로, 우주 모든 방향에서 관측되는 전파 복사입니다.', 71),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_72', '항성의 에너지원은?', '["화석 연료","핵분열","핵융합","화학 반응"]', 2, '항성은 수소 핵융합으로 에너지를 생성합니다.', 72),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_73', '입자가속기의 목적은?', '["전기 생산","입자를 가속하여 충돌시켜 기본 입자 연구","의료 영상","통신"]', 1, 'LHC 등 입자가속기는 기본 입자의 성질을 연구합니다.', 73),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_74', '힉스 보손의 역할은?', '["빛을 만듦","입자에 질량을 부여하는 메커니즘과 관련","중력을 전달","전자기력 매개"]', 1, '힉스 장과의 상호작용으로 입자가 질량을 얻습니다(2012 발견).', 74),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_75', '자연계의 4가지 기본 힘이 아닌 것은?', '["중력","전자기력","강한 핵력","마찰력"]', 3, '4가지 기본 힘: 중력, 전자기력, 강한 핵력, 약한 핵력.', 75),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_76', '산화수란?', '["원자가 가지는 형식적 전하 상태","원자의 질량","원자의 크기","원자의 속도"]', 0, '산화수는 원자의 형식적 전하 상태를 나타내는 값입니다.', 76),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_77', '엔트로피가 높다는 것은?', '["질서가 높다","무질서도가 높다","에너지가 많다","온도가 낮다"]', 1, '엔트로피가 높을수록 무질서도(혼란도)가 높습니다.', 77),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_78', '뉴턴의 만유인력 상수 G의 단위는?', '["kg","m/s²","N·m²/kg²","J/K"]', 2, 'G의 단위는 N·m²/kg²입니다.', 78),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_79', '적색편이(Redshift)란?', '["별이 빨간색으로 변함","빛의 파장이 길어지는 현상(멀어지는 천체)","적외선 방출","붉은 별"]', 1, '멀어지는 천체의 빛은 파장이 길어져 빨간색 쪽으로 이동합니다.', 79),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_80', '중성자별이란?', '["중성자로만 이루어진 별","초신성 폭발 후 남은 극도로 밀집된 별","중성적인 별","보통 별"]', 1, '초신성 잔해로, 극도로 높은 밀도를 가진 천체입니다.', 80),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_81', '생물의 분류 단계(큰→작은) 순서는?', '["계-문-강-목-과-속-종","계-강-문-목-과-속-종","종-속-과-목-강-문-계","문-계-강-목-속-과-종"]', 0, '계(Kingdom)→문→강→목→과→속→종(Species).', 81),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_82', '전자 껍질에서 K 껍질에 들어갈 수 있는 최대 전자 수는?', '["2개","8개","18개","32개"]', 0, 'K 껍질(n=1)에는 최대 2개의 전자가 들어갑니다 (2n²).', 82),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_83', '비열이 큰 물질의 특징은?', '["온도가 빨리 변함","온도 변화가 느림","밀도가 높음","전기가 잘 통함"]', 1, '비열이 크면 같은 열을 가해도 온도가 천천히 올라갑니다.', 83),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_84', '물의 비열은 다른 물질에 비해?', '["매우 낮다","보통이다","매우 높다","측정 불가"]', 2, '물의 비열(4.18 J/g·°C)은 대부분의 물질보다 높습니다.', 84),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_85', '전기 분해란?', '["전류가 흐르는 것","전기 에너지로 화학 반응을 일으키는 것","화학 반응으로 전기를 만드는 것","전기를 저장하는 것"]', 1, '전기 에너지를 이용하여 물질을 분해하는 과정입니다.', 85),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_86', '연료 전지(Fuel cell)란?', '["가솔린 엔진","수소와 산소의 화학 반응으로 전기를 생산하는 장치","태양 전지","원자로"]', 1, '연료 전지는 수소+산소 → 물+전기 에너지 반응을 이용합니다.', 86),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_87', '패러데이의 전자기 유도 법칙이란?', '["전류가 자기장을 만듦","자기장의 변화가 기전력(전압)을 유도","F=ma","E=mc²"]', 1, '자기 선속의 변화가 기전력을 유도합니다(발전기 원리).', 87),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_88', '마이크로바이옴이란?', '["미세 먼지","인체에 서식하는 미생물 총체","현미경","미세 플라스틱"]', 1, '인체에 공존하는 수조 개의 미생물 군집을 말합니다.', 88),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_89', '탄소 순환에서 탄소가 대기로 돌아가는 과정이 아닌 것은?', '["호흡","연소","광합성","화석 연료 연소"]', 2, '광합성은 대기 중 CO₂를 흡수하는 과정입니다.', 89),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_90', '골지체의 역할은?', '["에너지 생산","단백질 변형, 포장, 수송","DNA 복제","세포 분열"]', 1, '골지체는 단백질을 변형, 분류, 포장하여 목적지로 보냅니다.', 90),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_91', '리보솜의 역할은?', '["에너지 생산","유전 정보를 바탕으로 단백질 합성","세포 분열","지방 합성"]', 1, '리보솜은 mRNA 정보를 읽어 단백질을 합성합니다.', 91),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_92', '삼투압이란?', '["기체의 압력","농도가 다른 용액 사이에서 용매가 이동하려는 압력","전기적 압력","빛의 압력"]', 1, '반투과성 막을 통해 용매가 저농도→고농도로 이동하려는 압력.', 92),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_93', '약한 핵력은 무엇에 관여하나요?', '["중력","전자기 현상","방사성 붕괴(베타 붕괴)","화학 반응"]', 2, '약한 핵력은 베타 붕괴 등 방사성 붕괴에 관여합니다.', 93),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_94', '강한 핵력의 역할은?', '["분자 간 결합","쿼크를 결합하여 양성자/중성자 구성","중력 발생","전자기파 생성"]', 1, '강한 핵력은 쿼크를 결합시켜 양성자와 중성자를 만듭니다.', 94),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_95', '페르마의 원리란?', '["빛은 최소 시간 경로를 따라 이동","빛은 직선 운동","빛은 파동","빛은 입자"]', 0, '빛은 두 점 사이를 최소 시간 경로로 이동합니다.', 95),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_96', '온실 효과란?', '["식물의 광합성","대기 중 온실가스가 열을 가둬 지표 온도 상승","오존층 파괴","해수면 상승"]', 1, '온실가스(CO₂, CH₄ 등)가 적외선을 흡수해 지표가 따뜻해지는 현상.', 96),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_97', '단백질을 구성하는 기본 단위는?', '["뉴클레오타이드","아미노산","포도당","지방산"]', 1, '단백질은 아미노산이 펩타이드 결합으로 연결된 것입니다.', 97),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_98', 'DNA를 구성하는 기본 단위는?', '["아미노산","뉴클레오타이드","포도당","지방산"]', 1, 'DNA는 뉴클레오타이드(인산+당+염기)의 중합체입니다.', 98),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_99', '태양의 수명은 약?', '["10억 년","50억 년","100억 년","1000억 년"]', 2, '태양은 약 100억 년의 수명을 가지며, 약 46억 년이 경과했습니다.', 99),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_100', '지구 자기장의 원인은?', '["대기","외핵의 액체 철 대류","지각의 자석","태양풍"]', 1, '외핵의 액체 철이 대류하면서 전류가 흘러 자기장을 생성합니다.', 100)
ON CONFLICT (question_id) DO NOTHING;
