-- =====================================================
-- English Quiz Seed: BEGINNER Part 1 [1~50]
-- Basic verbs, tenses, pronouns, prepositions
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_1', '"먹다"를 영어로?', '["Eat","Drink","Cook","Buy"]', 0, '"Eat"은 먹다입니다.', 1),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_2', '"마시다"를 영어로?', '["Eat","Drink","Cook","Buy"]', 1, '"Drink"는 마시다입니다.', 2),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_3', '"가다"를 영어로?', '["Go","Come","Run","Walk"]', 0, '"Go"는 가다입니다.', 3),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_4', '"오다"를 영어로?', '["Go","Come","Run","Walk"]', 1, '"Come"은 오다입니다.', 4),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_5', '"보다"를 영어로?', '["See","Hear","Speak","Read"]', 0, '"See"는 보다입니다.', 5),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_6', '"듣다"를 영어로?', '["See","Hear","Speak","Read"]', 1, '"Hear"는 듣다입니다.', 6),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_7', '"말하다"를 영어로?', '["See","Hear","Speak","Read"]', 2, '"Speak"은 말하다입니다.', 7),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_8', '"읽다"를 영어로?', '["See","Hear","Speak","Read"]', 3, '"Read"는 읽다입니다.', 8),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_9', '"쓰다"(글)를 영어로?', '["Write","Draw","Paint","Type"]', 0, '"Write"는 쓰다입니다.', 9),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_10', '"자다"를 영어로?', '["Sleep","Wake","Rest","Sit"]', 0, '"Sleep"는 자다입니다.', 10),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_11', '"사다"를 영어로?', '["Buy","Sell","Give","Take"]', 0, '"Buy"는 사다입니다.', 11),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_12', '"팔다"를 영어로?', '["Buy","Sell","Give","Take"]', 1, '"Sell"은 팔다입니다.', 12),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_13', '"주다"를 영어로?', '["Buy","Sell","Give","Take"]', 2, '"Give"는 주다입니다.', 13),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_14', '"가지다/받다"를 영어로?', '["Buy","Sell","Give","Take"]', 3, '"Take"는 가지다/받다입니다.', 14),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_15', '"만들다"를 영어로?', '["Make","Break","Fix","Find"]', 0, '"Make"는 만들다입니다.', 15),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_16', 'I ___ a student. 빈칸에 알맞은 것은?', '["is","am","are","be"]', 1, '주어가 I일 때 "am"을 씁니다.', 16),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_17', 'She ___ a teacher. 빈칸에 알맞은 것은?', '["is","am","are","be"]', 0, '3인칭 단수 주어에는 "is"를 씁니다.', 17),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_18', 'They ___ friends. 빈칸에 알맞은 것은?', '["is","am","are","be"]', 2, '복수 주어에는 "are"를 씁니다.', 18),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_19', '"나"를 영어로? (주격)', '["I","Me","My","Mine"]', 0, '주격은 "I"입니다.', 19),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_20', '"나의"를 영어로?', '["I","Me","My","Mine"]', 2, '소유격은 "My"입니다.', 20),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_21', '"그녀"를 영어로? (주격)', '["He","She","Her","His"]', 1, '"She"는 그녀(주격)입니다.', 21),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_22', '"그"를 영어로? (주격)', '["He","She","Her","His"]', 0, '"He"는 그(주격)입니다.', 22),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_23', '"우리"를 영어로?', '["We","They","You","Us"]', 0, '"We"는 우리(주격)입니다.', 23),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_24', '"~위에"를 영어로?', '["On","In","Under","Next to"]', 0, '"On"은 ~위에입니다.', 24),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_25', '"~안에"를 영어로?', '["On","In","Under","Next to"]', 1, '"In"은 ~안에입니다.', 25),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_26', '"~아래에"를 영어로?', '["On","In","Under","Next to"]', 2, '"Under"는 ~아래에입니다.', 26),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_27', '"~옆에"를 영어로?', '["On","In","Under","Next to"]', 3, '"Next to"는 ~옆에입니다.', 27),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_28', 'I ___ to school every day. (가다)', '["go","goes","going","went"]', 0, '1인칭 현재 시제는 동사 원형 "go"를 씁니다.', 28),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_29', 'She ___ to school every day. (가다)', '["go","goes","going","went"]', 1, '3인칭 단수 현재에는 "goes"를 씁니다.', 29),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_30', 'I ___ breakfast this morning. (먹다 - 과거)', '["eat","eats","ate","eaten"]', 2, '"eat"의 과거형은 "ate"입니다.', 30),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_31', '"월요일"을 영어로?', '["Monday","Tuesday","Wednesday","Thursday"]', 0, '"Monday"는 월요일입니다.', 31),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_32', '"일요일"을 영어로?', '["Friday","Saturday","Sunday","Thursday"]', 2, '"Sunday"는 일요일입니다.', 32),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_33', '"1월"을 영어로?', '["January","February","March","April"]', 0, '"January"는 1월입니다.', 33),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_34', '"12월"을 영어로?', '["October","November","December","September"]', 2, '"December"는 12월입니다.', 34),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_35', '"봄"을 영어로?', '["Spring","Summer","Fall","Winter"]', 0, '"Spring"은 봄입니다.', 35),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_36', '"여름"을 영어로?', '["Spring","Summer","Fall","Winter"]', 1, '"Summer"는 여름입니다.', 36),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_37', '"가을"을 영어로?', '["Spring","Summer","Fall/Autumn","Winter"]', 2, '"Fall" 또는 "Autumn"이 가을입니다.', 37),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_38', '"겨울"을 영어로?', '["Spring","Summer","Fall","Winter"]', 3, '"Winter"는 겨울입니다.', 38),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_39', 'There ___ a book on the table.', '["is","are","am","be"]', 0, '단수 명사이므로 "is"를 씁니다.', 39),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_40', 'There ___ many students in the class.', '["is","are","am","be"]', 1, '복수 명사이므로 "are"를 씁니다.', 40),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_41', '"이것"을 영어로?', '["This","That","These","Those"]', 0, '"This"는 이것입니다.', 41),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_42', '"저것"을 영어로?', '["This","That","These","Those"]', 1, '"That"은 저것입니다.', 42),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_43', '"이것들"을 영어로?', '["This","That","These","Those"]', 2, '"These"는 이것들입니다.', 43),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_44', 'Can I ___ some water? (가지다)', '["has","have","had","having"]', 1, '"Can" 뒤에는 동사 원형 "have"를 씁니다.', 44),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_45', 'I ___ not like coffee. (do 부정)', '["do","does","did","am"]', 0, '1인칭 현재 부정문에 "do"를 씁니다.', 45),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_46', 'She ___ not like coffee.', '["do","does","did","am"]', 1, '3인칭 단수 부정문에 "does"를 씁니다.', 46),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_47', '"무엇"을 영어로?', '["What","Where","When","Who"]', 0, '"What"은 무엇입니다.', 47),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_48', '"어디"를 영어로?', '["What","Where","When","Who"]', 1, '"Where"는 어디입니다.', 48),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_49', '"언제"를 영어로?', '["What","Where","When","Who"]', 2, '"When"은 언제입니다.', 49),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_50', '"누구"를 영어로?', '["What","Where","When","Who"]', 3, '"Who"는 누구입니다.', 50)
ON CONFLICT (question_id) DO NOTHING;


INSERT INTO quiz_questions (correct_option_index, created_at, explanation, options, question, question_id, sort_order, set_id) VALUES
-- 1~20: Be동사 (현재/과거)
(1, CURRENT_TIMESTAMP, 'I에 알맞은 be동사 현재형은 am입니다.', '["is", "am", "are", "be"]', 'I ___ happy.', 'en_bg_fb_1', 1, 10),
(2, CURRENT_TIMESTAMP, 'You에 알맞은 be동사 현재형은 are입니다.', '["is", "am", "are", "be"]', 'You ___ late.', 'en_bg_fb_2', 2, 10),
(0, CURRENT_TIMESTAMP, 'He에 알맞은 be동사 현재형은 is입니다.', '["is", "am", "are", "be"]', 'He ___ tall.', 'en_bg_fb_3', 3, 10),
(0, CURRENT_TIMESTAMP, 'She에 알맞은 be동사 현재형은 is입니다.', '["is", "am", "are", "be"]', 'She ___ my sister.', 'en_bg_fb_4', 4, 10),
(0, CURRENT_TIMESTAMP, 'It에 알맞은 be동사 현재형은 is입니다.', '["is", "am", "are", "be"]', 'It ___ a sunny day.', 'en_bg_fb_5', 5, 10),
(2, CURRENT_TIMESTAMP, 'We에 알맞은 be동사 현재형은 are입니다.', '["is", "am", "are", "be"]', 'We ___ ready.', 'en_bg_fb_6', 6, 10),
(2, CURRENT_TIMESTAMP, 'They에 알맞은 be동사 현재형은 are입니다.', '["is", "am", "are", "be"]', 'They ___ at home.', 'en_bg_fb_7', 7, 10),
(3, CURRENT_TIMESTAMP, 'yesterday(어제)가 있으므로 과거형 was가 옵니다.', '["is", "am", "are", "was"]', 'I ___ tired yesterday.', 'en_bg_fb_8', 8, 10),
(3, CURRENT_TIMESTAMP, 'You의 과거형 be동사는 were입니다.', '["was", "is", "are", "were"]', 'You ___ right.', 'en_bg_fb_9', 9, 10),
(0, CURRENT_TIMESTAMP, 'before가 있으므로 과거형 was가 옵니다.', '["was", "were", "is", "are"]', 'He ___ a doctor before.', 'en_bg_fb_10', 10, 10),
(1, CURRENT_TIMESTAMP, 'yesterday가 있으므로 과거형 was가 옵니다.', '["is", "was", "were", "are"]', 'She ___ at school yesterday.', 'en_bg_fb_11', 11, 10),
(1, CURRENT_TIMESTAMP, 'last night이 있으므로 과거형 was가 옵니다.', '["is", "was", "were", "are"]', 'It ___ raining last night.', 'en_bg_fb_12', 12, 10),
(2, CURRENT_TIMESTAMP, 'last week가 있으므로 복수 과거형 were가 옵니다.', '["is", "was", "were", "are"]', 'We ___ busy last week.', 'en_bg_fb_13', 13, 10),
(3, CURRENT_TIMESTAMP, 'They의 과거형은 were입니다.', '["are", "is", "was", "were"]', 'They ___ happy yesterday.', 'en_bg_fb_14', 14, 10),
(2, CURRENT_TIMESTAMP, 'You와 어울리는 의문문 be동사는 Are입니다.', '["Is", "Am", "Are", "Was"]', '___ you okay?', 'en_bg_fb_15', 15, 10),
(0, CURRENT_TIMESTAMP, 'He와 어울리는 의문문 be동사는 Is입니다.', '["Is", "Am", "Are", "Were"]', '___ he a student?', 'en_bg_fb_16', 16, 10),
(0, CURRENT_TIMESTAMP, 'It과 어울리는 의문문 be동사는 Is입니다.', '["Is", "Am", "Are", "Were"]', '___ it cold outside?', 'en_bg_fb_17', 17, 10),
(2, CURRENT_TIMESTAMP, 'They와 어울리는 의문문 be동사는 Are입니다.', '["Is", "Am", "Are", "Were"]', '___ they your friends?', 'en_bg_fb_18', 18, 10),
(1, CURRENT_TIMESTAMP, 'I의 부정문은 am not입니다.', '["is", "am", "are", "be"]', 'I ___ not a doctor.', 'en_bg_fb_19', 19, 10),
(0, CURRENT_TIMESTAMP, 'She의 부정문은 is not입니다.', '["is", "am", "are", "be"]', 'She ___ not here.', 'en_bg_fb_20', 20, 10),

-- 21~40: 일반동사 (현재시제 및 3인칭 단수)
(1, CURRENT_TIMESTAMP, '현재 습관을 나타내는 일반동사 원형이 옵니다.', '["eats", "eat", "eating", "ate"]', 'I ___ an apple every morning.', 'en_bg_fb_21', 21, 10),
(0, CURRENT_TIMESTAMP, '주어가 You이므로 동사원형이 옵니다.', '["speak", "speaks", "speaking", "spoke"]', 'You ___ English well.', 'en_bg_fb_22', 22, 10),
(1, CURRENT_TIMESTAMP, '주어가 3인칭 단수(He)이므로 동사에 s가 붙습니다.', '["play", "plays", "playing", "played"]', 'He ___ soccer on weekends.', 'en_bg_fb_23', 23, 10),
(2, CURRENT_TIMESTAMP, '주어가 She이므로 listens가 옵니다.', '["listen", "listening", "listens", "listened"]', 'She ___ to music.', 'en_bg_fb_24', 24, 10),
(1, CURRENT_TIMESTAMP, '주어가 It이므로 rains가 옵니다.', '["rain", "rains", "raining", "rained"]', 'It ___ a lot in summer.', 'en_bg_fb_25', 25, 10),
(0, CURRENT_TIMESTAMP, '주어가 We이므로 동사원형 live가 옵니다.', '["live", "lives", "living", "lived"]', 'We ___ in a big house.', 'en_bg_fb_26', 26, 10),
(3, CURRENT_TIMESTAMP, '주어가 They이므로 watch가 옵니다.', '["watches", "watching", "watched", "watch"]', 'They ___ TV every night.', 'en_bg_fb_27', 27, 10),
(1, CURRENT_TIMESTAMP, 'The sun은 3인칭 단수이므로 rises가 옵니다.', '["rise", "rises", "rising", "rose"]', 'The sun ___ in the east.', 'en_bg_fb_28', 28, 10),
(1, CURRENT_TIMESTAMP, 'My mom은 3인칭 단수이므로 cooks가 옵니다.', '["cook", "cooks", "cooking", "cooked"]', 'My mom ___ delicious food.', 'en_bg_fb_29', 29, 10),
(0, CURRENT_TIMESTAMP, 'Dogs는 복수이므로 like가 옵니다.', '["like", "likes", "liking", "liked"]', 'Dogs ___ bones.', 'en_bg_fb_30', 30, 10),
(2, CURRENT_TIMESTAMP, 'do not 뒤에는 동사원형이 옵니다.', '["drinks", "drinking", "drink", "drank"]', 'I do not ___ coffee.', 'en_bg_fb_31', 31, 10),
(0, CURRENT_TIMESTAMP, 'does not 뒤에는 동사원형이 옵니다.', '["eat", "eats", "eating", "ate"]', 'She does not ___ meat.', 'en_bg_fb_32', 32, 10),
(1, CURRENT_TIMESTAMP, 'doesn''t 뒤에는 동사원형이 옵니다.', '["has", "have", "having", "had"]', 'He doesn''t ___ a car.', 'en_bg_fb_33', 33, 10),
(0, CURRENT_TIMESTAMP, '조동사 Do 의문문 뒤에는 동사원형이 옵니다.', '["know", "knows", "knowing", "knew"]', 'Do you ___ me?', 'en_bg_fb_34', 34, 10),
(2, CURRENT_TIMESTAMP, 'Does 의문문 뒤에는 동사원형이 옵니다.', '["works", "working", "work", "worked"]', 'Does he ___ here?', 'en_bg_fb_35', 35, 10),
(0, CURRENT_TIMESTAMP, 'I 뒤에는 동사원형이 옵니다.', '["go", "goes", "going", "went"]', 'I ___ to bed at 10 PM.', 'en_bg_fb_36', 36, 10),
(1, CURRENT_TIMESTAMP, 'He 뒤에는 es가 붙은 형태가 옵니다.', '["wash", "washes", "washing", "washed"]', 'He ___ his hands before meals.', 'en_bg_fb_37', 37, 10),
(2, CURRENT_TIMESTAMP, 'She 뒤에는 -y를 -ies로 바꾼 형태가 옵니다.', '["study", "studys", "studies", "studying"]', 'She ___ hard for exams.', 'en_bg_fb_38', 38, 10),
(0, CURRENT_TIMESTAMP, 'We 뒤에는 동사원형이 옵니다.', '["love", "loves", "loving", "loved"]', 'We ___ our parents.', 'en_bg_fb_39', 39, 10),
(1, CURRENT_TIMESTAMP, 'They 뒤에는 동사원형이 옵니다.', '["takes", "take", "taking", "took"]', 'They ___ the bus to school.', 'en_bg_fb_40', 40, 10),

-- 41~60: 일반동사 (과거시제)
(3, CURRENT_TIMESTAMP, 'yesterday가 있으므로 go의 과거형 went가 옵니다.', '["go", "goes", "going", "went"]', 'I ___ to the park yesterday.', 'en_bg_fb_41', 41, 10),
(2, CURRENT_TIMESTAMP, 'do의 과거형 did가 옵니다.', '["do", "does", "did", "done"]', 'You ___ a great job.', 'en_bg_fb_42', 42, 10),
(1, CURRENT_TIMESTAMP, 'last night이 있으므로 see의 과거형 saw가 옵니다.', '["see", "saw", "seen", "seeing"]', 'He ___ a movie last night.', 'en_bg_fb_43', 43, 10),
(0, CURRENT_TIMESTAMP, 'last week가 있으므로 read의 과거형(형태 동일)이 옵니다.', '["read", "reads", "reading", "write"]', 'She ___ a book last week.', 'en_bg_fb_44', 44, 10),
(2, CURRENT_TIMESTAMP, 'eat의 과거형 ate가 옵니다.', '["eat", "eats", "ate", "eating"]', 'We ___ pizza for dinner.', 'en_bg_fb_45', 45, 10),
(1, CURRENT_TIMESTAMP, 'play의 과거형 played가 옵니다.', '["play", "played", "playing", "plays"]', 'They ___ soccer yesterday.', 'en_bg_fb_46', 46, 10),
(3, CURRENT_TIMESTAMP, 'meet의 과거형 met가 옵니다.', '["meet", "meets", "meeting", "met"]', 'I ___ him yesterday.', 'en_bg_fb_47', 47, 10),
(1, CURRENT_TIMESTAMP, 'buy의 과거형 bought가 옵니다.', '["buy", "bought", "buys", "buying"]', 'She ___ a new bag.', 'en_bg_fb_48', 48, 10),
(2, CURRENT_TIMESTAMP, 'write의 과거형 wrote가 옵니다.', '["write", "writes", "wrote", "written"]', 'He ___ a letter to her.', 'en_bg_fb_49', 49, 10),
(0, CURRENT_TIMESTAMP, 'sing의 과거형 sang이 옵니다.', '["sang", "sing", "sings", "sung"]', 'We ___ a song together.', 'en_bg_fb_50', 50, 10),
(1, CURRENT_TIMESTAMP, 'win의 과거형 won이 옵니다.', '["win", "won", "wins", "winning"]', 'They ___ the game.', 'en_bg_fb_51', 51, 10),
(0, CURRENT_TIMESTAMP, 'didn''t 뒤에는 동사원형이 옵니다.', '["do", "did", "does", "done"]', 'I didn''t ___ my homework.', 'en_bg_fb_52', 52, 10),
(2, CURRENT_TIMESTAMP, 'didn''t 뒤에는 동사원형이 옵니다.', '["came", "comes", "come", "coming"]', 'She didn''t ___ to the party.', 'en_bg_fb_53', 53, 10),
(1, CURRENT_TIMESTAMP, 'Did 의문문 뒤에는 동사원형이 옵니다.', '["slept", "sleep", "sleeps", "sleeping"]', 'Did you ___ well?', 'en_bg_fb_54', 54, 10),
(0, CURRENT_TIMESTAMP, 'Did 의문문 뒤에는 동사원형이 옵니다.', '["open", "opened", "opens", "opening"]', 'Did he ___ the window?', 'en_bg_fb_55', 55, 10),
(3, CURRENT_TIMESTAMP, 'lose의 과거형 lost가 옵니다.', '["lose", "loses", "losing", "lost"]', 'I ___ my key yesterday.', 'en_bg_fb_56', 56, 10),
(1, CURRENT_TIMESTAMP, 'give의 과거형 gave가 옵니다.', '["give", "gave", "given", "gives"]', 'She ___ me a gift.', 'en_bg_fb_57', 57, 10),
(2, CURRENT_TIMESTAMP, 'last summer가 있으므로 go의 과거형 went가 옵니다.', '["go", "goes", "went", "gone"]', 'We ___ to the beach last summer.', 'en_bg_fb_58', 58, 10),
(0, CURRENT_TIMESTAMP, 'hit의 과거형(형태 동일)이 옵니다.', '["hit", "hits", "hitted", "hitting"]', 'He ___ the ball hard.', 'en_bg_fb_59', 59, 10),
(1, CURRENT_TIMESTAMP, 'build의 과거형 built가 옵니다.', '["build", "built", "builds", "building"]', 'They ___ a house last year.', 'en_bg_fb_60', 60, 10),

-- 61~80: 대명사 (주격, 소유격, 목적격)
(0, CURRENT_TIMESTAMP, '주어 자리이므로 주격 He가 옵니다.', '["He", "Him", "His", "Himself"]', '___ is my best friend.', 'en_bg_fb_61', 61, 10),
(1, CURRENT_TIMESTAMP, '전치사 at 뒤에는 목적격 her가 옵니다.', '["she", "her", "hers", "herself"]', 'Look at ___. She is dancing.', 'en_bg_fb_62', 62, 10),
(2, CURRENT_TIMESTAMP, '명사 앞이므로 소유격 my가 옵니다.', '["me", "I", "my", "mine"]', 'This is ___ book.', 'en_bg_fb_63', 63, 10),
(1, CURRENT_TIMESTAMP, '동물의 소유격은 its입니다.', '["it", "its", "it''s", "itself"]', 'The cat is washing ___ face.', 'en_bg_fb_64', 64, 10),
(0, CURRENT_TIMESTAMP, '동사 뒤 목적어 자리이므로 me가 옵니다.', '["me", "my", "I", "mine"]', 'Can you help ___?', 'en_bg_fb_65', 65, 10),
(2, CURRENT_TIMESTAMP, '동사 뒤 목적어 자리이므로 you가 옵니다.', '["your", "yours", "you", "yourself"]', 'I love ___.', 'en_bg_fb_66', 66, 10),
(3, CURRENT_TIMESTAMP, '그들의 것(소유대명사)이므로 theirs가 옵니다.', '["they", "them", "their", "theirs"]', 'That car is ___.', 'en_bg_fb_67', 67, 10),
(1, CURRENT_TIMESTAMP, '나의 것(소유대명사)이므로 mine이 옵니다.', '["my", "mine", "me", "I"]', 'This bag is ___.', 'en_bg_fb_68', 68, 10),
(0, CURRENT_TIMESTAMP, '주어 자리 복수형이므로 We가 옵니다.', '["We", "Us", "Our", "Ours"]', '___ are going to the mall.', 'en_bg_fb_69', 69, 10),
(2, CURRENT_TIMESTAMP, '동사 뒤 목적어 자리이므로 us가 옵니다.', '["we", "our", "us", "ours"]', 'Please tell ___ the truth.', 'en_bg_fb_70', 70, 10),
(1, CURRENT_TIMESTAMP, '동사 뒤 목적어 자리이므로 him이 옵니다.', '["he", "him", "his", "himself"]', 'I know ___. He is famous.', 'en_bg_fb_71', 71, 10),
(0, CURRENT_TIMESTAMP, '명사 앞이므로 소유격 His가 옵니다.', '["His", "He", "Him", "Himself"]', '___ name is John.', 'en_bg_fb_72', 72, 10),
(2, CURRENT_TIMESTAMP, '명사 앞이므로 소유격 your가 옵니다.', '["you", "yours", "your", "yourself"]', 'Is this ___ pen?', 'en_bg_fb_73', 73, 10),
(3, CURRENT_TIMESTAMP, '주어 자리 복수형이므로 They가 옵니다.', '["Them", "Their", "Theirs", "They"]', '___ are very kind.', 'en_bg_fb_74', 74, 10),
(1, CURRENT_TIMESTAMP, '동사 뒤 목적어 자리 복수형이므로 them이 옵니다.', '["they", "them", "their", "theirs"]', 'I saw ___ at the park.', 'en_bg_fb_75', 75, 10),
(0, CURRENT_TIMESTAMP, 'by oneself(스스로) 형태이므로 herself가 옵니다.', '["herself", "her", "she", "hers"]', 'She made it by ___.', 'en_bg_fb_76', 76, 10),
(2, CURRENT_TIMESTAMP, 'I를 강조하는 재귀대명사 myself가 옵니다.', '["me", "my", "myself", "mine"]', 'I did it ___.', 'en_bg_fb_77', 77, 10),
(1, CURRENT_TIMESTAMP, '주어 He와 동일한 대상을 지칭하므로 himself가 옵니다.', '["him", "himself", "his", "he"]', 'He cut ___ with a knife.', 'en_bg_fb_78', 78, 10),
(3, CURRENT_TIMESTAMP, 'enjoy oneself(~를 즐기다) 형태이므로 ourselves가 옵니다.', '["us", "our", "ours", "ourselves"]', 'We enjoyed ___ at the party.', 'en_bg_fb_79', 79, 10),
(0, CURRENT_TIMESTAMP, '그녀의 것(소유대명사)이므로 hers가 옵니다.', '["hers", "her", "she", "herself"]', 'This book is ___.', 'en_bg_fb_80', 80, 10),

-- 81~100: 시간 전치사
(1, CURRENT_TIMESTAMP, '연도 앞에는 전치사 in을 씁니다.', '["on", "in", "at", "to"]', 'I was born ___ 1990.', 'en_bg_fb_81', 81, 10),
(0, CURRENT_TIMESTAMP, '요일 앞에는 전치사 on을 씁니다.', '["on", "in", "at", "for"]', 'See you ___ Monday.', 'en_bg_fb_82', 82, 10),
(2, CURRENT_TIMESTAMP, '시각 앞에는 전치사 at을 씁니다.', '["in", "on", "at", "by"]', 'The class starts ___ 9 AM.', 'en_bg_fb_83', 83, 10),
(1, CURRENT_TIMESTAMP, '계절 앞에는 전치사 in을 씁니다.', '["at", "in", "on", "for"]', 'We go skiing ___ winter.', 'en_bg_fb_84', 84, 10),
(2, CURRENT_TIMESTAMP, '정오(noon) 앞에는 at을 씁니다.', '["on", "in", "at", "to"]', 'Let''s meet ___ noon.', 'en_bg_fb_85', 85, 10),
(0, CURRENT_TIMESTAMP, '달(Month) 앞에는 in을 씁니다.', '["in", "on", "at", "by"]', 'My birthday is ___ May.', 'en_bg_fb_86', 86, 10),
(1, CURRENT_TIMESTAMP, '특정한 날짜 앞에는 on을 씁니다.', '["in", "on", "at", "for"]', 'The concert is ___ July 4th.', 'en_bg_fb_87', 87, 10),
(0, CURRENT_TIMESTAMP, '아침/오후/저녁 앞에는 in을 씁니다.', '["in", "on", "at", "to"]', 'I read a book ___ the evening.', 'en_bg_fb_88', 88, 10),
(2, CURRENT_TIMESTAMP, 'night 앞에는 at을 씁니다.', '["in", "on", "at", "for"]', 'She sleeps ___ night.', 'en_bg_fb_89', 89, 10),
(0, CURRENT_TIMESTAMP, '아침(morning) 앞에는 in을 씁니다.', '["in", "on", "at", "by"]', 'We have a meeting ___ the morning.', 'en_bg_fb_90', 90, 10),
(1, CURRENT_TIMESTAMP, '~시간 후에(시간의 경과)는 in을 씁니다.', '["on", "in", "at", "for"]', 'He will arrive ___ an hour.', 'en_bg_fb_91', 91, 10),
(3, CURRENT_TIMESTAMP, 'from A to B (~부터 ~까지) 구문입니다.', '["in", "on", "at", "to"]', 'I work from Monday ___ Friday.', 'en_bg_fb_92', 92, 10),
(2, CURRENT_TIMESTAMP, '~동안(숫자 기간)은 for를 씁니다.', '["during", "since", "for", "in"]', 'We stayed there ___ three days.', 'en_bg_fb_93', 93, 10),
(1, CURRENT_TIMESTAMP, '~이후로 쭉(현재완료)은 since를 씁니다.', '["for", "since", "in", "from"]', 'I have lived here ___ 2010.', 'en_bg_fb_94', 94, 10),
(0, CURRENT_TIMESTAMP, '~할 때까지 계속이라는 뜻의 until이 적절합니다.', '["until", "by", "for", "in"]', 'I will wait ___ you come back.', 'en_bg_fb_95', 95, 10),
(2, CURRENT_TIMESTAMP, '~하기 전에라는 뜻의 before가 적절합니다.', '["after", "in", "before", "on"]', 'Wash your hands ___ meals.', 'en_bg_fb_96', 96, 10),
(1, CURRENT_TIMESTAMP, '~한 후에라는 뜻의 after가 적절합니다.', '["before", "after", "in", "at"]', 'Let''s play soccer ___ school.', 'en_bg_fb_97', 97, 10),
(3, CURRENT_TIMESTAMP, '기간 ~이내에 라는 뜻의 within이 적절합니다.', '["in", "on", "for", "within"]', 'He finished it ___ a week.', 'en_bg_fb_98', 98, 10),
(2, CURRENT_TIMESTAMP, '시각 앞에는 at을 씁니다.', '["in", "on", "at", "for"]', 'The store opens ___ 10 AM.', 'en_bg_fb_99', 99, 10),
(1, CURRENT_TIMESTAMP, '주말 앞에는 on(또는 at)을 씁니다.', '["in", "on", "for", "to"]', 'We relax ___ the weekend.', 'en_bg_fb_100', 100, 10),

-- 101~120: 장소 전치사
(0, CURRENT_TIMESTAMP, '표면 위를 나타내는 on이 적절합니다.', '["on", "in", "at", "under"]', 'The book is ___ the desk.', 'en_bg_fb_101', 101, 10),
(1, CURRENT_TIMESTAMP, '내부 공간을 나타내는 in이 적절합니다.', '["on", "in", "at", "over"]', 'She is ___ the kitchen.', 'en_bg_fb_102', 102, 10),
(2, CURRENT_TIMESTAMP, '특정 지점을 나타내는 at이 적절합니다.', '["on", "in", "at", "by"]', 'Let''s meet ___ the bus stop.', 'en_bg_fb_103', 103, 10),
(3, CURRENT_TIMESTAMP, '아래를 나타내는 under가 적절합니다.', '["on", "in", "over", "under"]', 'The cat is hiding ___ the table.', 'en_bg_fb_104', 104, 10),
(0, CURRENT_TIMESTAMP, '벽 표면에 붙어있으므로 on이 적절합니다.', '["on", "in", "at", "under"]', 'The picture is ___ the wall.', 'en_bg_fb_105', 105, 10),
(2, CURRENT_TIMESTAMP, '위로 넘어가는 모양인 over가 적절합니다.', '["on", "in", "over", "under"]', 'The bird flew ___ the tree.', 'en_bg_fb_106', 106, 10),
(1, CURRENT_TIMESTAMP, 'in front of(~의 앞에) 구문입니다.', '["on", "in", "at", "to"]', 'The car is ___ front of the house.', 'en_bg_fb_107', 107, 10),
(0, CURRENT_TIMESTAMP, 'next to(~의 옆에) 구문입니다.', '["next", "near", "beside", "by"]', 'The bank is ___ to the post office.', 'en_bg_fb_108', 108, 10),
(3, CURRENT_TIMESTAMP, '가로질러 있다는 뜻의 across가 적절합니다.', '["along", "through", "into", "across"]', 'There is a bridge ___ the river.', 'en_bg_fb_109', 109, 10),
(1, CURRENT_TIMESTAMP, '땅 아래(지하)이므로 under가 적절합니다.', '["over", "under", "on", "in"]', 'The subway goes ___ the ground.', 'en_bg_fb_110', 110, 10),
(0, CURRENT_TIMESTAMP, '도시 등 넓은 지역 앞에는 in을 씁니다.', '["in", "on", "at", "to"]', 'He lives ___ Seoul.', 'en_bg_fb_111', 111, 10),
(2, CURRENT_TIMESTAMP, '안으로(방향성)를 나타내는 into(또는 in)가 적절합니다.', '["on", "at", "in", "over"]', 'Put the apples ___ the box.', 'en_bg_fb_112', 112, 10),
(1, CURRENT_TIMESTAMP, '~옆에 라는 뜻의 beside가 적절합니다.', '["between", "beside", "among", "across"]', 'She sat ___ him.', 'en_bg_fb_113', 113, 10),
(3, CURRENT_TIMESTAMP, '기준보다 위쪽을 나타내는 above가 적절합니다.', '["under", "below", "on", "above"]', 'The plane flew ___ the clouds.', 'en_bg_fb_114', 114, 10),
(0, CURRENT_TIMESTAMP, '가로질러 뛰었다는 across가 적절합니다.', '["across", "through", "along", "in"]', 'A dog ran ___ the road.', 'en_bg_fb_115', 115, 10),
(2, CURRENT_TIMESTAMP, '길을 따라(along) 걷는다는 의미입니다.', '["across", "through", "along", "between"]', 'Walk ___ the street.', 'en_bg_fb_116', 116, 10),
(1, CURRENT_TIMESTAMP, '통과하여(through) 간다는 의미입니다.', '["across", "through", "along", "over"]', 'Go ___ the door.', 'en_bg_fb_117', 117, 10),
(0, CURRENT_TIMESTAMP, '둘 사이를 나타내는 between A and B 구문입니다.', '["between", "among", "in", "on"]', 'The school is ___ the park and the bank.', 'en_bg_fb_118', 118, 10),
(3, CURRENT_TIMESTAMP, '문 앞(특정 지점)이므로 at이 적절합니다.', '["in", "on", "over", "at"]', 'He is waiting ___ the door.', 'en_bg_fb_119', 119, 10),
(1, CURRENT_TIMESTAMP, '바닥 표면 위이므로 on이 적절합니다.', '["in", "on", "at", "under"]', 'Don''t sit ___ the floor.', 'en_bg_fb_120', 120, 10),

-- 121~140: 조동사
(0, CURRENT_TIMESTAMP, '능력을 나타내는 can(~할 수 있다)이 적절합니다.', '["can", "must", "should", "will"]', 'I ___ swim very well.', 'en_bg_fb_121', 121, 10),
(1, CURRENT_TIMESTAMP, '강한 의무를 나타내는 must(~해야 한다)가 적절합니다.', '["can", "must", "may", "will"]', 'You ___ wear a seatbelt.', 'en_bg_fb_122', 122, 10),
(3, CURRENT_TIMESTAMP, '미래를 나타내는 will(~일 것이다)이 적절합니다.', '["can", "must", "should", "will"]', 'It ___ rain tomorrow.', 'en_bg_fb_123', 123, 10),
(2, CURRENT_TIMESTAMP, '정중한 요청을 나타내는 Could가 적절합니다.', '["Must", "Should", "Could", "May"]', '___ you help me, please?', 'en_bg_fb_124', 124, 10),
(1, CURRENT_TIMESTAMP, '충고/권유를 나타내는 should(~하는 것이 좋다)가 적절합니다.', '["will", "should", "can", "may"]', 'You ___ see a doctor.', 'en_bg_fb_125', 125, 10),
(3, CURRENT_TIMESTAMP, '허락을 구하는 May I ~? 가 적절합니다.', '["Must", "Will", "Should", "May"]', '___ I open the window?', 'en_bg_fb_126', 126, 10),
(0, CURRENT_TIMESTAMP, '불가능을 나타내는 cannot이 적절합니다.', '["cannot", "must", "should", "will"]', 'He ___ not speak French.', 'en_bg_fb_127', 127, 10),
(2, CURRENT_TIMESTAMP, '약한 추측을 나타내는 might(~일지도 모른다)가 적절합니다.', '["can", "must", "might", "will"]', 'I ___ be late today.', 'en_bg_fb_128', 128, 10),
(1, CURRENT_TIMESTAMP, '의무를 나타내는 must가 적절합니다.', '["can", "must", "may", "will"]', 'We ___ go now. It is late.', 'en_bg_fb_129', 129, 10),
(0, CURRENT_TIMESTAMP, '권유를 나타내는 Would you like ~? 구문입니다.', '["Would", "Should", "Could", "Must"]', '___ you like some tea?', 'en_bg_fb_130', 130, 10),
(3, CURRENT_TIMESTAMP, '~할 필요가 없다(don''t have to) 구문입니다.', '["must", "should", "can", "have"]', 'You don''t ___ to come.', 'en_bg_fb_131', 131, 10),
(2, CURRENT_TIMESTAMP, '의지를 나타내는 will이 적절합니다.', '["can", "must", "will", "may"]', 'I ___ do my best.', 'en_bg_fb_132', 132, 10),
(0, CURRENT_TIMESTAMP, '능력을 나타내는 can이 적절합니다.', '["can", "must", "should", "will"]', 'She ___ play the piano.', 'en_bg_fb_133', 133, 10),
(1, CURRENT_TIMESTAMP, '강한 의무를 나타내는 must가 적절합니다.', '["can", "must", "may", "will"]', 'We ___ obey the rules.', 'en_bg_fb_134', 134, 10),
(2, CURRENT_TIMESTAMP, '허락을 구하는 Can I ~? 구문입니다.', '["Must", "Will", "Can", "Should"]', '___ I borrow your pen?', 'en_bg_fb_135', 135, 10),
(1, CURRENT_TIMESTAMP, '규칙 등 의무를 나타내는 must가 적절합니다.', '["can", "must", "may", "will"]', 'You ___ stop at a red light.', 'en_bg_fb_136', 136, 10),
(3, CURRENT_TIMESTAMP, '미래 예측을 나타내는 will이 적절합니다.', '["can", "must", "should", "will"]', 'He ___ arrive soon.', 'en_bg_fb_137', 137, 10),
(0, CURRENT_TIMESTAMP, '원함을 나타내는 would like to 구문입니다.', '["would", "should", "could", "must"]', 'I ___ like to order now.', 'en_bg_fb_138', 138, 10),
(1, CURRENT_TIMESTAMP, '~하는 게 낫다(had better) 구문입니다.', '["have", "had", "has", "would"]', 'You ___ better go home.', 'en_bg_fb_139', 139, 10),
(2, CURRENT_TIMESTAMP, '강한 추측(~임에 틀림없다)의 must가 적절합니다.', '["can", "will", "must", "should"]', 'They ___ be tired after the trip.', 'en_bg_fb_140', 140, 10),

-- 141~160: 접속사
(0, CURRENT_TIMESTAMP, '순접을 나타내는 and(그리고)가 적절합니다.', '["and", "but", "or", "so"]', 'I like apples ___ bananas.', 'en_bg_fb_141', 141, 10),
(1, CURRENT_TIMESTAMP, '역접을 나타내는 but(그러나)이 적절합니다.', '["and", "but", "or", "so"]', 'It is small ___ beautiful.', 'en_bg_fb_142', 142, 10),
(2, CURRENT_TIMESTAMP, '선택을 나타내는 or(또는)가 적절합니다.', '["and", "but", "or", "so"]', 'Do you want tea ___ coffee?', 'en_bg_fb_143', 143, 10),
(3, CURRENT_TIMESTAMP, '결과를 나타내는 so(그래서)가 적절합니다.', '["and", "but", "or", "so"]', 'I was tired, ___ I went to bed early.', 'en_bg_fb_144', 144, 10),
(1, CURRENT_TIMESTAMP, '이유를 나타내는 because(~때문에)가 적절합니다.', '["so", "because", "but", "and"]', 'I stayed home ___ it rained.', 'en_bg_fb_145', 145, 10),
(2, CURRENT_TIMESTAMP, '역접 관계이므로 but이 적절합니다.', '["and", "or", "but", "so"]', 'He is rich, ___ he is not happy.', 'en_bg_fb_146', 146, 10),
(0, CURRENT_TIMESTAMP, '명령문, and ~ (그러면 ~할 것이다) 구문입니다.', '["and", "but", "or", "so"]', 'Study hard, ___ you will pass.', 'en_bg_fb_147', 147, 10),
(2, CURRENT_TIMESTAMP, '명령문, or ~ (그렇지 않으면 ~할 것이다) 구문입니다.', '["and", "but", "or", "so"]', 'Hurry up, ___ you will be late.', 'en_bg_fb_148', 148, 10),
(1, CURRENT_TIMESTAMP, '시간을 나타내는 When(~할 때)이 적절합니다.', '["If", "When", "Because", "But"]', '___ I was young, I liked toys.', 'en_bg_fb_149', 149, 10),
(0, CURRENT_TIMESTAMP, '조건을 나타내는 If(만약 ~라면)가 적절합니다.', '["If", "When", "Because", "But"]', '___ it rains, we will stay inside.', 'en_bg_fb_150', 150, 10),
(2, CURRENT_TIMESTAMP, '이유를 설명하므로 because가 적절합니다.', '["so", "but", "because", "or"]', 'I didn''t buy it ___ it was too expensive.', 'en_bg_fb_151', 151, 10),
(0, CURRENT_TIMESTAMP, '두 동사를 잇는 and가 적절합니다.', '["and", "but", "or", "so"]', 'She can read ___ write.', 'en_bg_fb_152', 152, 10),
(1, CURRENT_TIMESTAMP, '앞뒤 문맥이 반대이므로 but이 적절합니다.', '["and", "but", "or", "so"]', 'I am sorry, ___ I can''t help you.', 'en_bg_fb_153', 153, 10),
(3, CURRENT_TIMESTAMP, '명사절을 이끄는 접속사 that이 적절합니다.', '["if", "when", "because", "that"]', 'I think ___ he is honest.', 'en_bg_fb_154', 154, 10),
(2, CURRENT_TIMESTAMP, '~할 때(when)가 자연스럽습니다.', '["if", "because", "when", "but"]', 'I will call you ___ I arrive.', 'en_bg_fb_155', 155, 10),
(0, CURRENT_TIMESTAMP, '~하기 전에(before)가 자연스럽습니다.', '["before", "after", "when", "while"]', 'Wash your hands ___ you eat.', 'en_bg_fb_156', 156, 10),
(1, CURRENT_TIMESTAMP, '~한 후에(after)가 자연스럽습니다.', '["before", "after", "when", "while"]', 'You can go out ___ you finish your homework.', 'en_bg_fb_157', 157, 10),
(2, CURRENT_TIMESTAMP, '이유를 나타내는 as(~때문에)가 적절합니다.', '["so", "but", "as", "or"]', 'He walked slowly ___ he was tired.', 'en_bg_fb_158', 158, 10),
(3, CURRENT_TIMESTAMP, '결과를 나타내는 so(그래서)가 적절합니다.', '["and", "but", "or", "so"]', 'He was sick, ___ he didn''t go to school.', 'en_bg_fb_159', 159, 10),
(2, CURRENT_TIMESTAMP, 'A or B 선택 의문문입니다.', '["and", "but", "or", "so"]', 'Is it true ___ false?', 'en_bg_fb_160', 160, 10),

-- 161~180: 관사, 수량형용사, 비교 등
(1, CURRENT_TIMESTAMP, '모음 발음 앞이므로 an을 씁니다.', '["a", "an", "the", "some"]', 'I have ___ apple.', 'en_bg_fb_161', 161, 10),
(0, CURRENT_TIMESTAMP, '자음 발음 앞이므로 a를 씁니다.', '["a", "an", "the", "some"]', 'He is ___ teacher.', 'en_bg_fb_162', 162, 10),
(2, CURRENT_TIMESTAMP, '유일무이한 대상(sun) 앞에는 the를 씁니다.', '["a", "an", "the", "some"]', 'Look at ___ sun.', 'en_bg_fb_163', 163, 10),
(3, CURRENT_TIMESTAMP, '긍정문에서 약간의(some)가 적절합니다.', '["a", "an", "any", "some"]', 'I need ___ water.', 'en_bg_fb_164', 164, 10),
(2, CURRENT_TIMESTAMP, '의문문에서는 some 대신 any를 주로 씁니다.', '["a", "an", "any", "some"]', 'Do you have ___ questions?', 'en_bg_fb_165', 165, 10),
(0, CURRENT_TIMESTAMP, '셀 수 있는 복수명사 앞에는 many를 씁니다.', '["many", "much", "a lot", "some"]', 'How ___ apples do you have?', 'en_bg_fb_166', 166, 10),
(1, CURRENT_TIMESTAMP, '셀 수 없는 명사(money) 앞에는 much를 씁니다.', '["many", "much", "a few", "few"]', 'How ___ money do you need?', 'en_bg_fb_167', 167, 10),
(2, CURRENT_TIMESTAMP, '셀 수 없는 명사의 약간(a little)이 적절합니다.', '["a few", "few", "a little", "little"]', 'There is ___ milk in the glass.', 'en_bg_fb_168', 168, 10),
(0, CURRENT_TIMESTAMP, '셀 수 있는 명사의 약간(a few)이 적절합니다.', '["a few", "few", "a little", "little"]', 'I have ___ friends here.', 'en_bg_fb_169', 169, 10),
(3, CURRENT_TIMESTAMP, 'than이 있으므로 비교급 taller가 옵니다.', '["tall", "tallest", "more tall", "taller"]', 'She is ___ than me.', 'en_bg_fb_170', 170, 10),
(1, CURRENT_TIMESTAMP, 'the 뒤에 오며 셋 이상 비교이므로 최상급 best가 옵니다.', '["good", "best", "better", "well"]', 'This is the ___ book in the store.', 'en_bg_fb_171', 171, 10),
(2, CURRENT_TIMESTAMP, 'than 앞이므로 비교급 faster가 옵니다.', '["fast", "fastest", "faster", "more fast"]', 'He runs ___ than a horse.', 'en_bg_fb_172', 172, 10),
(1, CURRENT_TIMESTAMP, 'the 뒤이므로 최상급 tallest가 옵니다.', '["tall", "tallest", "taller", "most tall"]', 'That is the ___ building in the city.', 'en_bg_fb_173', 173, 10),
(0, CURRENT_TIMESTAMP, '긍정문이므로 something이 자연스럽습니다.', '["something", "anything", "nothing", "everything"]', 'I want ___ to drink.', 'en_bg_fb_174', 174, 10),
(1, CURRENT_TIMESTAMP, '의문문이므로 anybody가 자연스럽습니다.', '["somebody", "anybody", "nobody", "everybody"]', 'Is there ___ in the room?', 'en_bg_fb_175', 175, 10),
(2, CURRENT_TIMESTAMP, '대부분의(Most) 사람들이라는 뜻이 적절합니다.', '["Much", "Many", "Most", "More"]', '___ people like music.', 'en_bg_fb_176', 176, 10),
(3, CURRENT_TIMESTAMP, '매일(every day)이라는 단수 명사 수식어가 옵니다.', '["all", "some", "any", "every"]', 'I eat an egg ___ day.', 'en_bg_fb_177', 177, 10),
(0, CURRENT_TIMESTAMP, '각각의(Each)를 뜻하며 단수취급(has)과 어울립니다.', '["Each", "All", "Both", "Some"]', '___ of the boys has a bike.', 'en_bg_fb_178', 178, 10),
(1, CURRENT_TIMESTAMP, '형용사를 수식하는 부사 very(매우)가 적절합니다.', '["much", "very", "many", "a lot"]', 'She is ___ beautiful.', 'en_bg_fb_179', 179, 10),
(2, CURRENT_TIMESTAMP, '너무 ~해서 ~할 수 없다(too ~ to) 구문입니다.', '["so", "very", "too", "much"]', 'He is ___ tired to walk.', 'en_bg_fb_180', 180, 10),

-- 181~200: 의문사 및 기타 필수 구문
(0, CURRENT_TIMESTAMP, '무엇을 묻는 의문대명사 What이 적절합니다.', '["What", "Who", "Where", "When"]', '___ is your name?', 'en_bg_fb_181', 181, 10),
(2, CURRENT_TIMESTAMP, '장소를 묻는 의문부사 Where가 적절합니다.', '["What", "Who", "Where", "When"]', '___ are you from?', 'en_bg_fb_182', 182, 10),
(1, CURRENT_TIMESTAMP, '사람을 묻는 의문대명사 Who가 적절합니다.', '["What", "Who", "Where", "When"]', '___ is that man?', 'en_bg_fb_183', 183, 10),
(3, CURRENT_TIMESTAMP, '시간을 묻는 의문부사 When이 적절합니다.', '["What", "Who", "Where", "When"]', '___ is your birthday?', 'en_bg_fb_184', 184, 10),
(2, CURRENT_TIMESTAMP, '이유를 묻는 의문부사 Why가 적절합니다.', '["How", "When", "Why", "Where"]', '___ are you crying?', 'en_bg_fb_185', 185, 10),
(0, CURRENT_TIMESTAMP, '정도(나이)를 묻는 의문사 How가 적절합니다.', '["How", "What", "Who", "Why"]', '___ old are you?', 'en_bg_fb_186', 186, 10),
(1, CURRENT_TIMESTAMP, '누구의 것인지 묻는 Whose가 적절합니다.', '["Who", "Whose", "Whom", "What"]', '___ book is this?', 'en_bg_fb_187', 187, 10),
(0, CURRENT_TIMESTAMP, '방법/수단을 묻는 How가 적절합니다.', '["How", "What", "Why", "Where"]', '___ do you go to school?', 'en_bg_fb_188', 188, 10),
(3, CURRENT_TIMESTAMP, '선택을 묻는 의문사 Which가 적절합니다.', '["What", "Who", "Where", "Which"]', '___ one do you like, red or blue?', 'en_bg_fb_189', 189, 10),
(0, CURRENT_TIMESTAMP, '시간을 묻는 표현 What time ~? 입니다.', '["What", "How", "When", "Why"]', '___ time is it?', 'en_bg_fb_190', 190, 10),
(1, CURRENT_TIMESTAMP, '날씨를 묻는 표현 How is the weather ~? 입니다.', '["What", "How", "When", "Where"]', '___ is the weather today?', 'en_bg_fb_191', 191, 10),
(2, CURRENT_TIMESTAMP, '단수명사 앞이므로 There is 구문입니다.', '["are", "am", "is", "be"]', 'There ___ a book on the desk.', 'en_bg_fb_192', 192, 10),
(0, CURRENT_TIMESTAMP, '복수명사 앞이므로 There are 구문입니다.', '["are", "is", "am", "be"]', 'There ___ two apples on the table.', 'en_bg_fb_193', 193, 10),
(1, CURRENT_TIMESTAMP, '단수명사 의문문이므로 Is there ~? 구문입니다.', '["Are", "Is", "Am", "Be"]', '___ there a bank near here?', 'en_bg_fb_194', 194, 10),
(0, CURRENT_TIMESTAMP, 'Let''s 뒤에는 동사원형이 옵니다.', '["go", "goes", "went", "going"]', 'Let''s ___ to the park.', 'en_bg_fb_195', 195, 10),
(2, CURRENT_TIMESTAMP, '부정 명령문 Don''t 뒤에는 동사원형이 옵니다.', '["opened", "opens", "open", "opening"]', 'Don''t ___ the door.', 'en_bg_fb_196', 196, 10),
(3, CURRENT_TIMESTAMP, '명령문의 맨 앞에는 동사원형이 옵니다.', '["is", "am", "are", "be"]', 'Please ___ quiet.', 'en_bg_fb_197', 197, 10),
(0, CURRENT_TIMESTAMP, 'What a 혁 명! 형태의 감탄문입니다.', '["What", "How", "Which", "Who"]', '___ a beautiful flower!', 'en_bg_fb_198', 198, 10),
(1, CURRENT_TIMESTAMP, 'How 형/부 주 동! 형태의 감탄문입니다.', '["What", "How", "Why", "When"]', '___ fast he runs!', 'en_bg_fb_199', 199, 10),
(2, CURRENT_TIMESTAMP, 'Thank you for 명사(~에 대해 감사하다) 구문입니다.', '["to", "in", "for", "with"]', 'Thank you ___ your help.', 'en_bg_fb_200', 200, 10);