-- =====================================================
-- 과학 상식 퀴즈: ADVANCED (고급) - Part 1 [1~50]
-- 대학/전문 수준: 노벨상 주제, 최신 과학, 심화 물리/화학/생물
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_1', '2012년 CERN에서 발견된 입자는?', '["중성미자","힉스 보손","글루온","W 보손"]', 1, 'CERN의 LHC에서 힉스 보손을 실험적으로 확인(2012).', 1),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_2', '2015년 최초로 직접 관측된 것은?', '["암흑 물질","블랙홀 사진","중력파","반물질"]', 2, 'LIGO가 2015년 최초로 중력파를 직접 관측했습니다.', 2),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_3', '양자 얽힘(Quantum entanglement)이란?', '["양자가 뭉치는 현상","둘 이상의 입자가 상태를 공유하여 측정 시 상관관계를 보이는 현상","양자 터널링","양자 점프"]', 1, '얽힌 입자 중 하나를 측정하면 다른 입자의 상태가 즉시 결정됩니다.', 3),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_4', '양자 터널링이란?', '["입자가 사라지는 현상","입자가 고전적으로 넘을 수 없는 에너지 장벽을 통과하는 현상","파동의 반사","핵분열"]', 1, '양자역학적으로 입자가 포텐셜 장벽을 투과할 확률이 있습니다.', 4),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_5', '표준 모형(Standard Model)에서 힘을 매개하는 입자가 아닌 것은?', '["글루온","광자","W/Z 보손","전자"]', 3, '전자는 물질 입자(페르미온). 게이지 보손: 글루온, 광자, W/Z.', 5),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_6', 'CRISPR-Cas9 시스템의 가이드 RNA의 역할은?', '["DNA를 자르기","표적 DNA 서열을 인식하여 Cas9를 유도","단백질 합성","RNA 복제"]', 1, '가이드 RNA가 상보적 서열을 인식하여 Cas9 효소를 표적으로 안내.', 6),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_7', '초끈 이론(String theory)에서 기본 구성요소는?', '["점 입자","1차원 진동하는 끈","원자","분자"]', 1, '초끈 이론에서는 기본 입자가 진동하는 1차원 끈입니다.', 7),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_8', '컨센서스 의견에 따르면 우주의 나이는 약?', '["46억 년","100억 년","138억 년","200억 년"]', 2, '우주의 나이는 약 138억 년으로 추정됩니다.', 8),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_9', '암흑 에너지(Dark energy)란?', '["블랙홀의 에너지","우주 팽창을 가속시키는 미지의 에너지","암흑 물질의 에너지","태양 에너지"]', 1, '우주 가속 팽창의 원인으로 추정되는 미지의 에너지입니다.', 9),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_10', '우주의 구성 비율은 약?', '["물질 95%, 암흑 5%","보통 물질 68%, 암흑 물질 27%","보통 물질 5%, 암흑 물질 27%, 암흑 에너지 68%","보통 물질 50%, 암흑 50%"]', 2, '보통 물질 ~5%, 암흑 물질 ~27%, 암흑 에너지 ~68%.', 10),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_11', '슈뢰딩거의 고양이 실험이 설명하는 것은?', '["고양이 행동학","양자 중첩 상태의 역설","상대성 이론","열역학 법칙"]', 1, '관측 전 양자 시스템은 여러 상태의 중첩 상태에 있다는 역설.', 11),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_12', 'EPR 역설은 어떤 분야와 관련 있나요?', '["열역학","양자역학(양자 얽힘과 국소성)","유체역학","천체물리학"]', 1, '아인슈타인-포돌스키-로젠 역설은 양자 얽힘의 비국소성 문제.', 12),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_13', '벨의 부등식이 실험적으로 위배된 것은 무엇을 의미하나요?', '["양자역학이 틀렸다","국소 숨은 변수 이론이 불가능","상대성 이론이 틀렸다","중력파가 존재"]', 1, '벨의 부등식 위배는 양자 얽힘이 실재하며 국소적 숨은 변수 이론이 불가능함을 보여줍니다.', 13),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_14', '호킹 복사(Hawking radiation)란?', '["별의 복사","블랙홀이 양자 효과로 입자를 방출하는 현상","태양 복사","X선 복사"]', 1, '블랙홀 사건의 지평선 근처에서 양자 효과로 입자가 방출됩니다.', 14),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_15', '페르미 역설이란?', '["에너지 역설","외계 문명이 있을 법한데 증거가 없는 모순","시간 역설","양자 역설"]', 1, '우주의 크기와 나이를 고려하면 외계 문명이 있을 법하나 증거 부재.', 15),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_16', '초전도체의 마이스너 효과란?', '["전류 증가","초전도 상태에서 자기장을 완전히 밀어내는 현상","열전도 증가","빛을 반사"]', 1, '초전도체는 내부에서 자기장을 완전히 배척합니다(자기 부상).', 16),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_17', 'mRNA 백신의 원리는?', '["약화된 바이러스 주입","mRNA로 체내에서 항원 단백질을 합성하게 하여 면역 유도","DNA 변형","항체 직접 주사"]', 1, 'mRNA가 세포에서 스파이크 단백질 등 항원을 합성하게 유도합니다.', 17),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_18', '위상 물질(Topological material)이 주목받는 이유는?', '["저렴해서","전자의 흐름이 불순물에 의해 산란되지 않아 양자 컴퓨팅에 활용 가능","색이 예뻐서","가벼워서"]', 1, '위상 보호 상태 덕분에 결함에 강건한 전자 전달이 가능합니다.', 18),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_19', '카시미르 효과란?', '["중력 효과","진공에 놓인 두 도체판 사이에 양자 요동으로 힘이 발생","자기장 효과","음향 효과"]', 1, '양자 진공 요동에 의해 두 도체판 사이에 인력이 작용합니다.', 19),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_20', '보스-아인슈타인 응축(BEC)이란?', '["고온 플라스마","초저온에서 보손들이 같은 양자 상태로 붕괴하는 물질 상태","화학 반응","핵반응"]', 1, '절대 영도 근처에서 보손이 동일 양자 상태를 점유하는 물질의 제5상태.', 20),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_21', '광촉매란?', '["빛으로 전기 생산","빛에 의해 활성화되어 화학 반응을 촉진하는 물질","광합성","레이저"]', 1, 'TiO₂ 등 광촉매는 빛(UV)을 받아 화학 반응을 촉진합니다.', 21),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_22', '양자 컴퓨터에서 큐비트(Qubit)의 특징은?', '["0 또는 1만 가능","0과 1의 중첩 상태 가능","10진법 사용","아날로그 신호"]', 1, '큐비트는 0과 1을 동시에 가질 수 있어(중첩) 병렬 처리가 가능.', 22),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_23', '해양 산성화의 원인은?', '["소금 증가","대기 CO₂가 해수에 녹아 탄산 형성","해류 변화","온도 상승만"]', 1, 'CO₂ + H₂O → H₂CO₃(탄산)로 해양 pH가 낮아집니다.', 23),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_24', '페로브스카이트 태양전지의 장점은?', '["무거움","제조 비용이 낮고 효율 향상이 빠름","큰 면적 불가","독성 없음"]', 1, '페로브스카이트 태양전지는 저비용 고효율로 주목받고 있습니다.', 24),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_25', '일반 상대성 이론에서 중력이란?', '["두 물체 사이의 힘","시공간의 휘어짐","전자기력의 일종","양자 효과"]', 1, '질량이 시공간을 휘게 하고, 이것이 중력으로 나타납니다.', 25),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_26', '특수 상대성 이론의 결과가 아닌 것은?', '["시간 팽창","길이 수축","질량-에너지 등가","중력 렌즈"]', 3, '중력 렌즈는 일반 상대성 이론의 결과입니다.', 26),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_27', '중력 렌즈 효과란?', '["렌즈로 중력 측정","거대 질량이 시공간을 휘어 뒤의 빛을 굴절시키는 현상","중력이 약해지는 것","빛이 사라지는 것"]', 1, '무거운 천체 주변의 시공간 왜곡이 빛을 굴절시킵니다.', 27),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_28', '후성유전학(Epigenetics)이란?', '["유전자 서열 변화를 연구","DNA 서열 변화 없이 유전자 발현이 조절되는 것을 연구","진화론의 일부","유전자 복제"]', 1, 'DNA 메틸화 등으로 유전자 발현이 조절되는 현상을 연구합니다.', 28),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_29', '텔로미어(Telomere)의 역할은?', '["유전자 발현","염색체 끝을 보호(세포 노화와 관련)","단백질 합성","RNA 생성"]', 1, '텔로미어는 세포 분열 시 짧아지며 세포 노화/수명과 관련됩니다.', 29),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_30', '텔로머라제(Telomerase)란?', '["텔로미어를 짧게 하는 효소","텔로미어를 연장하는 효소","DNA를 분해하는 효소","RNA를 생성하는 효소"]', 1, '텔로머라제는 텔로미어를 연장하여 세포 수명을 늘릴 수 있습니다.', 30),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_31', '오토파지(Autophagy)란?', '["세포가 스스로 소화","세포가 자체 구성 요소를 분해·재활용하는 과정","세포 분열","세포 사멸"]', 1, '요시노리 오스미가 2016년 노벨 생리의학상. 세포 내 불필요한 구성 성분 제거.', 31),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_32', '유도만능줄기세포(iPSC)를 만든 과학자는?', '["야마나카 신야","왓슨","멘델","파스퇴르"]', 0, '야마나카 신야가 체세포를 줄기세포로 역분화하는 데 성공(2006, 노벨상 2012).', 32),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_33', '모호로비치치 불연속면이란?', '["대기층 경계","지각과 맨틀의 경계(모호면)","맨틀과 핵의 경계","외핵과 내핵 경계"]', 1, '모호면은 지진파 속도 변화로 확인되는 지각-맨틀 경계입니다.', 33),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_34', '구텐베르크 불연속면이란?', '["지각과 맨틀 경계","맨틀과 외핵의 경계","외핵과 내핵 경계","대기권 경계"]', 1, '지진파 S파가 통과하지 못하여 외핵이 액체임을 알 수 있습니다.', 34),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_35', '킵 손, 라이너 바이스, 배리 배리시가 2017년 노벨 물리학상을 받은 이유는?', '["힉스 보손 발견","중력파 직접 검출(LIGO)","블랙홀 사진","양자 컴퓨터"]', 1, 'LIGO에 의한 중력파 직접 관측 공로.', 35),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_36', '카탈라아제 효소의 역할은?', '["DNA 복제","과산화수소(H₂O₂)를 물과 산소로 분해","단백질 합성","지방 분해"]', 1, '카탈라아제는 유해한 H₂O₂를 빠르게 분해합니다.', 36),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_37', '프리온(Prion)이란?', '["바이러스의 일종","비정상적으로 접힌 단백질로 전염성 질병 유발","세균","곰팡이"]', 1, '프리온은 정상 단백질을 비정상 형태로 변환시켜 광우병 등을 유발.', 37),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_38', '초대칭(Supersymmetry, SUSY) 이론이란?', '["대칭이 없다","모든 보손에 페르미온 짝이, 페르미온에 보손 짝이 존재한다는 이론","거울 대칭","결정 대칭"]', 1, '초대칭은 보손-페르미온 쌍을 예측하는 확장된 표준 모형입니다.', 38),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_39', '체렌코프 복사란?', '["빛의 반사","하전 입자가 매질 내 빛의 속도보다 빠르게 이동할 때 방출되는 전자기파","핵반응","열복사"]', 1, '원자로의 푸른 빛이 체렌코프 복사의 대표적 예입니다.', 39),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_40', '라만 산란이란?', '["빛의 반사","물질과 상호작용 시 빛의 파장이 변하는 비탄성 산란","빛의 흡수","빛의 간섭"]', 1, '라만 산란은 분자의 진동 에너지와 교환하여 파장이 변하는 현상.', 40),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_41', '중성자별의 밀도는 약?', '["물의 밀도와 같음","10배","10⁸ 배","10¹⁴ 배 이상"]', 3, '중성자별의 밀도는 약 10¹⁴~10¹⁵ g/cm³로 극도로 높습니다.', 41),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_42', '펄서(Pulsar)란?', '["밝은 별","빠르게 회전하며 전파를 방출하는 중성자별","퀘이사","행성"]', 1, '펄서는 자전하며 규칙적 전파를 방출하는 중성자별입니다.', 42),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_43', '퀘이사(Quasar)란?', '["작은 별","초거대 블랙홀이 물질을 빨아들이며 엄청난 에너지를 방출하는 활동성 은하핵","혜성","소행성"]', 1, '퀘이사는 우주에서 가장 밝은 천체 중 하나입니다.', 43),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_44', '양자 색역학(QCD)에서 강한 핵력을 매개하는 입자는?', '["광자","W 보손","글루온","히곡스 보손"]', 2, '글루온이 쿼크 사이의 강한 핵력(색힘)을 매개합니다.', 44),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_45', '반물질(Antimatter)이란?', '["어두운 물질","물질과 같은 질량이지만 반대 전하를 가진 입자","암흑 물질","가상 입자"]', 1, '양전자는 전자의 반물질. 물질과 만나면 쌍소멸하며 에너지 방출.', 45),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_46', '유전체학(Genomics)과 전사체학(Transcriptomics)의 차이는?', '["같은 것","유전체학=DNA 연구, 전사체학=RNA 발현 연구","유전체학=RNA, 전사체학=DNA","차이 없음"]', 1, '유전체학은 DNA 전체를, 전사체학은 mRNA 발현 패턴을 연구합니다.', 46),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_47', '메타물질(Metamaterial)이란?', '["금속 물질","자연에 없는 전자기적 성질을 가지도록 인공 설계된 물질","유기물","반도체"]', 1, '메타물질은 음의 굴절률 등 자연에 없는 성질을 구현할 수 있습니다.', 47),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_48', '플랑크 상수(h)의 물리적 의미는?', '["중력 상수","양자역학에서 에너지 양자화의 기본 단위","빛의 속도","전자의 질량"]', 1, 'E=hf에서 에너지는 플랑크 상수의 정수배로 양자화됩니다.', 48),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_49', '게이지 대칭이란?', '["물질의 대칭","물리 법칙이 특정 변환 하에서 불변인 것","거울 대칭","결정 대칭"]', 1, '게이지 대칭은 표준 모형의 기초가 되는 핵심 원리입니다.', 49),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='science'), 'sc_g_50', '파울리 배타 원리란?', '["같은 양자 상태에 두 개의 같은 페르미온이 존재할 수 없다","보손은 같은 상태 불가","에너지 보존","질량 보존"]', 0, '파울리 배타 원리 덕분에 전자는 에너지 준위를 순서대로 채웁니다.', 50)
ON CONFLICT (question_id) DO NOTHING;
