-- =====================================================
-- 일본어 퀴즈 시드: INTERMEDIATE (중급) - Part 1 [1~50]
-- 복합 문법, 가능형, 수동태, 경험, 경어, 한자 읽기
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_1', '"식사를 하고 있습니다" 진행형은?', '["타베마스","타베테 이마스","타베마시타","타베라레마스"]', 1, '진행형은 "~테 이루(~ている)"입니다.', 1),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_2', '"갈 수 있다" 가능형은?', '["이케루","이카루","이키타이","이코오"]', 0, '"이케루(行ける)"입니다.', 2),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_3', '수동태: "혼나다" (오코루)', '["오코루","오코라레루","오코나우","오코세루"]', 1, '"오코라레루(怒られる)"입니다.', 3),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_4', '"~한 적이 있다" 경험 표현은?', '["~타 코토가 아루","~테 이루","~타리 스루","~테 아루"]', 0, '"~たことがある"입니다.', 4),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_5', '"공부"의 한자는?', '["勉強","勉教","勤強","勤教"]', 0, '공부는 "勉強(べんきょう)"입니다.', 5),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_6', '"전화"는?', '["덴와","덴샤","덴키","덴치"]', 0, '"덴와(電話)"입니다.', 6),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_7', '"전철"은?', '["덴와","덴샤","덴키","덴치"]', 1, '"덴샤(電車)"입니다.', 7),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_8', '존경어: "먹다"의 존경어는?', '["메시아가루","이타다쿠","모스","오루"]', 0, '"메시아가루(召し上がる)"입니다.', 8),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_9', '겸양어: "먹다"의 겸양어는?', '["메시아가루","이타다쿠","하이켄스루","우카가우"]', 1, '"이타다쿠(いただく)"입니다.', 9),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_10', '"~해야 한다" (의무)는?', '["~테와 이케나이","~나쿠테와 나라나이","~테모 이이","~타라 이이"]', 1, '"~나쿠테와 나라나이"입니다.', 10),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_11', '"日本"의 읽기는?', '["니혼","닛폰","둘 다 맞음","니치혼"]', 2, '두 가지 읽기 모두 맞습니다.', 11),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_12', '"먹을 수 있다" 가능형은?', '["타베레루","타베라레루","둘 다 맞음","타베루"]', 2, '문법적으로 "타베라레루", 구어에서 "타베레루" 둘 다 사용합니다.', 12),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_13', '사역형: "가게 하다" (이쿠)', '["이카세루","이카레루","이카세라레루","이케루"]', 0, '"이카세루(行かせる)"입니다.', 13),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_14', '"~하면" (가정형)은?', '["~바","~타라","~나라","모두 가정 표현"]', 3, '~ば, ~たら, ~なら 모두 가정 표현입니다.', 14),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_15', '"경험"은 일본어로?', '["게이겐","케이케","타이겐","케이켄"]', 3, '경험은 "케이켄(経験)"입니다.', 15),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_16', '"회사원"은?', '["카이샤인","교인","이샤","벤고시"]', 0, '"카이샤인(会社員)"입니다.', 16),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_17', '"약속"은?', '["야쿠소쿠","요야쿠","케이야쿠","셋토쿠"]', 0, '"야쿠소쿠(約束)"입니다.', 17),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_18', '"예약"은?', '["야쿠소쿠","요야쿠","케이야쿠","셋토쿠"]', 1, '"요야쿠(予約)"입니다.', 18),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_19', '"계약"은?', '["야쿠소쿠","요야쿠","케이야쿠","셋토쿠"]', 2, '"케이야쿠(契約)"입니다.', 19),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_20', '"설득"은?', '["야쿠소쿠","요야쿠","케이야쿠","셋토쿠"]', 3, '"셋토쿠(説得)"입니다.', 20),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_21', '"~해도 되다" (허가)는?', '["~테모 이이","~테와 이케나이","~나케레바","~타라 다메"]', 0, '"~テモいい"입니다.', 21),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_22', '"~하면 안 된다" (금지)는?', '["~테모 이이","~테와 이케나이","~나케레바","~셔도 이이"]', 1, '"~テハいけない"입니다.', 22),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_23', '"안전"은?', '["안젠","키켄","헤이와","센소"]', 0, '"안젠(安全)"입니다.', 23),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_24', '"위험"은?', '["안젠","키켄","헤이와","센소"]', 1, '"키켄(危険)"입니다.', 24),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_25', '"交通"의 읽기는?', '["코츠","코우츠우","코우쓰","코토오리"]', 1, '"코우츠우(こうつう)"입니다.', 25),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_26', '"出発"의 읽기는?', '["데하츠","슈츠하츠","슛파츠","데파츠"]', 2, '"슛파츠(しゅっぱつ)"입니다.', 26),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_27', '"到着"의 읽기는?', '["토차쿠","도차쿠","토우차쿠","도우차쿠"]', 2, '"토우차쿠(とうちゃく)"입니다.', 27),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_28', '"趣味"의 읽기는?', '["슈미","취미","오모무키","키요미"]', 0, '"슈미(しゅみ)"입니다.', 28),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_29', '"残念"의 의미는?', '["남은 해","유감/아쉽다","부족하다","남겨두다"]', 1, '"잔넨(残念)" = 유감, 아쉽다입니다.', 29),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_30', '"~하려고 하다" (의도)는?', '["~오우 토 스루","~츠모리다","~요테다","~하즈다"]', 0, '"~ようとする"입니다.', 30),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_31', '"~할 예정이다"는?', '["~오우 토 스루","~츠모리다","~요테다","~하즈다"]', 2, '"~予定だ"입니다.', 31),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_32', '"~할 것이다" (확신)는?', '["~카모시레나이","~다로","~니치가이나이","~라시이"]', 2, '"~に違いない"입니다.', 32),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_33', '"~일지도 모르다"는?', '["~카모시레나이","~다로","~니치가이나이","~라시이"]', 0, '"~かもしれない"입니다.', 33),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_34', '존경어: "가다"의 존경어는?', '["이랏샤루","마이루","오이데니나루","이카레루"]', 0, '"이랏샤루(いらっしゃる)"입니다.', 34),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_35', '겸양어: "가다"의 겸양어는?', '["이랏샤루","마이루","오이데니나루","이카레루"]', 1, '"마이루(参る)"입니다.', 35),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_36', '"自然"의 읽기는?', '["시젠","지넨","자넨","지젠"]', 0, '"시젠(しぜん)"입니다.', 36),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_37', '"健康"의 읽기는?', '["켄코","켄코우","겐코","겐코우"]', 1, '"켄코우(けんこう)"입니다.', 37),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_38', '"失礼"의 의미는?', '["실패","실례","실망","실수"]', 1, '"시츠레이(失礼)" = 실례입니다.', 38),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_39', '"紹介"의 읽기는?', '["쇼카이","조카이","쇼게","죠카이"]', 0, '"쇼카이(しょうかい)"입니다.', 39),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_40', '"~하는 동안"은?', '["~아이다니","~우치니","둘 다 맞음","~나가라"]', 2, '"~間に"와 "~うちに" 둘 다 사용합니다.', 40),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_41', '"~하면서" (동시 동작)는?', '["~아이다니","~우치니","~테","~나가라"]', 3, '"~ながら"입니다.', 41),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_42', '"환경"은?', '["칸쿄","간쿄","칸고","간고"]', 0, '"칸쿄(環境)"입니다.', 42),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_43', '"경제"는?', '["게자이","게이자이","케자이","케이자이"]', 3, '"케이자이(経済)"입니다.', 43),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_44', '"교육"은?', '["교이쿠","쿄이쿠","교우이쿠","쿄우이쿠"]', 3, '"쿄우이쿠(教育)"입니다.', 44),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_45', '"문화"는?', '["몬카","붕카","분카","문카"]', 2, '"분카(文化)"입니다.', 45),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_46', '"社会"의 읽기는?', '["샤카이","샤가이","시야카이","조카이"]', 0, '"샤카이(しゃかい)"입니다.', 46),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_47', '"政治"의 읽기는?', '["세이지","세이치","쇼치","쇼지"]', 0, '"세이지(せいじ)"입니다.', 47),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_48', '"~에 의하면" (전달)은?', '["~니 요루토","~니 요레바","둘 다 맞음","~니 따르면"]', 2, '"~によると"와 "~によれば" 둘 다 가능합니다.', 48),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_49', '"~인 것 같다" (추측)는?', '["~요우다","~미타이다","둘 다 맞음","~라시이"]', 2, '"~ようだ"와 "~みたいだ" 둘 다 추측입니다.', 49),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_50', '"~해 버리다" (완료/유감)는?', '["~테 시마우","~테 오쿠","~테 미루","~테 아루"]', 0, '"~てしまう"입니다.', 50)
ON CONFLICT (question_id) DO NOTHING;
