-- =====================================================
-- 일본어 퀴즈 시드: INTERMEDIATE (중급) - Part 2 [51~100]
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_51', '"~해 두다" (준비)는?', '["~테 시마우","~테 오쿠","~테 미루","~테 아루"]', 1, '"~ておく"입니다.', 51),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_52', '"~해 보다" (시도)는?', '["~테 시마우","~테 오쿠","~테 미루","~테 아루"]', 2, '"~てみる"입니다.', 52),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_53', '"練習"의 읽기는?', '["렌슈","네슈","렌슈우","렌지"]', 2, '"렌슈우(れんしゅう)"입니다.', 53),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_54', '"準備"의 읽기는?', '["준비","쥰비","슌비","순비"]', 1, '"쥰비(じゅんび)"입니다.', 54),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_55', '"卒業"의 읽기는?', '["소츠교","소츠교우","졸교","쿄츠교"]', 1, '"소츠교우(そつぎょう)"입니다.', 55),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_56', '"受験"의 읽기는?', '["주켄","우켄","주켄","쥬켄"]', 3, '"쥬켄(じゅけん)"입니다.', 56),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_57', '"~하기 위해" (목적)는?', '["~타메니","~요우니","둘 다 목적 표현","~카라"]', 2, '"~ために"와 "~ように" 둘 다 목적을 나타냅니다.', 57),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_58', '"연락"은?', '["렌라쿠","렌가쿠","겐가쿠","겐라쿠"]', 0, '"렌라쿠(連絡)"입니다.', 58),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_59', '"問題"의 읽기는?', '["몬다이","도이","토이","몬데"]', 0, '"몬다이(もんだい)"입니다.', 59),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_60', '"質問"의 읽기는?', '["시츠몬","지몬","시몬","지츠몬"]', 0, '"시츠몬(しつもん)"입니다.', 60),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_61', '"説明"의 읽기는?', '["세츠메","세츠메이","셋메이","셋메"]', 2, '"셋메이(せつめい)"입니다.', 61),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_62', '"注意"의 의미는?', '["주사","주의/조심","주문","주목"]', 1, '"추우이(注意)" = 주의/조심입니다.', 62),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_63', '"相談"의 의미는?', '["상담","상대","상태","상상"]', 0, '"소우단(相談)" = 상담입니다.', 63),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_64', '"決定"의 읽기는?', '["케테이","겟테이","결정","케테"]', 1, '"겟테이(けってい)"입니다.', 64),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_65', '"最近"의 읽기는?', '["사이킨","사이곤","모킨","사이긴"]', 0, '"사이킨(さいきん)"입니다.', 65),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_66', '"将来"의 읽기는?', '["쇼라이","소라이","쇼래","장래"]', 0, '"쇼라이(しょうらい)"입니다.', 66),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_67', '"旅行"의 읽기는?', '["료코","료코우","리코우","료고우"]', 1, '"료코우(りょこう)"입니다.', 67),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_68', '"~하지 않을 수 없다"는?', '["~자루오에나이","~나이데이라레나이","둘 다 맞음","~테와 이케나이"]', 0, '"~ざるを得ない"입니다.', 68),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_69', '"関係"의 읽기는?', '["칸게","간게","칸케이","간게이"]', 2, '"칸게이(かんけい)"입니다. 실제로는 칸케이입니다.', 69),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_70', '"影響"의 읽기는?', '["에이쿄","에이쿄우","카게쿄우","카게히비키"]', 1, '"에이쿄우(えいきょう)"입니다.', 70),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_71', '"必要"의 읽기는?', '["히츠요","히츠요우","삐츠요","비요"]', 1, '"히츠요우(ひつよう)"입니다.', 71),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_72', '"特別"의 읽기는?', '["토쿠베츠","토쿠벳츠","독특","도쿠베"]', 0, '"토쿠베츠(とくべつ)"입니다.', 72),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_73', '"~에 대해서"는?', '["~니 츠이테","~니 타이시테","~니 요테","~니 토테"]', 0, '"~について"입니다.', 73),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_74', '"~에 비해서"는?', '["~니 츠이테","~니 쿠라베테","~니 칸시테","~니 토테"]', 1, '"~に比べて"입니다.', 74),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_75', '"以上"의 의미는?', '["이하","이상","이전","이후"]', 1, '"이죠우(以上)" = 이상입니다.', 75),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_76', '"以下"의 의미는?', '["이하","이상","이전","이후"]', 0, '"이카(以下)" = 이하입니다.', 76),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_77', '"増える"(후에루)의 의미는?', '["줄다","늘다","변하다","바뀌다"]', 1, '"후에루(増える)" = 늘다입니다.', 77),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_78', '"減る"(헤루)의 의미는?', '["줄다","늘다","변하다","바뀌다"]', 0, '"헤루(減る)" = 줄다입니다.', 78),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_79', '"比較"의 읽기는?', '["히카쿠","히카","비쿄","비가쿠"]', 0, '"히카쿠(ひかく)"입니다.', 79),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_80', '"原因"의 읽기는?', '["겐인","겐닌","겐잉","겐잉"]', 0, '"겐인(げんいん)"입니다.', 80),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_81', '"結果"의 읽기는?', '["겟카","켓카","게카","게쓰카"]', 1, '"켓카(けっか)"입니다.', 81),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_82', '"目的"의 읽기는?', '["모쿠테키","모쿠데키","메테키","모쿠교"]', 0, '"모쿠테키(もくてき)"입니다.', 82),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_83', '"方法"의 읽기는?', '["호호","호우호우","가타호","호우보우"]', 1, '"호우호우(ほうほう)"입니다.', 83),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_84', '"状態"의 읽기는?', '["조타이","죠타이","죠우타이","조우다이"]', 2, '"죠우타이(じょうたい)"입니다.', 84),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_85', '"成功"의 읽기는?', '["세코","세이코","세이코우","세코우"]', 2, '"세이코우(せいこう)"입니다.', 85),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_86', '"失敗"의 읽기는?', '["지빠이","시빠이","싯파이","시파이"]', 2, '"싯파이(しっぱい)"입니다.', 86),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_87', '"참가하다"는?', '["산카스루","산포스루","켄가쿠스루","호몬스루"]', 0, '"산카스루(参加する)"입니다.', 87),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_88', '"방문하다"는?', '["산카스루","산포스루","켄가쿠스루","호몬스루"]', 3, '"호몬스루(訪問する)"입니다.', 88),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_89', '"見学"의 의미는?', '["시합","견학","감상","감독"]', 1, '"켄가쿠(見学)" = 견학입니다.', 89),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_90', '"賛成"의 의미는?', '["찬성","반대","중립","무관"]', 0, '"산세이(賛成)" = 찬성입니다.', 90),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_91', '"反対"의 읽기는?', '["한다이","한타이","반타이","반다이"]', 1, '"한타이(はんたい)"입니다.', 91),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_92', '"意見"의 읽기는?', '["이겐","이켄","의켄","이견"]', 1, '"이켄(いけん)"입니다.', 92),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_93', '"~따라" (원인)은?', '["~세이데","~오카게데","둘 다 원인 표현","~카라"]', 2, '"~せいで"(나쁜 원인)와 "~おかげで"(좋은 원인) 둘 다 원인 표현입니다.', 93),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_94', '"確認"의 읽기는?', '["카쿠닌","카닌","카쿠인","가쿠닌"]', 0, '"카쿠닌(かくにん)"입니다.', 94),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_95', '"提出"의 읽기는?', '["테슈츠","테이슈츠","데슈츠","테이데"]', 1, '"테이슈츠(ていしゅつ)"입니다.', 95),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_96', '"完成"의 읽기는?', '["칸세이","간세이","칸조","완성"]', 0, '"칸세이(かんせい)"입니다.', 96),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_97', '"印象"의 읽기는?', '["인쇼","인죠","인쇼우","인조우"]', 2, '"인쇼우(いんしょう)"입니다.', 97),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_98', '"感想"의 읽기는?', '["칸소","칸소우","간소우","간소"]', 1, '"칸소우(かんそう)"입니다.', 98),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_99', '"~할수록 ~하다"는?', '["~바 ~호도","~타라 ~호도","~나라 ~호도","~토 ~호도"]', 0, '"~ば~ほど"입니다.', 99),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='japanese'), 'jp_j_100', '"~해야 할지 모르겠다"는?', '["~타라 이이카 와카라나이","~바 이이카 마요우","둘 다 맞음","~바 도우카"]', 0, '"~たらいいか分からない"입니다.', 100)
ON CONFLICT (question_id) DO NOTHING;
