-- =====================================================
-- 과학 상식 퀴즈: BEGINNER (초급) - Part 1 [1~50]
-- 초등~중등 수준 물리, 화학, 생물, 지구과학
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_1', '원자를 구성하는 입자가 아닌 것은?', '["양성자","중성자","전자","광자"]', 3, '원자는 양성자, 중성자, 전자로 구성됩니다.', 1),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_2', '산소의 원소 기호는?', '["O","Ox","Os","On"]', 0, '산소의 원소 기호는 O입니다.', 2),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_3', '금(Gold)의 원소 기호는?', '["Go","Gd","Au","Ag"]', 2, '금의 원소 기호는 Au(라틴어 Aurum)입니다.', 3),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_4', '세포의 유전 정보를 담고 있는 것은?', '["미토콘드리아","리보솜","DNA","세포막"]', 2, 'DNA(디옥시리보핵산)가 유전 정보를 담고 있습니다.', 4),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_5', '광합성에 필요한 것이 아닌 것은?', '["빛","물","이산화탄소","산소"]', 3, '산소는 광합성의 부산물(결과물)이지 재료가 아닙니다.', 5),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_6', '뉴턴의 운동 제1법칙은?', '["가속도 법칙","관성의 법칙","작용-반작용 법칙","중력 법칙"]', 1, '관성의 법칙: 외부 힘이 없으면 물체는 현재 상태를 유지합니다.', 6),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_7', '뉴턴의 운동 제3법칙은?', '["관성의 법칙","가속도 법칙","작용-반작용 법칙","만유인력 법칙"]', 2, '모든 작용에는 크기가 같고 방향이 반대인 반작용이 존재합니다.', 7),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_8', 'pH 7은 무엇을 의미하나요?', '["강산성","약산성","중성","염기성"]', 2, 'pH 7은 중성을 나타냅니다.', 8),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_9', '식초는 산성인가요 염기성인가요?', '["산성","중성","염기성","알 수 없음"]', 0, '식초에는 아세트산이 포함되어 산성입니다.', 9),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_10', '비누물은 산성인가요 염기성인가요?', '["산성","중성","염기성","알 수 없음"]', 2, '비누물은 약한 염기성입니다.', 10),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_11', '지구의 대기층 중 우리가 사는 곳은?', '["성층권","대류권","중간권","열권"]', 1, '대류권은 지표~약 12km 높이로 날씨가 발생합니다.', 11),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_12', '오존층은 어디에 위치하나요?', '["대류권","성층권","중간권","열권"]', 1, '오존층은 성층권(약 20~30km 높이)에 위치합니다.', 12),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_13', '화석 연료에 해당하지 않는 것은?', '["석탄","석유","천연가스","태양에너지"]', 3, '태양에너지는 재생 에너지입니다.', 13),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_14', '소리의 단위는?', '["볼트(V)","데시벨(dB)","와트(W)","헤르츠(Hz)"]', 1, '소리의 크기(세기)는 데시벨(dB)로 측정합니다.', 14),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_15', '진동수(주파수)의 단위는?', '["볼트(V)","데시벨(dB)","와트(W)","헤르츠(Hz)"]', 3, '진동수(주파수)의 단위는 헤르츠(Hz)입니다.', 15),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_16', '포유류의 특징이 아닌 것은?', '["젖으로 새끼를 기름","폐로 호흡","알을 낳아 번식","체온이 일정"]', 2, '대부분의 포유류는 새끼를 낳습니다(단공류 제외).', 16),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_17', '식물 세포에만 있는 것은?', '["핵","미토콘드리아","세포벽","리보솜"]', 2, '세포벽은 식물 세포에만 있습니다.', 17),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_18', '전류의 단위는?', '["볼트(V)","암페어(A)","옴(Ω)","와트(W)"]', 1, '전류의 단위는 암페어(A)입니다.', 18),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_19', '전압의 단위는?', '["볼트(V)","암페어(A)","옴(Ω)","와트(W)"]', 0, '전압의 단위는 볼트(V)입니다.', 19),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_20', '저항의 단위는?', '["볼트(V)","암페어(A)","옴(Ω)","와트(W)"]', 2, '저항의 단위는 옴(Ω)입니다.', 20),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_21', '속력의 공식은?', '["거리 × 시간","거리 ÷ 시간","시간 ÷ 거리","거리 + 시간"]', 1, '속력 = 거리 / 시간입니다.', 21),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_22', '밀도의 공식은?', '["질량 × 부피","질량 ÷ 부피","부피 ÷ 질량","질량 + 부피"]', 1, '밀도 = 질량 / 부피입니다.', 22),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_23', '소화기관의 순서로 맞는 것은?', '["입→위→식도→소장→대장","입→식도→위→소장→대장","입→소장→위→식도→대장","식도→입→위→대장→소장"]', 1, '입→식도→위→소장→대장이 올바른 순서입니다.', 23),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_24', '혈관의 종류가 아닌 것은?', '["동맥","정맥","모세혈관","신경관"]', 3, '혈관에는 동맥, 정맥, 모세혈관이 있습니다.', 24),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_25', '이산화탄소가 많아지면 발생하는 환경 문제는?', '["오존층 파괴","지구 온난화","산성비","방사능 오염"]', 1, 'CO₂는 대표적인 온실가스로 지구 온난화를 유발합니다.', 25),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_26', '전자기파가 아닌 것은?', '["빛","X선","라디오파","초음파"]', 3, '초음파는 음파(기계파)이고 전자기파가 아닙니다.', 26),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_27', '태양 에너지는 어떤 과정으로 만들어지나요?', '["핵분열","핵융합","연소","화학 반응"]', 1, '태양은 수소 핵융합 반응으로 에너지를 생성합니다.', 27),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_28', '지진의 세기를 나타내는 단위는?', '["데시벨","칼로리","리히터(규모)","볼트"]', 2, '지진의 규모는 리히터 규모로 측정합니다.', 28),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_29', '달의 모양이 변하는 이유는?', '["달이 커졌다 작아져서","지구의 그림자 때문","태양-지구-달의 위치 관계 변화","구름에 가려서"]', 2, '달의 위상 변화는 태양-지구-달의 상대적 위치에 의한 것입니다.', 29),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_30', '물의 순환 과정이 아닌 것은?', '["증발","응결","강수","핵분열"]', 3, '물의 순환: 증발→응결→강수→유출→다시 증발.', 30),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_31', '백혈구의 주된 역할은?', '["산소 운반","면역(병원체 제거)","혈액 응고","영양소 운반"]', 1, '백혈구는 면역을 담당해 병원체를 제거합니다.', 31),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_32', '혈소판의 주된 역할은?', '["산소 운반","면역","혈액 응고","호르몬 운반"]', 2, '혈소판은 상처 부위에서 혈액 응고를 돕습니다.', 32),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_33', '광년(Light-year)은 무엇의 단위인가요?', '["시간","질량","거리","속도"]', 2, '광년은 빛이 1년간 이동하는 거리 단위입니다.', 33),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_34', '나트륨(Na)과 염소(Cl)가 결합하면?', '["물","소금(NaCl)","설탕","식초"]', 1, 'Na + Cl → NaCl(소금, 염화나트륨)입니다.', 34),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_35', '지구의 내부 구조 순서(바깥→안쪽)는?', '["지각→맨틀→외핵→내핵","맨틀→지각→내핵→외핵","내핵→외핵→맨틀→지각","지각→외핵→맨틀→내핵"]', 0, '지각→맨틀→외핵→내핵 순서입니다.', 35),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_36', '소장의 주된 역할은?', '["음식 저장","영양소 흡수","수분 흡수","소화액 분비만"]', 1, '소장은 영양소의 대부분을 흡수합니다.', 36),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_37', '대장의 주된 역할은?', '["영양소 흡수","수분 흡수","단백질 소화","지방 분해"]', 1, '대장은 남은 수분을 흡수하고 대변을 형성합니다.', 37),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_38', '힘의 단위는?', '["줄(J)","뉴턴(N)","와트(W)","파스칼(Pa)"]', 1, '힘의 단위는 뉴턴(N)입니다.', 38),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_39', '에너지의 단위는?', '["줄(J)","뉴턴(N)","와트(W)","파스칼(Pa)"]', 0, '에너지의 단위는 줄(J)입니다.', 39),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_40', '전력(파워)의 단위는?', '["줄(J)","뉴턴(N)","와트(W)","파스칼(Pa)"]', 2, '전력(일률)의 단위는 와트(W)입니다.', 40),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_41', '엽록체에서 일어나는 과정은?', '["호흡","광합성","세포분열","소화"]', 1, '엽록체는 광합성이 일어나는 세포 소기관입니다.', 41),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_42', '미토콘드리아에서 일어나는 과정은?', '["광합성","세포 호흡","DNA 복제","단백질 합성"]', 1, '미토콘드리아는 세포 호흡으로 ATP를 생산합니다.', 42),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_43', '빛이 프리즘을 통과하면?', '["사라진다","여러 색으로 분산된다","흰색이 된다","검은색이 된다"]', 1, '프리즘은 백색광을 무지개 색으로 분산시킵니다.', 43),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_44', '전자는 어떤 전하를 가지나요?', '["양(+) 전하","음(-) 전하","중성","변한다"]', 1, '전자는 음(-) 전하를 가집니다.', 44),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_45', '양성자는 어떤 전하를 가지나요?', '["양(+) 전하","음(-) 전하","중성","변한다"]', 0, '양성자는 양(+) 전하를 가집니다.', 45),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_46', '철(Fe)의 원소 기호에서 Fe는 무슨 뜻인가요?', '["Fire element","Ferrum(라틴어)","Ferro","Felum"]', 1, 'Fe는 라틴어 Ferrum에서 유래했습니다.', 46),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_47', '은(Silver)의 원소 기호는?', '["Si","Sv","Ag","Sr"]', 2, '은의 원소 기호는 Ag(라틴어 Argentum)입니다.', 47),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_48', '냉동실(-18°C)에서도 죽지 않는 미생물이 있을까요?', '["없다, 다 죽는다","있다, 일부는 휴면 상태로 생존","냉동하면 모두 멸균","미생물은 온도에 영향 없음"]', 1, '일부 미생물은 냉동 상태에서 휴면하며 생존합니다.', 48),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_49', '진공에서 소리가 전달되나요?', '["네","아니요"]', 1, '소리는 매질이 필요하므로 진공에서는 전달되지 않습니다.', 49),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_50', '진공에서 빛은 전달되나요?', '["네","아니요"]', 0, '빛(전자기파)은 매질 없이도 진공에서 전달됩니다.', 50)
ON CONFLICT (question_id) DO NOTHING;
