-- =====================================================
-- 일본어 퀴즈 시드: BEGINNER (초급) - 100문항 [Part 1: 1~50]
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_1', '"먹다"는 일본어로?', '["이쿠","쿠루","타베루","노무"]', 2, '먹다는 "타베루(食べる)"입니다.', 1),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_2', '"마시다"는 일본어로?', '["타베루","노무","미루","키쿠"]', 1, '마시다는 "노무(飲む)"입니다.', 2),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_3', '"가다"는 일본어로?', '["이쿠","쿠루","카에루","아루쿠"]', 0, '가다는 "이쿠(行く)"입니다.', 3),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_4', '"오다"는 일본어로?', '["이쿠","쿠루","카에루","아루쿠"]', 1, '오다는 "쿠루(来る)"입니다.', 4),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_5', '"보다"는 일본어로?', '["미루","키쿠","하나스","카쿠"]', 0, '보다는 "미루(見る)"입니다.', 5),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_6', '"듣다"는 일본어로?', '["미루","키쿠","하나스","카쿠"]', 1, '듣다는 "키쿠(聞く)"입니다.', 6),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_7', '"말하다"는 일본어로?', '["미루","키쿠","하나스","카쿠"]', 2, '말하다는 "하나스(話す)"입니다.', 7),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_8', '"쓰다"(글)는 일본어로?', '["미루","키쿠","하나스","카쿠"]', 3, '쓰다는 "카쿠(書く)"입니다.', 8),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_9', '"읽다"는 일본어로?', '["요무","타츠","스와루","네루"]', 0, '읽다는 "요무(読む)"입니다.', 9),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_10', '"자다"는 일본어로?', '["요무","타츠","스와루","네루"]', 3, '자다는 "네루(寝る)"입니다.', 10),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_11', '"사다"(구매)는 일본어로?', '["카우","우루","쿠루","츠쿠루"]', 0, '사다는 "카우(買う)"입니다.', 11),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_12', '"만들다"는 일본어로?', '["카우","우루","쿠루","츠쿠루"]', 3, '만들다는 "츠쿠루(作る)"입니다.', 12),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_13', '"걷다"는 일본어로?', '["하시루","아루쿠","토부","오요구"]', 1, '걷다는 "아루쿠(歩く)"입니다.', 13),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_14', '"달리다"는 일본어로?', '["하시루","아루쿠","토부","오요구"]', 0, '달리다는 "하시루(走る)"입니다.', 14),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_15', '"돌아가다"는 일본어로?', '["이쿠","쿠루","카에루","데루"]', 2, '돌아가다는 "카에루(帰る)"입니다.', 15),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_16', '"재미있다"는 일본어로?', '["오모시로이","츠마라나이","무즈카시이","야사시이"]', 0, '재미있다는 "오모시로이(面白い)"입니다.', 16),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_17', '"어렵다"는 일본어로?', '["오모시로이","츠마라나이","무즈카시이","야사시이"]', 2, '어렵다는 "무즈카시이(難しい)"입니다.', 17),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_18', '"덥다"는 일본어로?', '["사무이","아츠이","스즈시이","아타타카이"]', 1, '덥다는 "아츠이(暑い)"입니다.', 18),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_19', '"춥다"는 일본어로?', '["사무이","아츠이","스즈시이","아타타카이"]', 0, '춥다는 "사무이(寒い)"입니다.', 19),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_20', '"좋아하다"는 일본어로?', '["스키다","키라이다","조즈다","헤타다"]', 0, '좋아하다는 "스키다(好きだ)"입니다.', 20),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_21', '"새롭다"는 일본어로?', '["아타라시이","후루이","하야이","오소이"]', 0, '새롭다는 "아타라시이(新しい)"입니다.', 21),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_22', '"빠르다"는 일본어로?', '["아타라시이","후루이","하야이","오소이"]', 2, '빠르다는 "하야이(速い)"입니다.', 22),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_23', '"어디"를 뜻하는 의문사는?', '["이츠","도코","다레","나니"]', 1, '어디는 "도코(どこ)"입니다.', 23),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_24', '"무엇"을 뜻하는 의문사는?', '["나니","도레","도코","이츠"]', 0, '무엇은 "나니(何)"입니다.', 24),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_25', '"누구"를 뜻하는 의문사는?', '["나니","도코","다레","이츠"]', 2, '누구는 "다레(誰)"입니다.', 25),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_26', '"언제"를 뜻하는 의문사는?', '["나니","도코","다레","이츠"]', 3, '언제는 "이츠(いつ)"입니다.', 26),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_27', '"얼마"를 뜻하는 표현은?', '["이쿠라","이쿠츠","난닌","난사이"]', 0, '"이쿠라(いくら)"입니다.', 27),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_28', '"~에" (장소)를 나타내는 조사는?', '["가","를","니","데"]', 2, '"니(に)"입니다.', 28),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_29', '"~에서" (행동 장소)를 나타내는 조사는?', '["가","를","니","데"]', 3, '"데(で)"입니다.', 29),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_30', '"~을/를"을 나타내는 조사는?', '["와","오","가","모"]', 1, '"오(を)"입니다.', 30),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_31', '"~도"를 나타내는 조사는?', '["와","오","가","모"]', 3, '"모(も)"입니다.', 31),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_32', '"~과/와"를 나타내는 조사는?', '["가","오","토","데"]', 2, '"토(と)"입니다.', 32),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_33', '"~부터"를 나타내는 조사는?', '["카라","마데","요리","호도"]', 0, '"카라(から)"입니다.', 33),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_34', '존댓말 동사 어미는?', '["~마스","~데스","~다","~나이"]', 0, '"~마스(ます)"입니다.', 34),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_35', '과거형: "타베루" -> "먹었습니다"', '["타베마스","타베마시타","타베마셍","타베타"]', 1, '"~마시타(ました)"입니다.', 35),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_36', '부정형: "이쿠" -> "가지 않다"', '["이카나이","이키나이","이쿠나이","이케나이"]', 0, '"이카나이(行かない)"입니다.', 36),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_37', '"하다"의 일본어는?', '["스루","나루","아루","이루"]', 0, '"스루(する)"입니다.', 37),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_38', '"있다" (사물)의 일본어는?', '["스루","나루","아루","이루"]', 2, '"아루(ある)"입니다.', 38),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_39', '"있다" (사람/동물)의 일본어는?', '["스루","나루","아루","이루"]', 3, '"이루(いる)"입니다.', 39),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_40', '"~하고 싶다"는?', '["~타이","~나이","~마스","~데스"]', 0, '"~타이(~たい)"입니다.', 40),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_41', '"알다/이해하다"는?', '["시루","와카루","오보에루","와스레루"]', 1, '"와카루(分かる)"입니다.', 41),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_42', '"기억하다"는?', '["시루","와카루","오보에루","와스레루"]', 2, '"오보에루(覚える)"입니다.', 42),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_43', '"잊다"는?', '["시루","와카루","오보에루","와스레루"]', 3, '"와스레루(忘れる)"입니다.', 43),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_44', '"기다리다"는?', '["마츠","모츠","카츠","타츠"]', 0, '"마츠(待つ)"입니다.', 44),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_45', '"열다"는?', '["아케루","시메루","츠케루","케스"]', 0, '"아케루(開ける)"입니다.', 45),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_46', '"닫다"는?', '["아케루","시메루","츠케루","케스"]', 1, '"시메루(閉める)"입니다.', 46),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_47', '"월요일"은?', '["겟츠요비","카요비","스이요비","니치요비"]', 0, '"겟츠요비(月曜日)"입니다.', 47),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_48', '"일요일"은?', '["킨요비","도요비","니치요비","겟츠요비"]', 2, '"니치요비(日曜日)"입니다.', 48),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_49', '"이것"은?', '["코레","소레","아레","도레"]', 0, '"코레(これ)"입니다.', 49),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_50', '"~입니다"의 정중형은?', '["다","데스","다요","ない"]', 1, '"데스(です)"입니다.', 50)
ON CONFLICT (question_id) DO NOTHING;
