-- =====================================================
-- 과학 상식 퀴즈: INTERMEDIATE (중급) - Part 1 [1~50]
-- 고등 수준: 물리, 화학, 생물, 지구과학 심화
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_1', '상대성 이론을 발표한 과학자는?', '["뉴턴","아인슈타인","보어","호킹"]', 1, '알베르트 아인슈타인이 1905년/1915년에 발표했습니다.', 1),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_2', 'E=mc²에서 c는 무엇을 의미하나요?', '["칼로리","탄소","빛의 속도","전하량"]', 2, 'c는 진공에서의 빛의 속도(약 3×10⁸ m/s)입니다.', 2),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_3', '전자기 유도를 발견한 과학자는?', '["패러데이","맥스웰","옴","쿨롱"]', 0, '마이클 패러데이가 전자기 유도 현상을 발견했습니다.', 3),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_4', '주기율표를 처음 만든 과학자는?', '["라부아지에","멘델레예프","돌턴","보일"]', 1, '멘델레예프가 1869년 최초의 주기율표를 만들었습니다.', 4),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_5', '원자번호는 무엇을 나타내나요?', '["전자 수","양성자 수","중성자 수","질량수"]', 1, '원자번호는 원자핵 속 양성자의 수입니다.', 5),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_6', '아보가드로 수는 약?', '["6.02×10²³","3.14×10²⁰","9.8×10¹⁰","1.6×10⁻¹⁹"]', 0, '아보가드로 수(N_A) ≈ 6.022×10²³입니다.', 6),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_7', '도플러 효과란?', '["파동의 굴절","파원과 관측자의 상대 운동에 의한 진동수 변화","파동의 회절","공명 현상"]', 1, '음원이 다가오면 높은 음, 멀어지면 낮은 음으로 들립니다.', 7),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_8', '열역학 제1법칙은?', '["엔트로피 증가","에너지 보존","절대 영도 불가","열효율 100% 불가"]', 1, '열역학 제1법칙은 에너지 보존 법칙입니다.', 8),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_9', '열역학 제2법칙과 관련된 개념은?', '["에너지 보존","엔트로피","절대 영도","질량 보존"]', 1, '열역학 제2법칙: 고립계의 엔트로피는 항상 증가합니다.', 9),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_10', '절대 영도(0K)는 섭씨로 약?', '["-100°C","-200°C","-273.15°C","-373.15°C"]', 2, '절대 영도는 -273.15°C입니다.', 10),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_11', '감마선, X선, 자외선, 가시광선을 파장이 짧은 순서로 나열하면?', '["가시광선→자외선→X선→감마선","감마선→X선→자외선→가시광선","X선→감마선→가시광선→자외선","자외선→가시광선→X선→감마선"]', 1, '감마선 < X선 < 자외선 < 가시광선 순으로 파장이 길어집니다.', 11),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_12', '산화 반응이란?', '["산소를 잃는 것","전자를 잃는 것","수소를 얻는 것","전자를 얻는 것"]', 1, '산화는 전자를 잃는 반응입니다.', 12),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_13', '환원 반응이란?', '["산소를 잃는 것","전자를 잃는 것","수소를 잃는 것","전자를 얻는 것"]', 3, '환원은 전자를 얻는 반응입니다.', 13),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_14', '화학 반응에서 촉매의 역할은?', '["반응물 추가","반응 속도 변화(활성화 에너지 낮춤)","생성물 제거","온도 상승"]', 1, '촉매는 자신은 변하지 않으면서 활성화 에너지를 낮춥니다.', 14),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_15', '멘델의 유전 법칙 중 "분리의 법칙"이란?', '["형질이 섞인다","대립유전자가 분리되어 각각 생식세포에 들어간다","유전자가 없어진다","형질이 무작위"]', 1, '감수분열 시 대립유전자 쌍이 분리되어 생식세포로 갑니다.', 15),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_16', '우성과 열성의 비율(Aa × Aa)은?', '["1:1","2:1","3:1","4:1"]', 2, 'Aa × Aa = AA:Aa:aa = 1:2:1 → 표현형 비 3:1.', 16),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_17', '판구조론에서 발산 경계란?', '["두 판이 충돌","두 판이 갈라짐","판이 사라짐","판이 회전"]', 1, '발산 경계에서는 두 판이 서로 멀어집니다(해령 생성).', 17),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_18', '초전도 현상이란?', '["매우 높은 전기 저항","절대 영도에서만 발생","특정 온도 이하에서 저항이 0","전류가 흐르지 않음"]', 2, '초전도체는 임계 온도 이하에서 전기 저항이 0이 됩니다.', 18),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_19', '광전 효과를 설명한 과학자는?', '["뉴턴","아인슈타인","맥스웰","패러데이"]', 1, '아인슈타인이 광전 효과를 광양자 가설로 설명(1905)했습니다.', 19),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_20', 'DNA에서 아데닌(A)과 쌍을 이루는 염기는?', '["구아닌(G)","시토신(C)","티민(T)","우라실(U)"]', 2, 'DNA에서 A-T, G-C 쌍을 이룹니다.', 20),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_21', 'RNA에서 아데닌(A)과 쌍을 이루는 염기는?', '["구아닌(G)","시토신(C)","티민(T)","우라실(U)"]', 3, 'RNA에서는 티민(T) 대신 우라실(U)이 사용됩니다.', 21),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_22', '보일의 법칙은?', '["온도 일정 시 압력×부피=일정","압력 일정 시 부피/온도=일정","기체 분자 운동 법칙","질량 보존 법칙"]', 0, 'PV=일정 (온도 일정 시 압력과 부피는 반비례).', 22),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_23', '샤를의 법칙은?', '["PV=일정","V/T=일정(압력 일정)","PV=nRT","F=ma"]', 1, '압력 일정 시 부피는 절대 온도에 비례합니다.', 23),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_24', '이상기체 방정식은?', '["PV=nRT","E=mc²","F=ma","V=IR"]', 0, 'PV=nRT (P:압력, V:부피, n:몰수, R:기체상수, T:온도).', 24),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_25', '탄소 동위원소 C-14는 무엇에 사용되나요?', '["의료 영상","연대 측정","핵발전","원소 분석"]', 1, 'C-14 방사성 탄소 연대측정법에 사용됩니다.', 25),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_26', '원심력은 실제 힘인가요?', '["네, 실제 힘","아니요, 관성에 의한 가상 힘(관성력)","때에 따라 다름","중력과 같음"]', 1, '원심력은 회전 좌표계에서 나타나는 관성력(가짜 힘)입니다.', 26),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_27', '블랙홀이란?', '["빛도 빠져나올 수 없는 천체","어두운 별","빈 우주 공간","소행성"]', 0, '블랙홀은 중력이 너무 강해 빛조차 탈출할 수 없는 천체입니다.', 27),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_28', '전해질이란?', '["물에 녹으면 이온으로 분리되어 전류가 흐르는 물질","모든 고체","비금속 원소","비전도체"]', 0, '전해질은 물에 녹아 이온화되어 전류를 통하게 합니다.', 28),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_29', '공유 결합이란?', '["전자를 주고받는 결합","전자쌍을 공유하는 결합","금속 간 결합","이온 간 결합"]', 1, '공유 결합은 원자 간 전자쌍을 공유하는 결합입니다.', 29),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_30', '이온 결합이란?', '["전자를 공유","양이온과 음이온 간 정전기적 인력","금속 결합","수소 결합"]', 1, '이온 결합은 양이온과 음이온 사이의 전기적 인력입니다.', 30),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_31', '광합성의 화학식은?', '["6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂","C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O","2H₂ + O₂ → 2H₂O","NaCl → Na⁺ + Cl⁻"]', 0, '6CO₂ + 6H₂O + 빛에너지 → C₆H₁₂O₆ + 6O₂', 31),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_32', '세포 호흡의 화학식은?', '["6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂","C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP","2H₂ + O₂ → 2H₂O","NaCl + H₂O → NaOH + HCl"]', 1, '포도당 + 산소 → 이산화탄소 + 물 + ATP(에너지)', 32),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_33', '허블의 법칙이란?', '["행성의 운동 법칙","먼 은하일수록 빠르게 멀어진다","별의 밝기 법칙","태양 흑점 주기"]', 1, '은하의 후퇴 속도는 거리에 비례(우주 팽창의 증거).', 33),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_34', '별의 색과 표면 온도의 관계는?', '["빨간 별이 가장 뜨겁다","파란 별이 가장 뜨겁다","색과 온도는 무관","흰색이 가장 차갑다"]', 1, '파란색 별 > 흰색 > 노란색 > 빨간색 순으로 뜨겁습니다.', 34),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_35', '슈뢰딩거 방정식은 어느 분야인가요?', '["고전역학","양자역학","열역학","유체역학"]', 1, '슈뢰딩거 방정식은 양자역학의 기본 방정식입니다.', 35),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_36', '반감기란?', '["물질이 완전히 분해되는 시간","반응속도가 절반이 되는 시간","방사성 물질의 양이 절반으로 줄어드는 시간","물질의 수명"]', 2, '방사성 원소의 양이 절반으로 줄어드는 데 걸리는 시간입니다.', 36),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_37', '핵분열과 핵융합 중 태양에서 일어나는 것은?', '["핵분열","핵융합","둘 다","둘 다 아님"]', 1, '태양은 수소 핵융합 반응으로 에너지를 방출합니다.', 37),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_38', '슈퍼노바(초신성)란?', '["작은 별","별의 대폭발","행성 충돌","소행성"]', 1, '질량이 큰 별이 일생의 마지막에 대폭발하는 현상입니다.', 38),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_39', '중성미자(뉴트리노)의 특징은?', '["전하가 크다","질량이 매우 크다","물질과 거의 상호작용하지 않음","빛보다 느림"]', 2, '뉴트리노는 전하가 없고 물질과 거의 반응하지 않습니다.', 39),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_40', 'PCR(중합효소 연쇄반응)의 용도는?', '["단백질 분석","DNA 증폭","세포 배양","약물 합성"]', 1, 'PCR은 소량의 DNA를 대량으로 증폭하는 기술입니다.', 40),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_41', '코리올리 효과란?', '["지구 자전 때문에 움직이는 물체의 방향이 편향되는 현상","달의 인력 효과","태양 복사 효과","지구 공전 효과"]', 0, '지구 자전에 의해 대기, 해류의 이동 방향이 편향됩니다.', 41),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_42', '엘니뇨 현상이란?', '["극지방 빙하 녹음","태평양 적도 동부 해수면 온도 상승","화산 폭발","오존층 파괴"]', 1, '태평양 적도 부근 동부 해수면 온도가 비정상적으로 상승.', 42),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_43', '라니냐 현상이란?', '["해수면 온도 상승","태평양 적도 동부 해수면 온도 하강","극지방 온난화","해수면 상승"]', 1, '엘니뇨와 반대로 해수면 온도가 비정상적으로 하강.', 43),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_44', '케플러의 제1법칙은?', '["행성은 원 궤도","행성은 타원 궤도","행성의 공전 주기","만유인력"]', 1, '행성은 태양을 한 초점으로 하는 타원 궤도를 그립니다.', 44),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_45', '무게와 질량의 차이는?', '["같은 개념","무게는 중력에 의한 힘, 질량은 물질의 양","질량이 더 크다","무게가 더 크다"]', 1, '질량은 변하지 않지만 무게는 중력에 따라 달라집니다.', 45),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_46', '오존(O₃)의 역할은?', '["온난화 촉진","자외선 차단","산소 공급","열 방출"]', 1, '성층권의 오존층은 유해 자외선(UV-B, C)을 차단합니다.', 46),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_47', '암페어의 법칙과 관련된 것은?', '["전류가 만드는 자기장","빛의 굴절","소리의 반사","열전도"]', 0, '전류가 흐르면 주변에 자기장이 형성됩니다.', 47),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_48', '파동의 성질이 아닌 것은?', '["반사","굴절","회절","녹는 점"]', 3, '반사, 굴절, 회절, 간섭은 파동의 성질입니다.', 48),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_49', '적외선의 주된 용도는?', '["X-ray 촬영","TV 리모컨/열화상","자외선 소독","라디오 방송"]', 1, '적외선은 열 감지, 리모컨 등에 사용됩니다.', 49),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='science'), 'sc_j_50', '헤르츠-루스프엘 도표(HR도)란?', '["주기율표","별의 밝기와 표면 온도를 나타낸 도표","화학 반응 도표","지질 연대표"]', 1, 'HR도는 별의 분류(주계열성, 거성, 백색왜성 등)에 사용됩니다.', 50)
ON CONFLICT (question_id) DO NOTHING;
