-- =====================================================
-- English Quiz Seed: ADVANCED Part 2 [51~100]
-- Business English, advanced idioms, collocations, SAT-level vocab
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_51', '"go the extra mile"의 뜻은?', '["먼 길을 가다","남들보다 더 노력하다","마일을 세다","운동하다"]', 1, '관용표현: 남들보다 더 많은 노력을 하다.', 51),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_52', '"hit the ground running"의 뜻은?', '["달리며 넘어지다","처음부터 바로 일을 잘 해내다","운동장에서 뛰다","빨리 도망치다"]', 1, '관용표현: 시작부터 바로 적응하여 잘 해내다.', 52),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_53', '"think outside the box"의 뜻은?', '["상자 밖을 생각하다","틀에 박힌 생각을 벗어나다","정리하다","이사하다"]', 1, '관용표현: 창의적으로 생각하다.', 53),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_54', '"touch base"의 뜻은?', '["기지를 만지다","간단히 연락하다/확인하다","홈런을 치다","출발하다"]', 1, '비즈니스 관용구: 간략하게 연락/확인하다.', 54),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_55', '"take it with a grain of salt"의 뜻은?', '["소금을 넣다","가감해서 듣다/곧이곧대로 믿지 않다","맛보다","의심하다"]', 1, '관용표현: 액면 그대로 믿지 않다.', 55),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_56', '"ephemeral"의 뜻은?', '["영원한","일시적인/덧없는","눈에 띄는","특별한"]', 1, '"ephemeral" = 일시적인/덧없는.', 56),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_57', '"quintessential"의 뜻은?', '["다섯 번째의","전형적인/정수의","불필요한","오래된"]', 1, '"quintessential" = 전형적인/가장 본질적인.', 57),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_58', '"perfunctory"의 뜻은?', '["완벽한","형식적인/건성의","기능적인","생산적인"]', 1, '"perfunctory" = 형식적인/건성으로 하는.', 58),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_59', '"sycophant"의 뜻은?', '["비평가","아첨꾼","예언자","지도자"]', 1, '"sycophant" = 아첨꾼.', 59),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_60', '"cacophony"의 뜻은?', '["아름다운 소리","불협화음/소음","반복","침묵"]', 1, '"cacophony" = 불협화음/소음.', 60),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_61', 'We need to ___ this issue ASAP. (비즈니스)', '["address","undress","redress","dress"]', 0, '"address an issue" = 문제를 다루다/해결하다.', 61),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_62', 'Please find ___ the report. (이메일)', '["attach","attaching","attached","attachment"]', 2, '"Please find attached" = 첨부 파일을 확인해주세요.', 62),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_63', '"at the end of the day"의 뜻은?', '["하루가 끝날 때","결국/최종적으로","퇴근할 때","마감 시간에"]', 1, '관용표현: 결국/최종적으로.', 63),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_64', '"on the same page"의 뜻은?', '["같은 페이지에","같은 의견/이해를 가진","같이 읽다","같은 학교"]', 1, '관용표현: 같은 이해/의견을 가지고 있다.', 64),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_65', '"keep someone in the loop"의 뜻은?', '["회전시키다","최신 정보를 공유하다","가두다","반복시키다"]', 1, '비즈니스 관용구: 계속 정보를 공유하다.', 65),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_66', '"ostentatious"의 뜻은?', '["검소한","과시적인/허세부리는","겸손한","조용한"]', 1, '"ostentatious" = 과시적인.', 66),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_67', '"conundrum"의 뜻은?', '["해결책","난제/수수께끼","실험","합의"]', 1, '"conundrum" = 난제/풀기 어려운 문제.', 67),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_68', '"vicarious"의 뜻은?', '["직접적인","대리의/간접적인","악의적인","승리의"]', 1, '"vicarious" = 대리의/간접 경험의.', 68),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_69', '"serendipity"의 뜻은?', '["행복","뜻밖의 발견/행운","우연","평온"]', 1, '"serendipity" = 우연한 행운/뜻밖의 발견.', 69),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_70', '"the elephant in the room"의 뜻은?', '["방에 있는 코끼리","다 알지만 언급 안 하는 문제","큰 물건","방해물"]', 1, '관용표현: 모두 알지만 아무도 언급하지 않는 중요한 문제.', 70),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_71', 'Little ___ he know what was coming.', '["does","did","was","had"]', 1, '부정 부사 도치: Little did + S + V원형.', 71),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_72', 'So ___ was the task that nobody attempted it.', '["difficult","difficulty","difficulties","difficultly"]', 0, '"So + 형용사 + 도치" 구문.', 72),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_73', '"paradigm"의 뜻은?', '["천국","패러다임/전형적 예","평행선","낙원"]', 1, '"paradigm" = 패러다임/모범.', 73),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_74', '"nuance"의 뜻은?', '["뉘앙스/미묘한 차이","소음","방해","폐해"]', 0, '"nuance" = 뉘앙스/미묘한 차이.', 74),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_75', '"leverage"(비즈니스)의 뜻은?', '["레버","영향력/활용하다","빚","고정하다"]', 1, '"leverage" = 영향력(명사)/활용하다(동사).', 75),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_76', '"move the needle"의 뜻은?', '["바늘을 옮기다","눈에 띄는 변화를 만들다","수치를 바꾸다","재봉하다"]', 1, '비즈니스 관용구: 의미 있는 변화/진전을 만들다.', 76),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_77', '"boil the ocean"의 뜻은?', '["바다를 끓이다","비현실적으로 큰 일을 시도하다","열심히 일하다","요리하다"]', 1, '비즈니스 관용구: 비현실적으로 거대한 과업을 시도하다.', 77),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_78', '"obfuscate"의 뜻은?', '["명확히 하다","혼란스럽게 하다/모호하게 하다","관찰하다","방해하다"]', 1, '"obfuscate" = 혼란스럽게 하다/모호하게 만들다.', 78),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_79', '"pernicious"의 뜻은?', '["유익한","해로운/치명적인","영구적인","허용된"]', 1, '"pernicious" = 해로운/치명적인.', 79),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_80', '"taciturn"의 뜻은?', '["수다스러운","과묵한/말이 적은","기민한","공격적인"]', 1, '"taciturn" = 과묵한/말이 적은.', 80),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_81', '"Don''t put all your eggs in one basket"의 뜻은?', '["달걀을 모으다","한 곳에 모든 것을 걸지 마라","절약하다","정리하다"]', 1, '관용표현: 위험을 분산하라.', 81),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_82', '"cross that bridge when we come to it"의 뜻은?', '["다리를 건너다","그때 가서 생각하자","계획을 세우다","미리 대비하다"]', 1, '관용표현: 그때 가서 생각하자/닥쳐봐야 안다.', 82),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_83', '"magnanimous"의 뜻은?', '["거대한","관대한/넓은 마음의","자기적인","유명한"]', 1, '"magnanimous" = 관대한/아량 있는.', 83),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_84', '"acquiesce"의 뜻은?', '["획득하다","마지못해 따르다/묵인하다","인정하다","달성하다"]', 1, '"acquiesce" = 마지못해 따르다/묵인하다.', 84),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_85', '"liaise"의 뜻은?', '["거짓말하다","연락을 취하다/조율하다","연합하다","합법화하다"]', 1, '"liaise" = 연락을 취하다/조율하다.', 85),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_86', '"scalable"(비즈니스)의 뜻은?', '["크기 조절 가능한","확장 가능한","측정 가능한","덮을 수 있는"]', 1, '"scalable" = (사업/시스템이) 확장 가능한.', 86),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_87', '"synergy"의 뜻은?', '["에너지","시너지/상승효과","합성","동기화"]', 1, '"synergy" = 시너지/상승효과.', 87),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_88', '"take a rain check"의 뜻은?', '["비 확인","다음 기회에 하자","우산을 가져가다","예약 취소"]', 1, '관용표현: 이번은 못하고 다음 기회에.', 88),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_89', '"play it by ear"의 뜻은?', '["귀로 듣다","상황을 봐가며 대처하다","음악을 연주하다","무시하다"]', 1, '관용표현: 상황을 봐가며 유연하게 대처하다.', 89),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_90', '"see eye to eye"의 뜻은?', '["눈을 마주치다","의견이 일치하다","서로 바라보다","눈을 감다"]', 1, '관용표현: 의견이 일치하다.', 90),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_91', '"superfluous"의 뜻은?', '["훌륭한","불필요한/과잉의","피상적인","초자연적인"]', 1, '"superfluous" = 불필요한/과잉의.', 91),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_92', '"belligerent"의 뜻은?', '["아름다운","호전적인/적대적인","자선적인","유익한"]', 1, '"belligerent" = 호전적인/적대적인.', 92),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_93', '"vindicate"의 뜻은?', '["복수하다","결백을 증명하다/정당화하다","비난하다","승리하다"]', 1, '"vindicate" = 정당화하다/결백을 증명하다.', 93),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_94', '"walk on eggshells"의 뜻은?', '["달걀 위를 걷다","조심스럽게 행동하다","위험을 감수하다","모험하다"]', 1, '관용표현: 말조심하며 조심스럽게 행동하다.', 94),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_95', '"back to square one"의 뜻은?', '["첫 번째 칸으로","원점으로 돌아가다","후퇴하다","포기하다"]', 1, '관용표현: 처음부터 다시 시작하다.', 95),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_96', '"proliferate"의 뜻은?', '["금지하다","급속히 확산하다/증가하다","발전하다","생산하다"]', 1, '"proliferate" = 급속히 확산하다/증가하다.', 96),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_97', '"altruistic"의 뜻은?', '["이기적인","이타적인","비현실적인","낙관적인"]', 1, '"altruistic" = 이타적인.', 97),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_98', '"penultimate"의 뜻은?', '["마지막의","끝에서 두 번째의","궁극적인","처음의"]', 1, '"penultimate" = 끝에서 두 번째의.', 98),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_99', '"get the ball rolling"의 뜻은?', '["공을 굴리다","일을 시작하다","운동하다","서두르다"]', 1, '관용표현: 일을 시작하다/진행시키다.', 99),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='english'), 'en_g_100', '"in a nutshell"의 뜻은?', '["견과류 속에","간단히 말하면/요약하면","자세히","핵심에서 벗어나"]', 1, '관용표현: 간단히 말하면/요약하면.', 100)
ON CONFLICT (question_id) DO NOTHING;
