-- =====================================================
-- English Quiz Seed: INTERMEDIATE Part 2 [51~100]
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_51', '"거절하다"를 영어로?', '["Refuse","Receive","Reduce","Remove"]', 0, '"Refuse"는 거절하다입니다.', 51),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_52', '"줄이다"를 영어로?', '["Refuse","Receive","Reduce","Remove"]', 2, '"Reduce"는 줄이다입니다.', 52),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_53', '"제거하다"를 영어로?', '["Refuse","Receive","Reduce","Remove"]', 3, '"Remove"는 제거하다입니다.', 53),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_54', 'She asked me ___ I could help her.', '["that","if","what","which"]', 1, '간접 의문문: if = ~인지 아닌지.', 54),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_55', 'He suggested ___ we go to the park.', '["if","that","what","which"]', 1, 'suggest + that절.', 55),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_56', '"call off"의 뜻은?', '["전화하다","취소하다","불러내다","돌려보내다"]', 1, '"call off" = 취소하다.', 56),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_57', '"carry out"의 뜻은?', '["운반하다","수행하다","들고 나가다","참다"]', 1, '"carry out" = 수행하다/실행하다.', 57),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_58', '"set up"의 뜻은?', '["앉다","설립하다/설치하다","정리하다","멈추다"]', 1, '"set up" = 설립하다/설치하다.', 58),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_59', '"bring up"의 뜻은?', '["가져오다","기르다/화제를 꺼내다","올리다","배달하다"]', 1, '"bring up" = 기르다/화제를 꺼내다.', 59),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_60', 'If I had studied harder, I ___ passed the exam.', '["will have","would have","could","should"]', 1, '가정법 과거완료: would have + p.p.', 60),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_61', '"결과"를 영어로?', '["Result","Reason","Resource","Research"]', 0, '"Result"는 결과입니다.', 61),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_62', '"이유"를 영어로?', '["Result","Reason","Resource","Research"]', 1, '"Reason"은 이유입니다.', 62),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_63', '"연구"를 영어로?', '["Result","Reason","Resource","Research"]', 3, '"Research"는 연구입니다.', 63),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_64', 'It is worth ___ this movie. (watch)', '["watch","watched","watching","to watch"]', 2, '"It is worth ~ing" 구문.', 64),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_65', 'I regret ___ that to her. (say)', '["say","said","saying","to say"]', 2, '"regret ~ing" = ~한 것을 후회하다.', 65),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_66', 'He avoided ___ the question. (answer)', '["answer","answered","answering","to answer"]', 2, '"avoid ~ing" 구문.', 66),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_67', 'I am looking forward to ___ you. (see)', '["see","saw","seeing","seen"]', 2, '"look forward to ~ing" 구문.', 67),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_68', '"성공하다"를 영어로?', '["Succeed","Success","Successful","Successfully"]', 0, '"Succeed"는 동사 성공하다입니다.', 68),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_69', '"성공" (명사)을 영어로?', '["Succeed","Success","Successful","Successfully"]', 1, '"Success"는 명사 성공입니다.', 69),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_70', '"영향"을 영어로?', '["Influence","Intelligent","Ingredient","Innocent"]', 0, '"Influence"는 영향입니다.', 70),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_71', 'He ___ me to go with him. (요청하다)', '["said","told","asked","talked"]', 2, '"ask + 목적어 + to부정사"입니다.', 71),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_72', 'The teacher made us ___ the homework. (do)', '["do","to do","doing","done"]', 0, '"make + 목적어 + 동사원형" 사역동사.', 72),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_73', 'I had my car ___. (고치다)', '["fix","fixed","fixing","to fix"]', 1, '"have + 목적어 + 과거분사" 사역.', 73),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_74', '"~동안"을 영어로? (기간)', '["During","While","For","Since"]', 2, '기간 앞에는 "For"를 씁니다.', 74),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_75', '"~이래로"를 영어로? (시점)', '["During","While","For","Since"]', 3, '시점 앞에는 "Since"를 씁니다.', 75),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_76', '"독립적인"을 영어로?', '["Independent","Dependent","Incredible","Individual"]', 0, '"Independent"는 독립적인입니다.', 76),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_77', '"의존적인"을 영어로?', '["Independent","Dependent","Incredible","Individual"]', 1, '"Dependent"는 의존적인입니다.', 77),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_78', '"증가하다"를 영어로?', '["Increase","Decrease","Include","Income"]', 0, '"Increase"는 증가하다입니다.', 78),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_79', '"감소하다"를 영어로?', '["Increase","Decrease","Include","Income"]', 1, '"Decrease"는 감소하다입니다.', 79),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_80', '"포함하다"를 영어로?', '["Increase","Decrease","Include","Income"]', 2, '"Include"는 포함하다입니다.', 80),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_81', 'The ___ you study, the more you learn.', '["much","more","most","many"]', 1, '"The more ~, the more ~" 구문.', 81),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_82', 'She speaks English as ___ as her teacher.', '["good","better","well","best"]', 2, '"as + 원급 + as" 동등비교. 부사 "well".', 82),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_83', '"가능성"을 영어로?', '["Possible","Possibility","Possibly","Position"]', 1, '"Possibility"는 가능성(명사)입니다.', 83),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_84', '"필요한"을 영어로?', '["Necessary","Accessory","Ordinary","Temporary"]', 0, '"Necessary"는 필요한입니다.', 84),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_85', '"일시적인"을 영어로?', '["Necessary","Accessory","Ordinary","Temporary"]', 3, '"Temporary"는 일시적인입니다.', 85),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_86', '"point out"의 뜻은?', '["가리키다","지적하다","둘 다 맞음","끝내다"]', 2, '"point out" = 가리키다/지적하다.', 86),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_87', '"hold on"의 뜻은?', '["잡고 있다","기다리다","둘 다 맞음","놓아주다"]', 2, '"hold on" = 잡고 있다/기다리다.', 87),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_88', '"pass away"의 뜻은?', '["지나가다","돌아가시다(사망)","건네주다","통과하다"]', 1, '"pass away" = 돌아가시다(완곡 표현).', 88),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_89', '"비교하다"를 영어로?', '["Compare","Complete","Compete","Compose"]', 0, '"Compare"는 비교하다입니다.', 89),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_90', '"경쟁하다"를 영어로?', '["Compare","Complete","Compete","Compose"]', 2, '"Compete"는 경쟁하다입니다.', 90),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_91', '"완료하다"를 영어로?', '["Compare","Complete","Compete","Compose"]', 1, '"Complete"는 완료하다입니다.', 91),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_92', 'I ___ rather stay home than go out.', '["would","should","could","will"]', 0, '"would rather A than B" 구문.', 92),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_93', '"적절한"을 영어로?', '["Appropriate","Approximate","Appreciate","Approach"]', 0, '"Appropriate"는 적절한입니다.', 93),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_94', '"감사하다"를 영어로?', '["Appropriate","Approximate","Appreciate","Approach"]', 2, '"Appreciate"는 감사하다/높이 평가하다입니다.', 94),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_95', '"접근하다"를 영어로?', '["Appropriate","Approximate","Appreciate","Approach"]', 3, '"Approach"는 접근하다입니다.', 95),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_96', 'She is ___ in cooking. (관심있다)', '["interest","interested","interesting","interests"]', 1, '"interested in" = ~에 관심있다. 과거분사.', 96),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_97', 'The movie was very ___. (흥미로운)', '["interest","interested","interesting","interests"]', 2, '"interesting" = 흥미로운. 현재분사.', 97),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_98', '"확인하다"를 영어로?', '["Confirm","Confuse","Compare","Consider"]', 0, '"Confirm"은 확인하다입니다.', 98),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_99', '"혼란스럽게 하다"를 영어로?', '["Confirm","Confuse","Compare","Consider"]', 1, '"Confuse"는 혼란스럽게 하다입니다.', 99),
((SELECT id FROM quiz_sets WHERE difficulty='INTERMEDIATE' AND category='english'), 'en_j_100', '"고려하다"를 영어로?', '["Confirm","Confuse","Compare","Consider"]', 3, '"Consider"는 고려하다입니다.', 100)
ON CONFLICT (question_id) DO NOTHING;
