-- =====================================================
-- English Quiz Seed: BEGINNER Part 2 [51~100]
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_51', '"왜"를 영어로?', '["Why","How","Which","Whose"]', 0, '"Why"는 왜입니다.', 51),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_52', '"어떻게"를 영어로?', '["Why","How","Which","Whose"]', 1, '"How"는 어떻게입니다.', 52),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_53', 'I ___ playing soccer now. (현재진행)', '["is","am","are","was"]', 1, '주어 I + "am" + ~ing입니다.', 53),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_54', 'He ___ watching TV now.', '["is","am","are","was"]', 0, '3인칭 단수 + "is" + ~ing입니다.', 54),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_55', '"~할 수 있다"를 영어로?', '["Can","Must","Should","Will"]', 0, '"Can"은 ~할 수 있다입니다.', 55),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_56', '"~해야 한다"를 영어로?', '["Can","Must","Should","Will"]', 1, '"Must"는 ~해야 한다입니다.', 56),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_57', '"~할 것이다"(미래)를 영어로?', '["Can","Must","Should","Will"]', 3, '"Will"은 ~할 것이다입니다.', 57),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_58', '"열다"를 영어로?', '["Open","Close","Push","Pull"]', 0, '"Open"은 열다입니다.', 58),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_59', '"닫다"를 영어로?', '["Open","Close","Push","Pull"]', 1, '"Close"는 닫다입니다.', 59),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_60', '"밀다"를 영어로?', '["Open","Close","Push","Pull"]', 2, '"Push"는 밀다입니다.', 60),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_61', '"당기다"를 영어로?', '["Open","Close","Push","Pull"]', 3, '"Pull"은 당기다입니다.', 61),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_62', 'I went to the store ___ buy milk.', '["for","to","at","by"]', 1, '목적을 나타내는 "to"입니다.', 62),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_63', 'She is good ___ math.', '["in","on","at","for"]', 2, '"good at ~" = ~를 잘하다.', 63),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_64', '"빠른"을 영어로?', '["Fast","Slow","High","Low"]', 0, '"Fast"는 빠른입니다.', 64),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_65', '"느린"을 영어로?', '["Fast","Slow","High","Low"]', 1, '"Slow"는 느린입니다.', 65),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_66', '"높은"을 영어로?', '["Fast","Slow","High","Low"]', 2, '"High"는 높은입니다.', 66),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_67', '"무거운"을 영어로?', '["Heavy","Light","Hard","Soft"]', 0, '"Heavy"는 무거운입니다.', 67),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_68', '"가벼운"을 영어로?', '["Heavy","Light","Hard","Soft"]', 1, '"Light"는 가벼운입니다.', 68),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_69', '"울다"를 영어로?', '["Cry","Laugh","Smile","Shout"]', 0, '"Cry"는 울다입니다.', 69),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_70', '"웃다"를 영어로?', '["Cry","Laugh","Smile","Shout"]', 1, '"Laugh"는 웃다입니다.', 70),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_71', '"기다리다"를 영어로?', '["Wait","Hurry","Stay","Leave"]', 0, '"Wait"는 기다리다입니다.', 71),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_72', '"떠나다"를 영어로?', '["Wait","Hurry","Stay","Leave"]', 3, '"Leave"는 떠나다입니다.', 72),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_73', '"도움"을 영어로?', '["Help","Hope","Hate","Have"]', 0, '"Help"는 도움/돕다입니다.', 73),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_74', '"배우다"를 영어로?', '["Learn","Teach","Study","Know"]', 0, '"Learn"은 배우다입니다.', 74),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_75', '"가르치다"를 영어로?', '["Learn","Teach","Study","Know"]', 1, '"Teach"는 가르치다입니다.', 75),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_76', '"알다"를 영어로?', '["Learn","Teach","Study","Know"]', 3, '"Know"는 알다입니다.', 76),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_77', '"머리"를 영어로?', '["Head","Face","Hand","Foot"]', 0, '"Head"는 머리입니다.', 77),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_78', '"얼굴"을 영어로?', '["Head","Face","Hand","Foot"]', 1, '"Face"는 얼굴입니다.', 78),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_79', '"손"을 영어로?', '["Head","Face","Hand","Foot"]', 2, '"Hand"는 손입니다.', 79),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_80', '"발"을 영어로?', '["Head","Face","Hand","Foot"]', 3, '"Foot"은 발입니다.', 80),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_81', '"눈"(신체)을 영어로?', '["Eye","Ear","Nose","Mouth"]', 0, '"Eye"는 눈입니다.', 81),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_82', '"귀"를 영어로?', '["Eye","Ear","Nose","Mouth"]', 1, '"Ear"는 귀입니다.', 82),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_83', '"코"를 영어로?', '["Eye","Ear","Nose","Mouth"]', 2, '"Nose"는 코입니다.', 83),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_84', '"입"을 영어로?', '["Eye","Ear","Nose","Mouth"]', 3, '"Mouth"는 입입니다.', 84),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_85', '"씻다"를 영어로?', '["Wash","Clean","Dry","Wet"]', 0, '"Wash"는 씻다입니다.', 85),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_86', '"놀다"를 영어로?', '["Play","Work","Rest","Sleep"]', 0, '"Play"는 놀다입니다.', 86),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_87', '"일하다"를 영어로?', '["Play","Work","Rest","Sleep"]', 1, '"Work"는 일하다입니다.', 87),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_88', '"쉬다"를 영어로?', '["Play","Work","Rest","Sleep"]', 2, '"Rest"는 쉬다입니다.', 88),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_89', 'I like apples, ___ I do not like oranges.', '["and","but","or","so"]', 1, '역접의 접속사 "but"입니다.', 89),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_90', 'Would you like tea ___ coffee?', '["and","but","or","so"]', 2, '선택의 접속사 "or"입니다.', 90),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_91', '"많은" (셀 수 있는)을 영어로?', '["Many","Much","A lot","Few"]', 0, '셀 수 있는 명사에는 "Many"를 씁니다.', 91),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_92', '"많은" (셀 수 없는)을 영어로?', '["Many","Much","A lot","Few"]', 1, '셀 수 없는 명사에는 "Much"를 씁니다.', 92),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_93', '"날씨"를 영어로?', '["Weather","Season","Climate","Temperature"]', 0, '"Weather"는 날씨입니다.', 93),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_94', '"맑은"을 영어로?', '["Sunny","Cloudy","Rainy","Windy"]', 0, '"Sunny"는 맑은입니다.', 94),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_95', '"흐린"을 영어로?', '["Sunny","Cloudy","Rainy","Windy"]', 1, '"Cloudy"는 흐린입니다.', 95),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_96', '"잊다"를 영어로?', '["Remember","Forget","Remind","Recall"]', 1, '"Forget"은 잊다입니다.', 96),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_97', '"기억하다"를 영어로?', '["Remember","Forget","Remind","Recall"]', 0, '"Remember"는 기억하다입니다.', 97),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_98', '"시작하다"를 영어로?', '["Start","Stop","Finish","Continue"]', 0, '"Start"는 시작하다입니다.', 98),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_99', '"끝내다"를 영어로?', '["Start","Stop","Finish","Continue"]', 2, '"Finish"는 끝내다입니다.', 99),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='english'), 'en_c_100', '"계속하다"를 영어로?', '["Start","Stop","Finish","Continue"]', 3, '"Continue"는 계속하다입니다.', 100)
ON CONFLICT (question_id) DO NOTHING;
