-- =====================================================
-- 일본어 퀴즈 시드: BEGINNER (초급) - Part 2 [51~100]
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_51', '"괜찮습니다"는?', '["다이조부","무리","다메","이이"]', 0, '"다이조부(大丈夫)"입니다.', 51),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_52', '"천천히"는?', '["핫쿠","유쿠리","하야쿠","스구"]', 1, '"유쿠리(ゆっくり)"입니다.', 52),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_53', '"빨리"는?', '["핫쿠","유쿠리","하야쿠","스구"]', 2, '"하야쿠(早く)"입니다.', 53),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_54', '"많다"는?', '["오이","스쿠나이","히로이","세마이"]', 0, '"오이(多い)"입니다.', 54),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_55', '"적다"는?', '["오이","스쿠나이","히로이","세마이"]', 1, '"스쿠나이(少ない)"입니다.', 55),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_56', '"날씨"는?', '["텐키","키온","카제","아메"]', 0, '"텐키(天気)"입니다.', 56),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_57', '"비"는?', '["텐키","유키","카제","아메"]', 3, '"아메(雨)"입니다.', 57),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_58', '"~합시다"(권유)는?', '["~마쇼","~마스","~마시타","~마셍카"]', 0, '"~마쇼(~ましょう)"입니다.', 58),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_59', '"되다"의 일본어는?', '["스루","나루","아루","이루"]', 1, '"나루(なる)"입니다.', 59),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_60', '"놀다"는 일본어로?', '["아소부","야스무","하타라쿠","베쿄스루"]', 0, '"아소부(遊ぶ)"입니다.', 60),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_61', '"쉬다"는 일본어로?', '["아소부","야스무","하타라쿠","베쿄스루"]', 1, '"야스무(休む)"입니다.', 61),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_62', '"일하다"는 일본어로?', '["아소부","야스무","하타라쿠","베쿄스루"]', 2, '"하타라쿠(働く)"입니다.', 62),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_63', '"공부하다"는 일본어로?', '["아소부","야스무","하타라쿠","벤쿄스루"]', 3, '"벤쿄스루(勉強する)"입니다.', 63),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_64', '"세다"(강하다)는?', '["츠요이","요와이","카타이","야와라카이"]', 0, '"츠요이(強い)"입니다.', 64),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_65', '"약하다"는?', '["츠요이","요와이","카타이","야와라카이"]', 1, '"요와이(弱い)"입니다.', 65),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_66', '"무겁다"는?', '["오모이","카루이","나가이","미지카이"]', 0, '"오모이(重い)"입니다.', 66),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_67', '"가볍다"는?', '["오모이","카루이","나가이","미지카이"]', 1, '"카루이(軽い)"입니다.', 67),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_68', '"길다"는?', '["오모이","카루이","나가이","미지카이"]', 2, '"나가이(長い)"입니다.', 68),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_69', '"짧다"는?', '["오모이","카루이","나가이","미지카이"]', 3, '"미지카이(短い)"입니다.', 69),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_70', '"보내다"는?', '["오쿠루","모라우","아게루","쿠레루"]', 0, '"오쿠루(送る)"입니다.', 70),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_71', '"받다"는?', '["오쿠루","모라우","아게루","쿠레루"]', 1, '"모라우(もらう)"입니다.', 71),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_72', '"주다"(나→상대)는?', '["오쿠루","모라우","아게루","쿠레루"]', 2, '"아게루(あげる)"입니다.', 72),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_73', '"준다"(상대→나)는?', '["오쿠루","모라우","아게루","쿠레루"]', 3, '"쿠레루(くれる)"입니다.', 73),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_74', '"전화"는?', '["덴와","덴샤","덴키","덴치"]', 0, '"덴와(電話)"입니다.', 74),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_75', '"전철"은?', '["덴와","덴샤","덴키","덴치"]', 1, '"덴샤(電車)"입니다.', 75),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_76', '"전기"는?', '["덴와","덴샤","덴키","덴치"]', 2, '"덴키(電気)"입니다.', 76),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_77', '"아침"은?', '["아사","히루","요루","유가타"]', 0, '"아사(朝)"입니다.', 77),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_78', '"밤"은?', '["아사","히루","요루","유가타"]', 2, '"요루(夜)"입니다.', 78),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_79', '"배우다"는?', '["나라우","오시에루","간가에루","시라베루"]', 0, '"나라우(習う)"입니다.', 79),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_80', '"가르치다"는?', '["나라우","오시에루","간가에루","시라베루"]', 1, '"오시에루(教える)"입니다.', 80),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_81', '"생각하다"는?', '["나라우","오시에루","간가에루","시라베루"]', 2, '"간가에루(考える)"입니다.', 81),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_82', '"조사하다"는?', '["나라우","오시에루","간가에루","시라베루"]', 3, '"시라베루(調べる)"입니다.', 82),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_83', '"울다"는?', '["나쿠","와라우","오코루","오도로쿠"]', 0, '"나쿠(泣く)"입니다.', 83),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_84', '"웃다"는?', '["나쿠","와라우","오코루","오도로쿠"]', 1, '"와라우(笑う)"입니다.', 84),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_85', '"화내다"는?', '["나쿠","와라우","오코루","오도로쿠"]', 2, '"오코루(怒る)"입니다.', 85),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_86', '"놀라다"는?', '["나쿠","와라우","오코루","오도로쿠"]', 3, '"오도로쿠(驚く)"입니다.', 86),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_87', '"입다"는?', '["키루","누구","하쿠","카부루"]', 0, '"키루(着る)"입니다.', 87),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_88', '"벗다"는?', '["키루","누구","하쿠","카부루"]', 1, '"누구(脱ぐ)"입니다.', 88),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_89', '"씻다"는?', '["아라우","미가쿠","후쿠","소지스루"]', 0, '"아라우(洗う)"입니다.', 89),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_90', '"이번 주"는?', '["콘슈","라이슈","센슈","마이슈"]', 0, '"콘슈(今週)"입니다.', 90),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_91', '"다음 주"는?', '["콘슈","라이슈","센슈","마이슈"]', 1, '"라이슈(来週)"입니다.', 91),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_92', '"지난 주"는?', '["콘슈","라이슈","센슈","마이슈"]', 2, '"센슈(先週)"입니다.', 92),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_93', '"매주"는?', '["콘슈","라이슈","센슈","마이슈"]', 3, '"마이슈(毎週)"입니다.', 93),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_94', '"눈" (신체)은?', '["메","하나","미미","쿠치"]', 0, '"메(目)"입니다.', 94),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_95', '"코"는?', '["메","하나","미미","쿠치"]', 1, '"하나(鼻)"입니다.', 95),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_96', '"귀"는?', '["메","하나","미미","쿠치"]', 2, '"미미(耳)"입니다.', 96),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_97', '"입"은?', '["메","하나","미미","쿠치"]', 3, '"쿠치(口)"입니다.', 97),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_98', '"머리"는?', '["아타마","카오","테","아시"]', 0, '"아타마(頭)"입니다.', 98),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_99', '"손"은?', '["아타마","카오","테","아시"]', 2, '"테(手)"입니다.', 99),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='japanese'), 'jp_c_100', '"발"은?', '["아타마","카오","테","아시"]', 3, '"아시(足)"입니다.', 100)
ON CONFLICT (question_id) DO NOTHING;
