-- =====================================================
-- 일본어 퀴즈 시드: ADVANCED (고급) - Part 1 [1~50]
-- JLPT N2/N1 수준, 관용구, 경어, 한자 읽기
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_1', '彼は毎日忙しい（　）、ボランティアにも参加している。', '["ものの","ながら","ついでに","かわりに"]', 0, '"～ものの"는 "～이기는 하지만"입니다.', 1),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_2', 'この計画は中止する（　）を得ない。', '["わけ","こと","ほか","もの"]', 2, '"～するほかない" = ～할 수밖에 없다.', 2),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_3', '「こちらで少々（　）。」(お客様に)', '["待ってください","お待ちしてください","お待ちください","待たれてください"]', 2, '"お待ちください"가 올바른 존경어입니다.', 3),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_4', '「懸念」の読み方は？', '["けねん","けんねん","かかん","けいねん"]', 0, '"けねん" = 걱정/우려.', 4),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_5', '「躊躇」の意味は？', '["決心すること","ためらうこと","急ぐこと","中止すること"]', 1, '躊躇(ちゅうちょ) = 망설이다.', 5),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_6', '「猫の手も借りたい」の意味は？', '["猫が好きだ","とても忙しい","何もしたくない","人手が余っている"]', 1, '너무 바빠서 누구 손이라도 빌리고 싶다.', 6),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_7', '「臨機応変」の読み方は？', '["りんきおうへん","りんきこうへん","りんきょうへん","りんぎおうへん"]', 0, '"りんきおうへん"입니다.', 7),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_8', '品質（　）、デザインも優れている。', '["のみならず","ばかりか","に限らず","もかまわず"]', 0, '"～のみならず" = ～뿐만 아니라.', 8),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_9', '「一石二鳥」の意味は？', '["一つのことで二つの利益","石を投げて鳥を捕まえる","二つのことを同時に行う","損をして得を取る"]', 0, '일석이조입니다.', 9),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_10', '終電に（　）そうになった。', '["乗れ","遅れ","乗り","遅れる"]', 1, '"遅れそうになった" = 늦을 뻔했다.', 10),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_11', '「空気を読む」の意味は？', '["深呼吸する","雰囲気を察する","空を見る","天気を予想する"]', 1, '분위기를 파악하다.', 11),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_12', '「部長、申されましたか？」は正しい？', '["正しい","間違い"]', 1, '"申す"는 겸양어. 존경어는 "おっしゃる".', 12),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_13', '「前代未聞」の読み方は？', '["ぜんだいみもん","ぜんだいみぶん","ぜんだいみきき","ぜんだいみと"]', 0, '"ぜんだいみもん"입니다.', 13),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_14', '口が（　）= 秘密を守らない', '["重い","軽い","悪い","堅い"]', 1, '"口が軽い" = 입이 가볍다.', 14),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_15', '「忖度」の意味は？', '["推測すること","他人の気持ちを推し量ること","計算すること","調査すること"]', 1, '손타쿠 = 남의 마음을 헤아리다.', 15),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_16', '「齟齬」の意味は？', '["一致すること","食い違い","対立","矛盾"]', 1, '소고 = 서로 맞지 않음/어긋남.', 16),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_17', '彼の行動は理解（　）がたい。', '["し","する","され","できる"]', 0, '"～しがたい" = ～하기 어렵다.', 17),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_18', '「七転八起」の読み方は？', '["しちてんはっき","ななころびやおき","ななてんはちき","しちころびやおき"]', 1, '"ななころびやおき"입니다.', 18),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_19', '「以心伝心」の意味は？', '["心を伝える","言わなくても通じる","心が変わる","心配する"]', 1, '이심전심 = 말하지 않아도 통한다.', 19),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_20', '当社（　）努力させていただきます。', '["としましても","といたしましても","にしても","としても"]', 1, '"といたしましても"가 가장 정중한 겸양 표현.', 20),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_21', '「矛盾」の読み方は？', '["むじゅん","ぼうじゅん","むとん","ほこたて"]', 0, '"むじゅん"입니다.', 21),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_22', '「顕著」の読み方は？', '["けんちょ","けんじょ","けんちゃ","がんちょ"]', 0, '"けんちょ" = 현저하다.', 22),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_23', '「憂慮」の意味は？', '["喜ぶこと","心配すること","怒ること","悲しむこと"]', 1, '유우려 = 걱정하다/우려하다.', 23),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_24', '「唖然」の読み方は？', '["あぜん","がぜん","あねん","がねん"]', 0, '"あぜん" = 어이없어 말을 잃음.', 24),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_25', '「愕然」の読み方は？', '["かくぜん","がくぜん","きょうぜん","けんぜん"]', 1, '"がくぜん" = 깜짝 놀라다.', 25),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_26', '「おっしゃる」は何の敬語？', '["言う の尊敬語","言う の謙譲語","聞く の尊敬語","話す の謙譲語"]', 0, '"おっしゃる"는 "言う"의 존경어.', 26),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_27', '「申す」は何の敬語？', '["言う の尊敬語","言う の謙譲語","聞く の謙譲語","話す の尊敬語"]', 1, '"申す"는 "言う"의 겸양어.', 27),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_28', '「伺う」は何の敬語？', '["行く の尊敬語","聞く/行く の謙譲語","見る の謙譲語","来る の尊敬語"]', 1, '"伺う"는 "聞く/行く"의 겸양어.', 28),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_29', '「五十歩百歩」の意味は？', '["大きな差がある","ほとんど差がない","勝負がつかない","努力が足りない"]', 1, '오십보백보 = 거의 차이가 없다.', 29),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_30', '「取り越し苦労」の意味は？', '["余計な心配","実際の苦労","過去の苦労","他人の苦労"]', 0, '기우/쓸데없는 걱정.', 30),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_31', '研究の成果を（　）、論文を発表した。', '["もとに","もとで","もとから","もとまで"]', 0, '"～をもとに" = ～을 바탕으로.', 31),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_32', '「自業自得」の意味は？', '["自分の行いの報い","自分で稼ぐ","自分を信じる","自分の得意分野"]', 0, '자업자득.', 32),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_33', '「暗中模索」の意味は？', '["暗い場所を探す","手がかりなく探る","秘密裏に行動","暗い中で見る"]', 1, '암중모색 = 손잡이 없이 더듬다.', 33),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_34', '「拝見する」は何の敬語？', '["見る の尊敬語","見る の謙譲語","読む の尊敬語","読む の謙譲語"]', 1, '"拝見する"는 "見る"의 겸양어.', 34),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_35', '「ご覧になる」は何の敬語？', '["見る の尊敬語","見る の謙譲語","読む の尊敬語","読む の謙譲語"]', 0, '"ご覧になる"는 "見る"의 존경어.', 35),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_36', '試験に受かる（　）、毎日勉強した。', '["べく","ごとく","かぎり","のみ"]', 0, '"～べく" = ～하기 위해.', 36),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_37', '「付和雷同」の意味は？', '["雷に打たれる","自分の意見なく同調","強く反対する","雷のように怒る"]', 1, '부화뇌동 = 자기 의견 없이 따라 하다.', 37),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_38', '「杞憂」の意味は？', '["必要な心配","取り越し苦労","深い悲しみ","強い怒り"]', 1, '기우 = 쓸데없는 걱정.', 38),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_39', '彼は医者（　）あって、健康に詳しい。', '["だけ","こそ","ばかり","のみ"]', 0, '"～だけあって" = ～인 만큼.', 39),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_40', '「朝飯前」の意味は？', '["朝食のこと","とても簡単なこと","朝早いこと","食事の準備"]', 1, '아침밥 먹기 전 = 아주 쉬운 일.', 40),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_41', '「異口同音」の意味は？', '["違う意見","全員が同じことを言う","口論する","音楽を合わせる"]', 1, '이구동성.', 41),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_42', '「破天荒」の本来の意味は？', '["乱暴な","前代未聞の快挙","天が壊れる","荒れ果てる"]', 1, '본래 의미는 전대미문의 쾌거.', 42),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_43', '事故の原因を（　）、報告書をまとめた。', '["踏まえ","踏まえて","踏まえた上で","すべて正しい"]', 3, '"踏まえ(て/た上で)" 모두 가능.', 43),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_44', '「画竜点睛」の意味は？', '["龍の絵を描く","仕上げの大切な部分","絵画の技術","点を打つ"]', 1, '화룡점정 = 마무리의 중요한 부분.', 44),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_45', '「温故知新」の意味は？', '["温かい人","古いものから新しい知識を得る","古い友人","温泉を楽しむ"]', 1, '온고지신.', 45),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_46', '「遵守」の読み方は？', '["じゅんしゅ","そんしゅ","じゅんす","そんす"]', 0, '"じゅんしゅ" = 준수하다.', 46),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_47', '「瑕疵」の読み方は？', '["かし","かきず","かせき","かはく"]', 0, '"かし" = 하자/결함.', 47),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_48', '「忸怩」の読み方は？', '["じくじ","にくじ","じゅくじ","ぬくじ"]', 0, '"じくじ" = 부끄러워하다.', 48),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_49', '彼の努力は（　）に値する。', '["称賛","賞賛","どちらも正しい","商談"]', 2, '"称賛"과 "賞賛" 둘 다 가능.', 49),
((SELECT id FROM quiz_sets WHERE difficulty='ADVANCED' AND category='japanese'), 'jp_g_50', '「棚からぼた餅」の意味は？', '["努力の成果","思いがけない幸運","失敗すること","準備が大切"]', 1, '뜻밖의 행운.', 50)
ON CONFLICT (question_id) DO NOTHING;
