-- =====================================================
-- 과학 상식 퀴즈: BEGINNER (초급) - Part 2 [51~100]
-- =====================================================

INSERT INTO quiz_questions (set_id, question_id, question, options, correct_option_index, explanation, sort_order) VALUES
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_51', '물질이 타는 것(연소)에 필요한 3요소는?', '["연료, 산소, 점화원","연료, 물, 공기","산소, 질소, 수소","연료, 전기, 소리"]', 0, '연소의 3요소: 연료(가연물), 산소(조연물), 점화원(발화점 이상 온도).', 51),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_52', '지층이 쌓이는 순서는?', '["위가 오래됨","아래가 오래됨","관계없음","좌우로 쌓임"]', 1, '지층 누중의 법칙: 아래 지층이 더 오래된 것입니다.', 52),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_53', '화석이 만들어지기 위한 조건은?', '["화산 활동","빠른 매몰과 단단한 부위","사막 기후","높은 기온"]', 1, '생물 사체가 빠르게 매몰되어 보존되어야 합니다.', 53),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_54', '퇴적암의 예가 아닌 것은?', '["사암","석회암","이암","화강암"]', 3, '화강암은 화성암(마그마가 굳어진 암석)입니다.', 54),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_55', '변성암의 예시는?', '["대리석","현무암","사암","응회암"]', 0, '대리석은 석회암이 열과 압력을 받아 변한 변성암입니다.', 55),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_56', '식물의 증산 작용은 주로 어디서 일어나나요?', '["뿌리","줄기","잎의 기공","꽃"]', 2, '잎의 기공을 통해 수증기가 배출되는 것이 증산 작용입니다.', 56),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_57', '전지의 직렬 연결은 어떤 효과가 있나요?', '["전압 증가","전류 증가","저항 감소","효과 없음"]', 0, '직렬 연결 시 전압이 합산되어 증가합니다.', 57),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_58', '전지의 병렬 연결은 어떤 효과가 있나요?', '["전압 증가","사용 시간 증가","저항 증가","아무 효과 없음"]', 1, '병렬 연결 시 전압은 같지만 사용 시간이 늘어납니다.', 58),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_59', '렌즈의 종류 중 중간이 두꺼운 것은?', '["오목렌즈","볼록렌즈","평면렌즈","이중렌즈"]', 1, '볼록렌즈는 중간이 두껍고 빛을 모읍니다.', 59),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_60', '근시를 교정하는 렌즈는?', '["볼록렌즈","오목렌즈","원통렌즈","평면렌즈"]', 1, '근시는 오목렌즈(발산렌즈)로 교정합니다.', 60),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_61', '원시를 교정하는 렌즈는?', '["볼록렌즈","오목렌즈","원통렌즈","평면렌즈"]', 0, '원시는 볼록렌즈(수렴렌즈)로 교정합니다.', 61),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_62', '식물의 줄기가 하는 일은?', '["물과 양분 흡수","물과 양분 수송","광합성","종자 생산"]', 1, '줄기는 뿌리에서 흡수한 물과 양분을 잎으로 운반합니다.', 62),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_63', '나선 은하의 대표적 예는?', '["안드로메다은하","목성","달","소행성대"]', 0, '안드로메다은하는 나선 은하의 대표적 예입니다.', 63),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_64', '우리 은하의 이름은?', '["안드로메다은하","은하수(밀키웨이)","마젤란은하","처녀자리 은하"]', 1, '우리 은하는 은하수(Milky Way)라고 합니다.', 64),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_65', '암석의 3대 분류는?', '["화성암, 퇴적암, 변성암","화강암, 현무암, 대리석","사암, 이암, 석회암","석영, 장석, 운모"]', 0, '암석은 화성암, 퇴적암, 변성암으로 분류합니다.', 65),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_66', '탄소(C)의 동소체가 아닌 것은?', '["다이아몬드","흑연","풀러렌","석영"]', 3, '석영은 SiO₂이고, 탄소 동소체는 다이아몬드, 흑연, 풀러렌 등.', 66),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_67', '소화(화재 진압)의 원리가 아닌 것은?', '["연료 제거","산소 차단","온도 낮추기","습도 높이기"]', 3, '소화는 연소 3요소 중 하나 이상을 제거하는 것입니다.', 67),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_68', '줄기세포란 무엇인가요?', '["이미 분화된 세포","다양한 세포로 분화할 수 있는 세포","죽은 세포","암세포"]', 1, '줄기세포는 여러 종류의 세포로 분화할 수 있는 미분화 세포입니다.', 68),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_69', '전자기파 중 파장이 가장 긴 것은?', '["감마선","X선","가시광선","라디오파"]', 3, '라디오파가 가장 긴 파장을 가집니다.', 69),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_70', '전자기파 중 에너지가 가장 큰 것은?', '["감마선","마이크로파","적외선","라디오파"]', 0, '감마선이 가장 높은 에너지(짧은 파장)를 가집니다.', 70),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_71', '물이 높은 곳에서 낮은 곳으로 흐르는 이유는?', '["바람","중력","자기력","전기력"]', 1, '중력에 의해 물은 높은 곳에서 낮은 곳으로 흐릅니다.', 71),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_72', '기압이 낮아지면 날씨는 어떻게 되나요?', '["맑아진다","흐려지고 비가 올 수 있다","바람이 멈춘다","기온이 올라간다"]', 1, '저기압은 상승기류를 만들어 구름과 비를 동반합니다.', 72),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_73', '해류의 영향이 아닌 것은?', '["기후 조절","어장 형성","지진 발생","해양 생태계 유지"]', 2, '해류는 기후, 어장, 생태계에 영향을 주지만 지진과는 무관합니다.', 73),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_74', '비중이 1보다 큰 물체는 물에?', '["뜬다","가라앉는다","반쯤 잠긴다","녹는다"]', 1, '비중이 1보다 크면(물보다 밀도가 높으면) 가라앉습니다.', 74),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_75', '뉴턴의 운동 제2법칙(F=ma)에서 a는?', '["질량","힘","가속도","속도"]', 2, 'a는 가속도입니다. F=ma (힘=질량×가속도).', 75),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_76', '지구의 자전 방향은?', '["서→동","동→서","남→북","북→남"]', 0, '지구는 서쪽에서 동쪽으로 자전합니다.', 76),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_77', '일식이 일어나는 조건은?', '["달-태양-지구 순서","태양-달-지구 순서","지구-달-태양 순서","관계없음"]', 1, '일식은 태양-달-지구 순으로 일직선이 되면 발생합니다.', 77),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_78', '월식이 일어나는 조건은?', '["태양-지구-달 순서","태양-달-지구 순서","달-지구-태양 순서","관계없음"]', 0, '월식은 태양-지구-달 순으로 일직선이 되면 발생합니다.', 78),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_79', '산성비의 주된 원인 물질은?', '["CO₂","SO₂, NOₓ","O₃","H₂O"]', 1, '이산화황(SO₂)과 질소산화물(NOₓ)이 산성비의 주원인입니다.', 79),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_80', '일(Work)의 공식은?', '["힘 × 거리","힘 ÷ 거리","질량 × 속도","질량 × 가속도"]', 0, '일(W) = 힘(F) × 이동거리(d)입니다.', 80),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_81', '역학적 에너지 보존이란?', '["운동 에너지만 보존","위치 에너지만 보존","운동 + 위치 에너지의 합이 일정","에너지가 사라짐"]', 2, '마찰 무시 시 운동에너지 + 위치에너지 = 일정합니다.', 81),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_82', '호르몬을 분비하는 기관을 무엇이라 하나요?', '["소화기관","내분비선","근육","뼈"]', 1, '내분비선(갑상선, 부신 등)이 호르몬을 분비합니다.', 82),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_83', '인슐린은 어디서 분비되나요?', '["갑상선","뇌하수체","췌장","부신"]', 2, '인슐린은 췌장(이자)의 베타 세포에서 분비됩니다.', 83),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_84', '신장(콩팥)의 주된 역할은?', '["산소 운반","노폐물 여과(소변 생성)","소화","호르몬 분비"]', 1, '신장은 혈액에서 노폐물을 걸러 소변을 만듭니다.', 84),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_85', '생태계에서 분해자의 역할을 하는 생물은?', '["사자","풀","균류(곰팡이)와 세균","독수리"]', 2, '곰팡이, 세균 등 분해자가 죽은 유기물을 분해합니다.', 85),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_86', '먹이 사슬의 시작은 보통?', '["초식동물","육식동물","생산자(식물)","분해자"]', 2, '먹이 사슬은 생산자(식물)에서 시작됩니다.', 86),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_87', '옴의 법칙(V=IR)에서 I는?', '["전압","전류","저항","전력"]', 1, 'I는 전류(암페어)입니다.', 87),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_88', '합금이란?', '["순수 금속","두 종류 이상의 금속을 섞은 것","비금속","액체 금속"]', 1, '합금은 두 종류 이상의 금속(또는 금속+비금속)을 섞은 것입니다.', 88),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_89', '스테인리스강은 무엇의 합금인가요?', '["철+구리","철+크롬+니켈","철+금","구리+주석"]', 1, '스테인리스강은 철에 크롬, 니켈을 섞은 합금입니다.', 89),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_90', '청동은 무엇의 합금인가요?', '["철+구리","구리+주석","금+은","알루미늄+철"]', 1, '청동은 구리와 주석의 합금입니다.', 90),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_91', '태양계 행성 중 가장 작은 것은?', '["화성","수성","금성","지구"]', 1, '수성은 태양계에서 가장 작은 행성입니다.', 91),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_92', '태양계 행성 중 가장 뜨거운 표면 온도를 가진 것은?', '["수성","금성","화성","목성"]', 1, '금성은 두꺼운 CO₂ 대기 때문에 표면 온도가 약 460°C입니다.', 92),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_93', '감수분열의 결과 만들어지는 세포는?', '["체세포","생식세포(정자, 난자)","신경세포","근육세포"]', 1, '감수분열은 생식세포(정자, 난자)를 만듭니다.', 93),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_94', 'DNA의 이중나선 구조를 발견한 사람은?', '["멘델","다윈","왓슨과 크릭","아인슈타인"]', 2, '왓슨과 크릭이 1953년 DNA 이중나선 구조를 발표했습니다.', 94),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_95', '진화론을 주장한 사람은?', '["뉴턴","다윈","아인슈타인","갈릴레오"]', 1, '찰스 다윈이 자연선택에 의한 진화론을 주장했습니다.', 95),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_96', '유전학의 아버지로 불리는 사람은?', '["멘델","다윈","왓슨","파스퇴르"]', 0, '그레고르 멘델이 완두콩 실험으로 유전 법칙을 발견했습니다.', 96),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_97', '반도체의 대표적 원소는?', '["구리","실리콘","철","금"]', 1, '실리콘(규소, Si)은 대표적인 반도체 물질입니다.', 97),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_98', '지구 온난화의 주된 온실가스는?', '["산소","질소","이산화탄소","수소"]', 2, 'CO₂가 가장 대표적인 온실가스입니다.', 98),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_99', '플레밍의 왼손 법칙은 무엇에 관한 것인가요?', '["열전도","전동기(모터)","발전기","화학반응"]', 1, '플레밍의 왼손 법칙은 전동기(모터) 원리입니다.', 99),
((SELECT id FROM quiz_sets WHERE difficulty='BEGINNER' AND category='science'), 'sc_c_100', '플레밍의 오른손 법칙은 무엇에 관한 것인가요?', '["열전도","전동기(모터)","발전기","화학반응"]', 2, '플레밍의 오른손 법칙은 발전기 원리입니다.', 100)
ON CONFLICT (question_id) DO NOTHING;
