package realestate.server.application.realestate.domain;

import lombok.Builder;

import java.time.LocalDateTime;

@Builder
public record AptPblanc(
        Long id,
        String houseManageNo,
        String pblancNo,
        String houseNm,
        String houseSecd,
        String houseSecdNm,
        String houseDtlSecd,
        String houseDtlSecdNm,
        String rentSecd,
        String rentSecdNm,
        String subscrptAreaCode,
        String subscrptAreaCodeNm,
        String sggCode,
        String hssplyZip,
        String hssplyAdres,
        Integer totSuplyHshldco,
        String rcritPblancDe,
        String nsprcNm,
        String rceptBgnde,
        String rceptEndde,
        String spsplyRceptBgnde,
        String spsplyRceptEndde,
        String gnrlRnk1CrspareaRcptde,
        String gnrlRnk1CrspareaEndde,
        String gnrlRnk1EtcGgRcptde,
        String gnrlRnk1EtcGgEndde,
        String gnrlRnk1EtcAreaRcptde,
        String gnrlRnk1EtcAreaEndde,
        String gnrlRnk2CrspareaRcptde,
        String gnrlRnk2CrspareaEndde,
        String gnrlRnk2EtcGgRcptde,
        String gnrlRnk2EtcGgEndde,
        String gnrlRnk2EtcAreaRcptde,
        String gnrlRnk2EtcAreaEndde,
        String przwnerPresnatnDe,
        String cntrctCnclsBgnde,
        String cntrctCnclsEndde,
        String hmpgAdres,
        String cnstrctEntrpsNm,
        String mdhsTelno,
        String bsnsMbyNm,
        String mvnPrearngeYm,
        String specltRdnEarthAt,
        String mdatTrgetAreaSecd,
        String parcprcUlsAt,
        String imprmnBsnsAt,
        String publicHouseEarthAt,
        String lrsclBldlndAt,
        String nplnPrvoprPublicHouseAt,
        String publicHouseSpclwApplcAt,
        String pblancUrl,
        LocalDateTime createdAt) {
}
